shuding/nextra

.nextra/styles.css, .nextra/theme.js, .prettierignore, package.json, pages/headers.md, pages/meta.json, yarn.lock
- Standardizes the spacing for all header elements (h1 through h6)
- Adds a hash link to each of them
- Show `#` on hover, as per feedback
- Added Prettier config
pages/headers has an example.
=> Add anchors and hash to all headers, add Prettier

package.json, src/loader.js
Testing passed both on macOS and Windows
Fixes #10
=> Convert Windows backslash path to slash path

packages/nextra/src/loader.js
For some reason when I cloned nextra-docs meta.json files were considered "META" from my editor and I kept doing silly mistakes.
-- Not sure why the deploy failed, but I would assume it's because It's not on my vercel account?
=> fix(loader): JSON parse throwing if isn't valid

packages/nextra/src/loader.js
If there is a file with empty basename in the `pages` directory, will break the building process. Ignore them to fix.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shuding/nextra/62)
=> Ignore files with empty basename, like .DS_Store etc

packages/nextra/src/index.js
I made a change to support more options to accept mdx-js/loader options: e.g. remarkPlugins and rehypePlugins.
```js
// this still works
const withNextra = require("nextra")("./theme", "./theme.config.js")
// also object can be accepted
const withNextra = require("nextra")({
theme: "./theme",
themeConfig: "./theme.config.js",
mdxOptions: {
remarkPlugins: [require("remark-emoji")]
}
})
```
Note: If #75 is merged first, the type definition needs to be modified as well.
=> Accept mdx options

examples/docs/theme.config.js, packages/nextra-theme-docs/src/misc/default.config.js
follow og protocol, use `property` and `content` to describe pairs
reference: https://ogp.me
=> fix: og protocol peropty in meta

packages/nextra-theme-docs/src/index.js
This is my proposal to fix the issue that a logo with SVG image won't be centered vertically properly as described in https://github.com/vercel/swr-site/issues/71
=> Change the logo wrapper from inline to block

packages/nextra-theme-docs/src/index.js, packages/nextra-theme-docs/src/misc/default.config.js, packages/nextra-theme-docs/src/styles.css
So users can change to another font/font-display strategy easily.
=> Option for disabling the default font

packages/nextra-theme-docs/src/search.js, packages/nextra-theme-docs/src/stork-search.js
Currently pressing '/' pulls focus from inputs, etc. Looks like this isn't intended, just an wandering bracket.
Cheers!
=> Fix search focusing

packages/nextra-theme-docs/src/callout.js
Noticed that some emojis are not being rendered by the correct font:
This PR fixes that:
=> Update Callout component to correctly support emojis

packages/nextra/src/index.js
Even when the stork is not enabled.
Stork runs on the build.
=> build stork index only when stork:true

packages/nextra-theme-blog/package.json, packages/nextra-theme-blog/src/index.js, yarn.lock
I add a `comments` props in `Layout`, so if we want to add another comment widget, we can just pass different `comments` component to the `Layout`
In `theme.config.js`:
```js
export default {
cusdis: {
appId: 'xxx',
host: 'https://cusdis.com', // optional
lang: 'zh-cn', // optional
}
}
```
=> Support Cusdis in nextra-theme-blog

packages/nextra-theme-docs/src/index.js
Bug is seen when fresh-loading a page from a URL that contains header tags:
```
http://localhost:3000/foo#bar
```
(as opposed to without header tags: `http://localhost:3000/foo`)
1. Next/Prev Links at the footer will become just one Next Link, which will point to the first file in meta.json
2. Sidebar tree will not expand for the current page
This PR fixes that
=> Fixed fresh loading from URLs containing header tags

examples/docs/pages/nextra/about.en.md, packages/nextra/package.json, packages/nextra/react17-loader.js, packages/nextra/src/index.js, packages/nextra/src/loader.js, packages/nextra/src/react17-loader.js, packages/nextra/src/static-image.js, yarn.lock
Since GFM was removed from `@mdx-js/loader` 2.0, let's add the Remark GFM plugin by default. Also the `jsxRuntime classic` pragma can be removed too.
Closes #127, #141.
=> Fix GFM support and upgrade MDX loader

examples/docs/next.config.js, examples/docs/theme.config.js, packages/nextra-theme-docs/src/index.js, packages/nextra/src/index.js, packages/nextra/src/loader.js
This feature is very unstable and will probably be removed in the future.
=> Prefix stork options with `unstable_`

examples/docs/theme.config.js, packages/nextra-theme-docs/src/index.js
When this option is set, the value will be displayed as a `<text>` content of SVG inside the favicon. The color will be adjusted based on the preferred color scheme.
Demo: https://twitter.com/shuding_/status/1411619791127908353
=> Add `unstable_faviconGlyph` option to the docs theme

examples/docs/pages/nextra/about.en.md, packages/nextra-theme-blog/src/mdx-theme.js, packages/nextra-theme-docs/src/misc/theme.js
Adds support for ranges as well in the `highlight=` option:
```jsx highlight=1,4,6-8
import useSWR from 'swr'
function App() {
const { data, error } = useSWR('/api/user', fetcher)
if (error) return <div>failed to load</div>
if (!data) return <div>loading...</div>
return <div>hello {data.name}!</div>
}
```
=> Support highlighting a range of code lines

examples/docs/theme.config.js, packages/nextra-theme-docs/package.json, packages/nextra-theme-docs/src/footer.js, packages/nextra-theme-docs/src/index.js, packages/nextra-theme-docs/src/misc/default.config.js, yarn.lock
This PR updates the following options:
- `repository` → `github`, because it's explicitly a link to GitHub, not GitLab or other repository URLs.
- `docsRepository` → `docsRepositoryBase`, so it can include branch and subpath information.
- `branch`, `path` → removed, they're included in the option above and their namings are also confusing.
- `footerEditOnGitHubLink`, `footerEditOnGitHubText` → `footerEditLink`, it's not necessarily a GitHub link.
=> Normalize option names

packages/nextra-theme-blog/src/index.js
This PR brings the "titleSuffix" to the "blog" theme. It's similar to the one in the "docs" theme.
For example, with `titleSuffix: "- Shudin"`, the page https://shud.in/art will have the title "Arts - Shudin" instead of just "Arts". This only applies for the title inside "head" tag.
Implementation notes:
- There is no default value in order to be backward compatible (do you want me to change it to "- Nextra" like in the "docs" theme?)
- There is no "renderComponent" utility in the "blog" project so I just render the titleSuffix naively. Please tell me if this needs change.
Thank you
=> add titleSuffix config to blog theme

pages/themes/docs/callout.mdx
The last callout (explaining `error`) has type `warning` instead of `error` .
=> Code example error

pages/get-started.mdx, pages/index.mdx
Actually the link in the Introduction Page is returning a 404 error.
=> fix(docs): added an anchor link to fix the issue

pages/themes/blog/index.mdx
The blog install should use the blog theme, not the docs theme. Not sure if there are other issues that could be fixed related to this, but I found a small gotcha in the docs.
=> Bugfix(docs): Change docs to blog theme

packages/nextra/src/loader.js
Addresses https://github.com/shuding/nextra/issues/214
build nextra site on Windows
Before: 
Click on nav links; no `active` class name added (because routes don't match)
After:
Active nav link has the `active` class
=> Fixing routes so they work in Windows

packages/nextra-theme-docs/src/misc/default.config.js, packages/nextra-theme-docs/src/navbar.js
This adds the new config option `gitIcon` to change the icon in the top right corner and replaces the `github` option with `gitLink` (for uniform naming, but the old option will still work).
Closes #175 
Example config:
```ts
import Gitlab from "@geist-ui/react-icons/gitlab";
const themeConfig = {
gitLink: "https://gitlab.com/librewolf-community/browser",
gitIcon: <Gitlab />,
// ...
```
Result:
=> Add option to change the Git icon in the top right corner

packages/nextra-theme-docs/src/search.js, packages/nextra-theme-docs/src/stork-search.js
Polishing the search input a bit. 
I wonder if we should switch this to <kbd> ⌘</kbd> + <kbd>K</kbd> to mimic algolia doc search. The reason I prefer this over <kbd>/</kbd> is because it doesn't interfere with interactive react/html/mdx playgrounds.
=> Stripe-like search input

packages/nextra-theme-docs/src/sidebar.js
This will fix the sidebar for the case that `trailingSlash` is enabled in `next.config.js` (That option adds an `/` to the end of the routes and thus makes `next export` more useful).
Before:
After:
Of course everything still works as expected when `trailingSlash` is off.
=> Fix sidebar for `trailingSlash: true`

packages/nextra-theme-blog/package.json
Got error after upgrade
```
Server Error
SyntaxError: Unexpected token 'export'
This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
<unknown>
/Users/promer94/workspace/blog/node_modules/.pnpm/nextra-theme-blog (2.0.0-beta.2_f195614718841b3c14a81ac95268ce58/node_modules/nextra-theme-blog/index.js (1)
Object.compileFunction
node:vm (352:18)
wrapSafe
node:internal/modules/cjs/loader (1031:15)
Module._compile
node:internal/modules/cjs/loader (1065:27)
Object.Module._extensions..js
node:internal/modules/cjs/loader (1153:10)
Module.load
node:internal/modules/cjs/loader (981:32)
Function.Module._load
node:internal/modules/cjs/loader (822:12)
Module.require
node:internal/modules/cjs/loader (1005:19)
```
=> add exports

packages/nextra-theme-docs/src/search.js
This fixes a minor bug when there are no active results, this PR checks if there are results and if there is an `results[active]`
=> fix(Search): check for active results on `Enter` key

packages/nextra-theme-docs/src/index.js
This fixes some issues on pages with the type `nav` in the `meta.json`. Currently, the next links, syntax highlighting and probably other things aren't working on those pages because of what I assume is a typo.
=> Fix broken "nav" pages

package.json
having both `types` and `dist` caching with ** is probably not right, so restricting to respective extensions
=> Safer turbo caching

packages/nextra/package.json
Hello.
I found footnotes not working in the [nextra blog sample](https://demo.vercel.blog/posts/markdown). So I want to add a footnote.
After changing the [remark-gfm version to 3](https://github.com/remarkjs/remark-gfm/releases/tag/3.0.0), the footnote function works.
=> use remark-gfm v3.0.1

pages/themes/blog/index.mdx
`yarn next` wouldn't build a site w/o it!
=> insert missing comma

packages/nextra/package.json
Alpha versions dist folder doesn't have an type file - https://unpkg.com/browse/nextra@2.0.0-alpha.16/dist/
=> Add types script to prepublishOnly

packages/nextra/src/content-dump.ts, packages/nextra/src/loader.ts
Since Webpack doesn't have glob dependency support for loaders, we're now doing the following:
```js
if (!isProductionBuild) {
// Add the entire directory `pages` as the dependency
// so we can generate the correct page map.
this.addContextDependency(pagesDir)
} else {
// We only add meta files as dependencies for prodution build,
// so we can do incremental builds.
Object.entries(fileMap).forEach(([filePath, { name, meta, locale }]) => {
if (
name === 'meta.json' &&
meta &&
(!fileLocale || locale === fileLocale)
) {
this.addDependency(filePath)
}
})
}
```
=> Fix dependency resolving

packages/nextra-theme-docs/src/styles.css
| Light | Dark |
| ------ | ----- |
|![Screenshot 2022-02-17 at 14-10-30 React Hooks for Data Fetching – SWR](https://user-images.githubusercontent.com/10325111/154417678-9d1f792b-3db7-482d-9c4a-38fa36541765.png)|![Screenshot 2022-02-17 at 14-10-15 React Hooks for Data Fetching – SWR](https://user-images.githubusercontent.com/10325111/154417673-1463220b-e213-40a9-983d-3fad7d575e5f.png)|
| Light | Dark |
| ------ | ----- |
|<img width="1552" alt="截圖 2022-02-17 下午2 09 29" src="https://user-images.githubusercontent.com/10325111/154417825-f3089163-df39-48b1-a275-0cac153ca8d3.png">|<img width="1552" alt="截圖 2022-02-17 下午2 09 40" src="https://user-images.githubusercontent.com/10325111/154417832-7df68aa8-8d2c-4ee2-b15b-37374a382fb4.png">|
Hi @shuding, thank you for creating an amazing static …
=> fix(search): add fallback bg-color for search result

packages/nextra-theme-blog/src/utils/sort-date.ts
The comparison function needs to return 0 when elements are equal. Otherwise, when dates are equal (as in a previous version of the blog example), the ordering of the navbar becomes non-deterministic between engines.
=> fix sort-date

README.md, packages/nextra-theme-docs/src/search.tsx
The proposed changes help address issue https://github.com/vercel/swr-site/issues/195, specifically, where the search is currently not working when:
1. User performs a search, then
2. User receives some search results, then
3. User uses their mouse to click on a search result in hopes of being navigated to the corresponding search result page
Currently, step 3 does not work as expected. This PR addresses this in addition to:
- Corrects a minor typo on the core README
- Updates the search result list items' HTML to be more semantically correct from a structure perspective
**Additional notes:**
* Search feature in production currently works for key events (e.g. pressing `enter`). 
* I performed some regression testing and things seem a-okay but would appreciate any pointers/edge cases …
=> Issue 195: Fixing search in core

examples/docs/src/theme.config.js, examples/swr-site/next.config.js, packages/nextra/src/compile.ts, packages/nextra/src/loader.ts, packages/nextra/src/plugin.ts, packages/nextra/src/types.ts
In preparation for 2.0 stable release, we will rename it to just `flexsearch` soon.
=> breaking: Rename unstable_contentDump to unstable_flexsearch

examples/swr-site/pages/docs/meta.en-US.json, examples/swr-site/pages/meta.en-US.json, packages/nextra-theme-docs/src/index.tsx, packages/nextra-theme-docs/src/navbar.tsx, packages/nextra-theme-docs/src/sidebar.tsx, packages/nextra-theme-docs/src/utils/normalize-pages.tsx
Closes #341.
Add a link to the navbar/sidebar:
```json
"nextra_link": {
"title": "Nextra ↗",
"href": "https://github.com/shuding/nextra",
"type": "page",
"newWindow": true
},
```
Hide a page/directory in navbar/sidebar:
```json
"error-handling": {
"title": "Error Handling",
"hidden": true
},
```
=> Options for hiding/adding a link

packages/nextra/context.js, packages/nextra/scripts/build.js, packages/nextra/scripts/dev.js, packages/nextra/src/context.ts, packages/nextra/src/loader.ts
Resolves #368.
The following APIs are now supported inside your MDX files:
```
import { getAllPages, getCurrentLevelPages, getPagesUnderRoute } from 'nextra/context'
{console.log(getAllPages())}
{console.log(getCurrentLevelPages())}
{console.log(getPagesUnderRoute('/blog'))}
```
This will be extremely helpful for building an index page. The blog theme can be refactored based on this.
=> Expose the page map starting from the current level

examples/swr-site/pages/blog.en-US.mdx, examples/swr-site/pages/docs/advanced.en-US.mdx, packages/nextra-theme-docs/package.json, packages/nextra-theme-docs/src/index.tsx, packages/nextra-theme-docs/src/navbar.tsx, packages/nextra-theme-docs/src/sidebar.tsx, packages/nextra-theme-docs/src/styles.css, packages/nextra-theme-docs/src/theme-switch.tsx, packages/nextra-theme-docs/src/utils/normalize-pages.tsx, packages/nextra/src/loader.ts, pnpm-lock.yaml
If you have a directory `/blog`, together with a page `/blog.mdx`, the page now becomes the index page of that directory.
Check the "Advanced" folder and "Blog" page of the deployed demo for more details.
=> Support for adding index page for directories

examples/swr-site/pages/_app.js, packages/nextra-theme-docs/package.json, packages/nextra-theme-docs/src/icons/arrow-right.tsx, packages/nextra-theme-docs/src/index.tsx, packages/nextra-theme-docs/src/navbar.tsx, packages/nextra-theme-docs/src/polyfill.tsx, packages/nextra-theme-docs/src/sidebar.tsx, packages/nextra-theme-docs/src/styles.css, packages/nextra-theme-docs/src/toc.tsx, packages/nextra-theme-docs/src/utils/normalize-pages.tsx, packages/nextra-theme-docs/tailwind.config.js, packages/nextra/src/loader.ts, packages/nextra/src/ssg.ts
With the docs theme, it's now required to have this layout function:
```js
export default function MyApp({ Component, pageProps }) {
// Use the layout defined at the page level, if available
const getLayout = Component.getLayout || ((page) => page);
return getLayout(<Component {...pageProps} />);
}
```
=> breaking: Layout element and style improvements

packages/nextra-theme-docs/src/head.tsx
@shuding I was solving my issue described here #379, and I found what is the issue.
This PR will add a support for passing a function in `config.head` configuration for Docs theme.
To support `config.head` as a function we need to have latest code from `core` branch for `renderComponent` metod:
```
const renderComponent = <T,>(
ComponentOrNode: React.FC<T> | React.ReactNode,
props: T,
functionOnly?: boolean
) => {
if (!ComponentOrNode) return null
if (typeof ComponentOrNode === 'function') {
if (functionOnly) return ComponentOrNode(props)
return <ComponentOrNode {...props} />
}
return ComponentOrNode
}
```
Note that this is not a function we have in latest tag (`v2.0.0-beta.5`). The `functionOnly` is added later.
Important part is we have `functionOnly` and in case it is true we return ` …
=> the head config to support function in doc theme

examples/swr-site/pages/docs/change-log.en-US.mdx, packages/nextra/data.js, packages/nextra/package.json, packages/nextra/src/ssg.ts
Simply because this can be used for SSR/ISR. The prop is not limited to `ssg` as long as a key is passed.
But we are keeping the old API support too.
=> Rename nextra/ssg to nextra/data

packages/nextra-theme-blog/package.json, packages/nextra-theme-docs/package.json, pnpm-lock.yaml
Found this "bug" where you can't build on windows on a fresh clone because it doesn't recognize that you're trying to set an env var. This should work cross-platform
=> usee cross-env to set env vars

packages/nextra/src/compile.ts, packages/nextra/src/loader.ts
With a syntax error in a markdown/MDX file, the build gives no feedback as to what authored file is the cause of the problem. Could this be addressed  through a strategy along the lines of the proposal in this PR? This will report the file at fault, and an attempt at the line location (unfortunately an attempt that usually doesn't match up with the actual line, for reasons I don't understand).
For example:
```
raidocs:build: info  - Loaded env from /home/robbear/dev/robbear/rai-ux/raidocs/site/.env.production
raidocs:build: info  - Checking validity of types...
raidocs:build: warn  - The Next.js plugin was not detected in your ESLint configuration. See https://nextjs.org/docs/basic-features/eslint#migrating-existing-config
raidocs:build: info  - Creating an optimized production build... …
```
=> Discussion: Feedback for MDX compilation failure

examples/swr-site/pages/docs/advanced/meta.en-US.json, examples/swr-site/pages/meta.en-US.json, packages/nextra-theme-docs/src/index.tsx, packages/nextra-theme-docs/src/misc/theme-context.tsx, packages/nextra-theme-docs/src/styles.css, packages/nextra-theme-docs/src/utils/normalize-pages.tsx
Breaking change:
```
"theme": {
"full": true
}
```
will be:
```
"theme": {
"layout": "full"
}
```
It will support three options: "default", "full" and "raw". "raw" will not be wrapped by `<MDXContent>` and `article`.
---
Also the `*` key will be used as the fallback configuration for all pages in the same level:
```
{
"*": {
"type": "page",
"theme": {
"sidebar": true
}
},
"a": "A",
"b": {
"title": "B",
"theme": {
"sidebar": false
}
}
}
```
=> Add `layout` option and `*` fallback of meta.json

packages/nextra-theme-blog/src/index.tsx
Using `<ul>` adds unnecessary left padding to the post item list and changing it to `<div>` removes the padding.
=> fix(theme-blog): remove extra padding from post-item list

packages/nextra/context.js, packages/nextra/data.js, packages/nextra/index.js, packages/nextra/locales.js, packages/nextra/package.json, packages/nextra/scripts/build.js, packages/nextra/scripts/dev.js, packages/nextra/src/compile.ts, packages/nextra/src/types.ts, packages/nextra/ssg.js
`compileMdx` is a pretty useful function for me, but unfortunately, it is not exported by Nextra, and I use this function with [`next-mdx-remote`](https://github.com/hashicorp/next-mdx-remote)
P.S. also I found a way to remove dummy `context.js`, `data.js`, `index.js`, `locales.js` and `ssg.js` files by configuring the `exports` field in `package.json`
=> feat(nextra): export `compile.tsx`

packages/nextra/src/env.d.ts
`slash` already provides types and there is no more `download` package
=> fix(nextra): Update env.d.ts

.changeset/pretty-tips-invite.md, packages/nextra/src/compile.ts, packages/nextra/src/types.ts
fixes https://github.com/shuding/nextra/issues/555
=> feat(nextra): allow define custom languages for shiki with `mdxOptions.rehypePrettyCodeOptions` option

.changeset/nasty-radios-joke.md, packages/nextra-theme-docs/src/misc/theme-context.ts
I renamed the extension to `ts` since there is no `jsx` content in this function
=> chore(nextra-theme-docs): refactor `theme-context.ts`

.changeset/stale-masks-change.md, .github/workflows/release.yml, package.json
It seems there's a bug in the Changeset package resolution process where private packages are included too. One workaround is to limit the workspace to only include the ones inside `packages/`.
=> Fix release workflow

.changeset/spicy-swans-check.md, examples/swr-site/components/external.mdx, examples/swr-site/pages/docs/advanced/markdown-import.en-US.mdx, examples/swr-site/pages/docs/advanced/meta.en-US.json, packages/nextra-theme-blog/src/index.tsx, packages/nextra-theme-docs/src/index.tsx, packages/nextra/__test__/__snapshots__/page-map.test.ts.snap, packages/nextra/src/loader.ts, packages/nextra/src/plugin.ts
fixes https://github.com/shuding/nextra/issues/83
<s>depend on https://github.com/shuding/nextra/pull/546 since I already touched `plugin.ts`</s>
review only last commit
=> feat(nextra/docs/blog): allow import `.md`/`.mdx` as well

.changeset/eight-carpets-pretend.md, packages/nextra-theme-docs/src/index.tsx, packages/nextra-theme-docs/src/misc/default.config.tsx, packages/nextra-theme-docs/src/types.ts
=> chore(nextra-theme-docs): provide type for `DocsThemeConfig.nextThemes` instead of `object`

.changeset/large-ligers-doubt.md, .npmrc
Fixes the `ERR_PNPM_PEER_DEP_ISSUES  Unmet peer dependencies` error in dev deployments.
=> chore: Add `strict-peer-dependencies=false`

.changeset/silent-games-nail.md, packages/nextra/src/loader.ts
because filename will be always `md`/`mdx` file
https://github.com/shuding/nextra/blob/417918abb9c87f6862a6f24115ee092e03d49f5b/packages/nextra/src/index.js#L44
=> chore: remove redundant check for `MARKDOWN_EXTENSION_REGEX.test(filename)` in loader

.changeset/modern-toys-admire.md, examples/swr-site/pages/about/a-page.en-US.mdx, examples/swr-site/pages/about/acknowledgement.en-US.mdx, examples/swr-site/pages/about/meta.en-US.json, examples/swr-site/pages/about/team.en-US.mdx, examples/swr-site/pages/meta.en-US.json, packages/nextra-theme-docs/__test__/__snapshots__/normalize-page.spec.ts.snap, packages/nextra-theme-docs/src/index.tsx, packages/nextra-theme-docs/src/navbar.tsx, packages/nextra-theme-docs/src/select.tsx, packages/nextra-theme-docs/src/sidebar.tsx, packages/nextra-theme-docs/src/utils/normalize-pages.tsx, packages/nextra/__test__/__snapshots__/page-map.test.ts.snap
This is a new navbar item type that shows a dropdown menu:
To-do:
=> feat: `menu` type

.changeset/olive-frogs-greet.md, examples/swr-site/theme.config.js, packages/nextra-theme-docs/src/head.tsx, packages/nextra-theme-docs/src/types.ts, packages/nextra-theme-docs/src/utils/render-component.tsx
fixes console warning
and possible issue when declaring `titleSuffix` as function
=> [nextra-theme-docs]: fix `Warning: A title element received an array` and possible `[object Object]` in title

.changeset/quick-cobras-end.md, packages/nextra-theme-docs/src/callout.tsx, packages/nextra-theme-docs/src/css/styles.css, packages/nextra-theme-docs/src/flexsearch.jsx, packages/nextra-theme-docs/src/search.tsx, packages/nextra-theme-docs/src/select.tsx, packages/nextra-theme-docs/src/sidebar.tsx
Tailwind recommends using new opacity modifier syntax https://tailwindcss.com/docs/upgrade-guide#new-opacity-modifier-syntax
=> [nextra-theme-docs]: use new opacity modifier syntax for tailwindcss

.changeset/lemon-bags-check.md, packages/nextra-theme-docs/src/index.tsx, packages/nextra/src/index.js, packages/nextra/src/loader.ts
Closes #594. I noticed that the flexsearch option being overridden here:
Which is not needed, we should just remove it.
=> Fix flexsearch option being overridden

.changeset/witty-tools-repair.md, packages/nextra-theme-blog/src/mdx-theme.tsx, packages/nextra-theme-blog/src/posts-layout.tsx
Even though these classes are not used within nextra for styling, these are still useful for users to be able to target these classes and override the styles.
cc @B2o5T
=> change(blog): add missing class names to override styles

.changeset/chatty-gifts-dress.md, packages/nextra-theme-docs/package.json, packages/nextra-theme-docs/src/index.tsx
There's actually one import includes side effects, everything inside `dist` should be good.
=> Fix `sideEffects` in the docs theme

.changeset/seven-bobcats-battle.md, examples/swr-site/pages/about/meta.en-US.json, examples/swr-site/pages/meta.en-US.json, packages/nextra-theme-docs/src/index.tsx, packages/nextra-theme-docs/src/styles.css, packages/nextra/__test__/__snapshots__/page-map.test.ts.snap
When having the scrollbar always shown, `100vw` behaves weirdly and causes overflow when `layout: "raw"` is set. This can be reproduced on [turborepo.org](https://turborepo.org/):
Here we just remove the `max-w-[90rem]` constraint when using the raw layout.
=> Fix body overflow under `layout: raw`

.changeset/selfish-radios-work.md, packages/nextra/src/loader.ts
fixes https://github.com/shuding/nextra/issues/657
=> fix `Unhandled Runtime Error: No content found for <route>`

.changeset/long-pants-obey.md, examples/swr-site/pages/docs/meta.en-US.json, examples/swr-site/pages/docs/raw-layout.en-US.mdx, packages/nextra-theme-docs/src/components/collapse.tsx, packages/nextra-theme-docs/src/index.tsx, packages/nextra-theme-docs/src/mdx-theme.tsx, packages/nextra-theme-docs/src/styles.css, packages/nextra/__test__/__snapshots__/page-map.test.ts.snap
fixes https://github.com/shuding/nextra/issues/620
closes https://github.com/shuding/nextra/pull/628
=> `"layout": "raw"` should render `all` unstyled elements, except `<a />`

packages/nextra-theme-docs/src/index.tsx
The current ternary is hard to read
1. If we remove `hideToc` variable, and move his value inside ternary we'll see duplicated  `themeContext.layout === 'raw'` check
2. We can safely remove the first one check
=> simpify `tocEl` ternary

.changeset/friendly-singers-provide.md, packages/nextra-theme-blog/src/meta.tsx
I tried to improve tags' styling; specially in dark-mode where the contrast was very low. Let me know what do you all think :)
https://user-images.githubusercontent.com/24727447/183091115-7a188744-d1b4-42e3-a752-9e3563bbdc89.mp4
https://user-images.githubusercontent.com/24727447/183091149-dea48d27-2289-4cce-bf73-ec687907ce62.mp4
---
Supersedes #504
=> change(blog): improve tags styling

.changeset/breezy-news-talk.md, .changeset/nervous-otters-design.md, .changeset/sharp-carpets-care.md, packages/nextra-theme-docs/package.json, packages/nextra-theme-docs/src/components/flexsearch.jsx, packages/nextra-theme-docs/src/components/flexsearch.tsx, packages/nextra-theme-docs/src/components/highlight-matches.tsx, packages/nextra-theme-docs/src/components/input.tsx, packages/nextra-theme-docs/src/components/match-sorter-search.tsx, packages/nextra-theme-docs/src/components/navbar.tsx, packages/nextra-theme-docs/src/components/search.tsx, packages/nextra-theme-docs/src/components/sidebar.tsx, packages/nextra-theme-docs/src/env.d.ts, packages/nextra-theme-docs/src/styles.css, packages/nextra-theme-docs/src/types.ts, packages/nextra-theme-docs/tailwind.config.js, packages/nextra-theme-docs/tsconfig.json, pnpm-lock.yaml
`<Flexsearch />` component is much more beautiful and contains smarter keyboard handlers that can be extracted to `<Search />` component and reused in both searches (flexsearch and match-sorter)
fixes https://github.com/shuding/nextra/issues/694
Previous 
https://user-images.githubusercontent.com/7361780/184511575-47abb663-c3f7-44a4-a3c7-40d211e9a422.mov
https://user-images.githubusercontent.com/7361780/184511578-763c390b-bad6-4b01-b6b1-e5a7d67e4ae2.mov
https://user-images.githubusercontent.com/7361780/184511517-9c1fc4bb-5448-4897-990d-159ae89d1aed.mov
https://user-images.githubusercontent.com/7361780/184511555-4b9afe20-e7fe-4a42-8033-8757164e6103.mov
https://user-images.githubusercontent.com/7361780/184511557-8b563b99-8088-4558-b784-d2d118867b71.mov
=> reuse Flexsearch result styles on match-sorter search

.changeset/lovely-windows-occur.md, packages/nextra-theme-docs/src/components/flexsearch.tsx, packages/nextra-theme-docs/src/components/navbar.tsx, packages/nextra-theme-docs/src/components/search.tsx, packages/nextra-theme-docs/src/components/select.tsx
https://github.com/shuding/nextra/issues/634
I guess `ESC` text is better than X icon and it will be not confusing to see triple X if there is banner on page
=> add clear button for search input

pages/themes/docs/configuration.mdx
Update `Type` value for `footerEditLink` property (as it not supposed to be a `boolean`).
See: https://github.com/shuding/nextra/blob/237faa9d606cfce005b0fee69338768b54499163/packages/nextra-theme-docs/src/types.ts#L25
=> docs(configuration): fix `footerEditLink` type

packages/nextra-theme-docs/src/components/toc.tsx
Use 'main' as the default branch for GitLab, just like GitHub. It is the default starting ~April to June 2021
https://about.gitlab.com/blog/2021/03/10/new-git-default-branch-name/
=> Use 'main' as GitLab default branch

.changeset/curvy-tomatoes-worry.md, .eslintrc.cjs, examples/blog/theme.config.jsx, examples/docs/src/pages/themes/docs/bleed.mdx, examples/docs/src/theme.config.js, examples/swr-site/theme.config.tsx, package.json, packages/nextra-theme-blog/src/constants.tsx, packages/nextra-theme-blog/src/types.ts, packages/nextra-theme-docs/src/components/banner.tsx, packages/nextra-theme-docs/src/components/footer.tsx, packages/nextra-theme-docs/src/components/locale-switch.tsx, packages/nextra-theme-docs/src/components/nav-links.tsx, packages/nextra-theme-docs/src/components/navbar.tsx, packages/nextra-theme-docs/src/components/not-found.tsx, packages/nextra-theme-docs/src/components/search.tsx, packages/nextra-theme-docs/src/components/server-side-error.tsx, packages/nextra-theme-docs/src/components/sidebar.tsx, packages/nextra-theme-docs/src/components/toc.tsx, packages/nextra-theme-docs/src/constants.tsx, packages/nextra-theme-docs/src/contexts/config.tsx, packages/nextra-theme-docs/src/contexts/menu.ts, packages/nextra-theme-docs/src/index.tsx, packages/nextra-theme-docs/src/types.ts, pnpm-lock.yaml
fixes https://github.com/shuding/nextra/issues/676 https://github.com/shuding/nextra/issues/669
also, add new option `toc.component` to fix https://github.com/shuding/nextra/issues/564
and fixes `project.link` behaviour https://github.com/shuding/nextra/issues/383
https://github.com/shuding/nextra/blob/bbfe8a37ce59fc0bbb00da7c0d8a04220d111c53/packages/nextra-theme-docs/src/types.ts#L15-L82
@shuding it was hard to implement without too monkey-business code for some options like
```ts
search: boolean | FC | ReactNode | {
placeholder?: string | (() => string)
emptyResult?: ReactNode | FC
}
```
So I made the following
```ts
search: { 
component: ReactNode | FC<{ directories: Item[] }> 
emptyResult: ReactNode | FC  // will be ignored if component was specified
placeholder: string | (() => …
```
=> [docs] ❗️BREAKING ❗️ various theme config options was renamed

.changeset/hot-pianos-try.md, packages/nextra-theme-docs/src/components/head.tsx, packages/nextra-theme-docs/src/types.ts
This is previously allowed and it makes sense (if the head is totally static).
=> Allow `head` to be a ReactNode

.changeset/young-cows-serve.md, packages/nextra-theme-docs/src/components/search.tsx
=> fix search input `ESC` icon vertical alignment

.changeset/eleven-drinks-deny.md, examples/blog/pages/posts/table.mdx, packages/nextra-theme-blog/src/mdx-theme.tsx, packages/nextra-theme-docs/src/mdx-components.tsx, packages/nextra/src/components/index.ts, packages/nextra/src/components/td.tsx, packages/nextra/src/components/th.tsx, packages/nextra/src/components/tr.tsx
Should we use styles from `@tailwindcss/typography` or from docs?
=> reuse table styles from docs in blog

.changeset/odd-moose-kick.md, packages/nextra-theme-docs/src/components/callout.tsx, packages/nextra-theme-docs/src/components/nav-links.tsx
=> break words in navlinks, remove unneeded `<div />` wrappers, align text on right side for next link

.github/workflows/ci.yml, .github/workflows/release.yml
The previous setup is actually right. The reason why it’s failed is because that cache can only be shared between default branch and feature branchs. 
So if you have main => feature 1 => feature 2. These two feature branches cant share therir caches.
https://github.com/actions/cache/issues/843#issuecomment-1179771256
=> revert: #583

.changeset/pretty-dolphins-live.md, examples/swr-site/pages/docs/code-block-without-language.en-US.mdx, packages/nextra/package.json, packages/nextra/src/compile.ts, packages/nextra/src/components/copy-to-clipboard.tsx, packages/nextra/src/components/pre.tsx, packages/nextra/src/mdx-plugins/rehype-handler.js, packages/nextra/styles/code-block.css, pnpm-lock.yaml
=> fix missing `Copy Code` button in code-blocks without language

.changeset/few-emus-pull.md, packages/nextra-theme-docs/src/components/tabs.tsx
I want to pass some `data-*` prop to `<Tab />` but, currently he accept only `children`
=> make `<Tab />` accept `ComponentProps<'div'>`

.changeset/quick-rabbits-care.md, packages/nextra-theme-docs/src/index.tsx
to render remote markdown with nextra styles
```ts
const components = useMDXComponents()
return (
<MDXRemote compiledSource={packageData.compiledSource} components={components} />
)
```
=> remove `getComponents` export, export `useMDXComponents` from `@mdx-js/react` instead

.changeset/nice-shrimps-cheat.md, packages/nextra-theme-docs/src/utils/normalize-pages.ts, packages/nextra/__test__/__snapshots__/context.test.ts.snap, packages/nextra/__test__/__snapshots__/page-map.test.ts.snap, packages/nextra/package.json, packages/nextra/src/env.d.ts, packages/nextra/src/plugin.ts, pnpm-lock.yaml
1. bring back `title` package but use it not in `nextra-theme-docs` but in `nextra` directly
So follow sidebar links:
will be replaced with:
2. replace all `-` and `_` characters in pagename to make it looks even better!
=> use `title` package in nextra to determine sidebar title based on pagename

docs/pages/docs/guide/advanced/_meta.json, docs/pages/docs/guide/advanced/table.mdx
@shuding I tried to explain confusing behaviour of rendering tables
https://nextra-v2-ggyzxlq24-shuding1.vercel.app/docs/guide/advanced/table
fixes https://github.com/shuding/nextra/issues/799 and https://github.com/shuding/nextra/issues/741
=> explain why table is rendered differently

.changeset/purple-poems-argue.md, examples/swr-site/theme.config.tsx, packages/nextra/src/loader.ts, pnpm-lock.yaml
This fixes the issue that native addons cannot be loaded on WebContainers currently.
=> Fix Nextra not able to run on WebContainers

.changeset/lucky-chefs-walk.md, packages/nextra-theme-docs/src/index.tsx
I guess while using `next export` glitch is still present
see https://f6c0950f.graphql-yoga.pages.dev/
=> fix rtl/ltr glitch on initial loading

packages/nextra/src/loader.ts, packages/nextra/src/plugin.ts, pnpm-lock.yaml
Fixes #844 
The lockfile can't currently be regenerated since the resulting build breaks due to TypeScript problems. This is a proposed fix.
1. `rm pnpm-lock.yaml`
2. `pnpm install`
Note that regenerating the lockfile appears to reveal peer dependency warnings due to the use of React 18.
=> Allows regeneration of `pnpm-lock.yaml` by fixing build error

.changeset/lovely-boxes-impress.md, packages/nextra-theme-docs/src/components/search.tsx
On chrome in non-mac, metaKey is not mapped into ctrlKey. We must use ctrlKey explicitly to check
=> fix: ctrl+k check with e.ctrlKey

.changeset/fresh-ads-chew.md, packages/nextra/__test__/compile.test.ts, packages/nextra/src/compile.ts, packages/nextra/src/loader.ts
while compiling mdx and rendering via `next-remote-mdx`, every time we pass these values by default, I guess we can simplify to make them by default and only in loader overwrite them
=> change default options for `compileMdx`, set `jsx: false` and `outputFormat: 'function-body'` by default

.changeset/moody-buses-arrive.md, packages/nextra-theme-docs/src/index.tsx
Fixes an issue when a heading contains a leading number. For example:
---
This is technically an invalid HTML id (can't start an ID with a number), and `querySelector` is unable to handle this:
```
3680-40188720ff3a5e8f.js:1 Uncaught DOMException: Failed to execute 'querySelector' on 'Document': '#2-create-a-new-package' is not a valid selector.
at ResizeObserver.<anonymous> (https://turborepo.org/_next/static/chunks/3680-40188720ff3a5e8f.js:1:180836)
```
This PR fixes this by using `getElementById` instead of `querySelector`
This could also be fixed by sanitizing the IDs when they are created, but this could lead to collisions (`#1-header`, `#2-header` could collapse to `#header`)
=> fix(docs): correct query for hash with leading num

.changeset/olive-otters-float.md, examples/docs/src/pages/themes/docs/configuration.mdx, packages/nextra-theme-docs/src/components/navbar.tsx, packages/nextra-theme-docs/src/constants.tsx, packages/nextra-theme-docs/src/types.ts
Support a configuration option to disable the logo being linked to / by default. 
This also supports providing a custom route to link to from the logo if desired.
=> feat(docs): support logoLink config option

.changeset/brown-cats-deliver.md, packages/nextra-theme-blog/src/mdx-theme.tsx, packages/nextra-theme-docs/src/mdx-components.tsx, packages/nextra/styles/subheading-anchor.css
fixes https://github.com/shuding/nextra/issues/747
> Make heading as normal heading and only add a to #, the problem is that we have link in heading and nesting link is invalid and will cause SSR error
https://user-images.githubusercontent.com/7361780/195916148-443d5755-0aab-4d2e-a40c-f4ed70056d68.mov
=> allow headings contain links

.changeset/thirty-suns-help.md, packages/nextra-theme-docs/src/constants.tsx
fixes https://github.com/shuding/nextra/issues/747
> site title is hidden in small viewport
=> do not hide default logo on mobile

.changeset/silver-students-return.md, examples/docs/src/pages/_app.js, examples/docs/src/pages/features/i18n.mdx, examples/docs/src/pages/features/image.mdx, examples/docs/src/pages/get-started.mdx, examples/docs/src/pages/index.mdx, examples/docs/src/pages/themes/docs/callout.mdx, examples/docs/src/pages/themes/docs/configuration.mdx, examples/docs/src/theme.config.js, examples/swr-site/theme.config.tsx, packages/nextra-theme-docs/package.json, packages/nextra-theme-docs/src/components/head.tsx, packages/nextra-theme-docs/src/constants.tsx, packages/nextra-theme-docs/src/types.ts, pnpm-lock.yaml
fixes https://github.com/shuding/nextra/issues/113
- setup `next-seo`
- add new theme option `getNextSeoProps`
- remove `titleSuffix` theme option in favor of `getNextSeoProps.titleTemplate`
- by default pass `description`, `canonical`, `openGraph` values to `<NextSeo />` component  from page `frontMatter`, values can be overridden with return value of `getNextSeoProps`
=> setup `next-seo`

.changeset/nasty-apples-breathe.md, packages/nextra-theme-docs/src/constants.tsx, packages/nextra-theme-docs/src/index.tsx, packages/nextra-theme-docs/src/types.ts
fixes https://github.com/shuding/nextra/issues/826#issue-1368578794
> bodyExtraContent → main.extraContent (in the future we can configure the main content area here)
=> replace `main.extraContent` theme option with `main` option

.changeset/grumpy-coins-swim.md, docs/pages/_meta.json, examples/swr-site/pages/_meta.en-US.json, examples/swr-site/pages/_meta.es-ES.json, examples/swr-site/pages/_meta.ja.json, examples/swr-site/pages/_meta.ko.json, examples/swr-site/pages/_meta.ru.json, examples/swr-site/pages/_meta.zh-CN.json, examples/swr-site/pages/about/_meta.en-US.json, examples/swr-site/pages/docs/_meta.en-US.json, examples/swr-site/pages/docs/advanced/_meta.en-US.json, packages/nextra-theme-docs/__test__/__snapshots__/normalize-page.spec.ts.snap, packages/nextra-theme-docs/src/components/navbar.tsx, packages/nextra-theme-docs/src/index.tsx, packages/nextra-theme-docs/src/utils/normalize-pages.ts, packages/nextra/__test__/__snapshots__/context.test.ts.snap, packages/nextra/__test__/__snapshots__/page-map.test.ts.snap
This PR deprecates the `hidden: true` property in _meta, with a new option `display: 'normal' | 'hidden' | 'children'`, where `display: 'hidden'` is the same as `hidden: true`. And `display: 'children'` will make a `doc` directory hide itself, but put all its children in the current level.
This option allows us to put items inside directories in pages/, without affecting the sidebar structure.
=> Breaking: Deprecate `hidden` add new `display` option

.changeset/tall-shoes-perform.md, packages/nextra-theme-docs/src/components/anchor.tsx, packages/nextra-theme-docs/src/components/navbar.tsx
The goal is to use `aria-current` attribute so show only for the current selected element inside the nav, and avoid using `aria-selected` which is meant for `tablist` wrapper aria roles
Example:
```
<nav>
<div aria-current="true">option1</div>
<div>option2</div>
</nav>
```
=> Add correct aria values inside nav

.changeset/young-jeans-know.md, packages/nextra-theme-docs/__test__/__snapshots__/normalize-page.spec.ts.snap, packages/nextra-theme-docs/src/components/sidebar.tsx, packages/nextra-theme-docs/src/utils/normalize-pages.ts
If there are multiple docs trees, for the mobile menu we should display the full list (contains all docs trees) and for the sidebar we need to show only the current active one. To make the implementation easier, we always include the doc item in the list, but mark it with `isUnderCurrentDocsTree`. And when displaying it in the sidebar or mobile menu, we conditionally filter these out.
Another fix is to not show external items as active.
=> Fix full docs directory list and active link

.changeset/funny-houses-tickle.md, packages/nextra-theme-docs/package.json, packages/nextra-theme-docs/src/utils/get-git-edit-url.ts, packages/nextra-theme-docs/src/utils/get-git-issue-url.ts, pnpm-lock.yaml
A follow-up on my last try: I've used a different git url parser this time, changes the approach of getting the git url and issue path quite a bit, but does the job. Makes getting the complete path of a file easier..
Tested with custom GitHub and GitLab domain (sub-domain).
Happy to hear your feedback
---
I've stumbled across https://github.com/shuding/nextra/issues/330 myself and tried to get Nextra running for my Enterprise GitHub instances that use custom domains.
This change focuses on using making small changes to Nextra instead of parse-git-url .
Any feedback is welcome or otherwise put it to the bin.
=> Allow Custom Git Hostnames

.changeset/tall-candles-brake.md, packages/nextra-theme-docs/src/components/toc.tsx
In old Safari accidentally omitting this bracket will throw: `SyntaxError: The string did not match the expected pattern.`
=> Close selector bracket for compat with old Safari.

.changeset/metal-laws-joke.md, packages/nextra-theme-docs/src/components/navbar.tsx
I was discouraged by the appearance of the discord icon without specifying the discord link in `theme.config` 
Custom elements in NavBar should be added by this new option https://github.com/shuding/nextra/pull/907, current behaviour changed by @tknickman is confused
=> fix project/chat icon could appear without provided link

.changeset/seven-timers-pretend.md, packages/nextra-theme-docs/css/scrollbar.css, packages/nextra-theme-docs/css/styles.css, packages/nextra-theme-docs/src/components/navbar.tsx, packages/nextra-theme-docs/src/components/select.tsx, packages/nextra-theme-docs/src/components/sidebar.tsx, packages/nextra-theme-docs/src/constants.tsx, packages/nextra-theme-docs/src/contexts/config.tsx, packages/nextra-theme-docs/src/utils/normalize-pages.ts, packages/nextra/src/compile.ts, packages/nextra/src/components/button.tsx, packages/nextra/src/components/code.tsx, packages/nextra/src/components/pre.tsx, packages/nextra/src/loader.ts, packages/nextra/src/plugin.ts, packages/nextra/src/types.ts
This PR removes the `unstable_` prefix for flexsearch, staticImage and the copy button because they're pretty stable and safe to ship in 2.0.
Also I adjusted some shadow, border, and scrollbar styles. And fixed a bug about separators in the sidebar.
=> Polish the docs theme; rename options

docs/pages/docs/docs-theme/theme-configuration.mdx
The documentation uses `footer.content` while the actual code is using `footer.text`.
Here is the code reference:
https://github.com/shuding/nextra/blob/e1fc506a0bdf73fe9fcf679e3de39918697aa352/packages/nextra-theme-docs/src/components/footer.tsx#L28
---
I also noticed an extra `$` in the code example and I removed it, here is the code reference:
https://github.com/shuding/nextra/blob/73241b3fee58f0318e9349a5eb7650a7cd55a4e3/docs/pages/docs/docs-theme/theme-configuration.mdx?plain=1#L470
=> [Docs] Fixing key name for footer content

docs/pages/docs/docs-theme.mdx
How to reproduce ?
1. Go to https://nextra.site/docs/docs-theme
2. Click on Built-In Components
3. This going to redirect you to https://nextra.site/docs/docs-theme/components
In this pull request I simply fixed the link.
=> Fix built ins components link on docs theme page

.changeset/odd-pants-grow.md, packages/nextra-theme-docs/src/components/navbar.tsx
@shuding on a dark theme we no longer need a border?
as border is missing on latest preview
=> fix missing border in navbar

.changeset/pink-bears-smoke.md, packages/nextra-theme-blog/src/index.tsx, packages/nextra-theme-docs/src/index.tsx, packages/nextra-theme-docs/src/types.ts, packages/nextra/package.json, packages/nextra/src/hooks/index.ts, packages/nextra/src/layout.ts, packages/nextra/src/loader.ts, packages/nextra/src/types.ts, packages/nextra/src/use-internals.ts, packages/nextra/tsup.config.ts
After #1144, I realized that we can simplify the theme layout component even further and get rid of the `usePageContext()` call (so it can be a 100% internal implementation detail).
With this change, the theme layout is just a component that receives the following props:
- `children`: The page content
- `pageOpts`: Related meta information for the current page
- `themeConfig`: The global theme configuration
Which is very straightforward and easy to understand. This will make custom theme easier to create too.
Another reason for this change is, in https://github.com/shuding/nextra/pull/1168/files#diff-8310a54b1ec9da38ed7c74e8c1328e33f07848d25bd9779811614642e3268747R247-R249 we are manipulating the page's props (received from SSG/SSR) and the `pageOpts` object. It would be great to move all …
=> Simplify the theme layout interface

.changeset/spotty-planes-kick.md, packages/nextra-theme-blog/src/meta.tsx
This PR fixes the missing `•` separator in meta heading when `readingTime` is enabled and tags are empty.
- Before
- After
---
Also wrapped the separator in `<span className="nx-px-1">` to prevent uneven spacing when using monospace font like Fira Code.
- Before
- After
=> fix(theme-blog): `•` separator is missing if tags are empty

examples/blog/theme.config.jsx, packages/nextra-theme-blog/src/mdx-theme.tsx, packages/nextra-theme-blog/src/types.ts
This adds functionality to allow for overriding the default MDX component configuration which makes the theme design more flexible.
As you can see, in `examples/blog/theme.config.jsx`, the `h1` element is overridden using a custom implementation.
=> feat: add custom component configuration

.changeset/late-bears-explode.md, examples/swr-site/pages/test.en-US.md, packages/nextra/__test__/__snapshots__/context.test.ts.snap, packages/nextra/__test__/__snapshots__/page-map.test.ts.snap, packages/nextra/src/compile.ts, packages/nextra/src/loader.ts
Sometimes people want to only use standard Markdown files to build a simple page, if they don't need JSX at all. One difference between MD and MDX is that `` will be invalid in MDX.
Hence we are now accepting the `format` option for `mdxOptions`. It can be defined via both `next.config.js` globally or front matter on a per file basis.
=> Allow to use MD (instead of MDX) syntax

.changeset/khaki-numbers-join.md, packages/nextra/src/plugin.ts
E.g. when there's an error accessing the file system, or parsing the front matter, by default it will be swallowed and Webpack will be just stuck silently.
=> fix: Errors during `collectFiles` should be thrown

.changeset/lucky-dogs-act.md, examples/swr-site/theme.config.tsx, packages/nextra-theme-docs/src/components/sidebar.tsx
Currently we determine the level based on the route, however that's not reliable at all as you can put the docs inside a subpath, hide some folders (via `display: 'children'` in meta), etc. This PR changes it to use the actual displayed folder depth via a context.
=> Fix defaultMenuCollapseLevel

.changeset/sharp-flowers-roll.md, packages/nextra/src/loader.ts, packages/nextra/src/types.ts, packages/nextra/src/use-internals.ts
This is an option that mostly helps custom themes. For example if the site has 1000 pages, every page will bundle the meta information (such as front matter) for all other pages and that's 1000x1000 copies. If the theme doesn't show a global sidebar for everything (unlike our `nextra-theme-docs`), that's totally unnecessary.
=> Add transformPageOpts option for advanced use cases

.changeset/three-boats-learn.md, packages/nextra/package.json, packages/nextra/src/index.js, packages/nextra/src/loader.ts
I'm not 100% sure why there's this error, but it seems that some times the webpack resolver doesn't handle `./*` correctly:
=> Fix build error of resolving subpath imports

.changeset/modern-rings-melt.md, packages/nextra/__test__/__snapshots__/compile.test.ts.snap, packages/nextra/src/compile.ts, packages/nextra/src/index.js, packages/nextra/src/loader.ts, packages/nextra/src/mdx-plugins/index.ts, packages/nextra/src/mdx-plugins/remark-replace-imports.ts, packages/nextra/src/types.ts, packages/nextra/tsup.config.ts
fixes https://github.com/shuding/nextra/issues/1303
=> fix `Module not found: Can't resolve 'nextra-theme-docs/style.css'` for imported markdown files that located outside of CWD

.changeset/heavy-news-tan.md, packages/nextra/__test__/compile.test.ts, packages/nextra/src/compile.ts
When calling `compileMdx` directly that option should be enabled unless you explicitly disable it.
=> Fix `codeHighlight` being false by default for remote content

.changeset/many-plants-add.md, docs/components/card/index.tsx, docs/components/features/index.tsx, docs/pages/docs/docs-theme/theme-configuration.mdx, docs/pages/docs/guide/syntax-highlighting.mdx, docs/theme.config.tsx, packages/nextra-theme-docs/src/constants.tsx
fixes https://github.com/shuding/nextra/pull/1406
=> prefer `asPath` over `route` in `useNextSeoProps` docs, allow `void` as return type of `useNextSeoProps`

packages/nextra-theme-docs/src/components/footer.tsx
The menu in `Footer` isn't hidden, if `darkMode` is disabled and `i18n` isn't set or is empty.
Hide the menu if the above statement is true.
=> Hide footer menu if there's nothing to display

.changeset/wet-doors-flow.md, packages/nextra-theme-docs/src/contexts/active-anchor.tsx, packages/nextra-theme-docs/src/mdx-components.tsx
In this way,  React Hook "useSetActiveAnchor" would not be called conditionally.
fixes https://github.com/shuding/nextra/issues/1207
=> fix: move intersection observe and slugs into ActiveAnchorProvider

.changeset/pretty-rings-smile.md, packages/nextra/src/locales.ts
Currently `nextra` tries "handle" the pathname conversion for mp4 files.
=> fix: add mp4 to shoudlHandleLocale exception

.changeset/dirty-donuts-look.md, packages/nextra-theme-blog/src/mdx-theme.tsx, packages/nextra-theme-docs/src/mdx-components.tsx
Currently, only `https://` links open in a new tab. With this change,`http://` links also open in a new tab.
Plus, a tiny Prettier reformatting.
fixes https://github.com/shuding/nextra/issues/1375
=> Make http links external (not just https ones)

nervous-tigers-camp.md, packages/nextra/src/loader.ts
Fix the following error by adding `slash(...)`:
```
Error:
x Bad character escape sequence, expected 2 hex characters
,-[C:\Users\x...\Projects\kyaru-blog\pages\blog\index.mdx:1:1]
1 | import { setupNextraPage } from 'nextra/setup-page'
2 | import __nextra_layout from 'C:\Users\x...\Projects\kyaru-blog\theme.tsx'
:                                      ^^
3 |
4 |
`----
Caused by:
Syntax Error
```
=> fix local theme on Windows

docs/pages/docs/guide/syntax-highlighting.mdx
Added a section on how to render and use the `filename` attribute (thus showing the title bar for a code section).
The attribute is frequently used throughout the Nextra documentation - but information on how to use it was missing.
=> Filenames and titles to syntax-highlighting

.changeset/cuddly-timers-attack.md, packages/nextra-theme-docs/src/components/search.tsx
Per https://github.com/shuding/nextra/issues/1606#issuecomment-1457862874, the PR makes the search input always show `Cmd + K`/`Ctrl + K` when loses focus.
Fixes #1606.
=> fix(search): always show Cmd+K when input loses focus

.changeset/curly-bats-whisper.md, packages/nextra-theme-docs/src/constants.tsx
The "Search documentation..." text was originally translated in French to "Rechercher de la documentation...".  This is wrong (and is overly long).  
In this setting, it should be "Rechercher documents..." or simply "Rechercher...". 
Reference:  https://translate.google.com/?sl=fr&tl=en&text=rechercher%20documents&op=translate&hl=en
Thanks
=> Fix search text in French

.changeset/fast-pugs-beg.md, package.json, packages/nextra-theme-blog/tsup.config.ts, packages/nextra-theme-docs/tsup.config.ts, packages/nextra/__test__/compile.test.ts, packages/nextra/src/compile.ts, packages/nextra/src/constants.ts, packages/nextra/tsup.config.ts, pnpm-lock.yaml
This is a following up to my previous PR https://github.com/shuding/nextra/pull/1534. 
After this PR, nextra will remove the `.md` extension in the link, but keep the anchor and query, if exist. 
```
// Input markdown
[link](../my_markdown_file.md#heading)
```
```
// Output HTML
<a href="../my_markdown_file#heading">
```
Other updates in this PR:
- Replace `as any` to typescript 4.9's `satisfies` keyword.
- Update `tsup` by removing it from `pnpm.overrides`, so that it can support `satisfies`.
=> Support Markdown links with query or anchor

.changeset/modern-games-bow.md, packages/nextra-theme-docs/src/components/sidebar.tsx
Some hue give not really accessibles sidebar actives items. 
| Actual  | Fixed |
| ------------- | ------------- |
| <img width="489" alt="image" src="https://user-images.githubusercontent.com/48803115/224540227-7a753a97-a7dc-46a1-bca6-5dcd03c5be57.png">  | <img width="479" alt="image" src="https://user-images.githubusercontent.com/48803115/224540238-3f6101e8-6e98-4526-a307-e29eb14f9a1b.png">  |
| <img width="466" alt="image" src="https://user-images.githubusercontent.com/48803115/224540266-157a999a-40c9-4c06-8db9-0e43a7b39894.png">  | <img width="481" alt="image" src="https://user-images.githubusercontent.com/48803115/224540280-c3f067b5-aa4f-408d-a39a-128163a153a9.png">  |
| <img width="484" alt="image" src="https://user-images.githubusercontent.com/48803115/224540303-d3582c42-e499-4e6a-a …
=> Fix: Improve sidebar colors accessibility

.changeset/curly-rings-sip.md, packages/nextra/src/loader.ts
This PR prints the warning inline instead of the current behavior which includes a stack trace.
```
$ next build
info  - Linting and checking validity of types
[nextra] Init git repository failed Error: Discover git repo from [/Users/styfle/Code/foo] failed: could not find repository from '/Users/styfle/Code/foo'; class=Repository (6); code=NotFound (-3)
at file:///Users/styfle/Code/foo/node_modules/nextra/dist/loader.mjs:29:37 {
code: 'GenericFailure'
}
```
```
$ next build
info  - Linting and checking validity of types
[nextra] Init git repository failed Discover git repo from [/Users/styfle/Code/foo] failed: could not find repository from '/Users/styfle/Code/foo'; class=Repository (6); code=NotFound (-3)
```
=> fix: improve warning when missing `.git` directory

.changeset/lazy-cooks-wash.md, packages/nextra-theme-docs/src/components/search.tsx
Fixes: #1703 
I tested this localy on my site by patching node_modules directly and it works at least with `codemirror`.
=> fix: Do not focus search when currently focusing a HTMLElement with contenteditable active

.changeset/fix-toc-word-wrap.md, .changeset/twenty-chefs-switch.md, packages/nextra-theme-docs/src/components/toc.tsx
Fixed wrapping issue in TOC section for long single-word headers (e.g. env variables)
https://user-images.githubusercontent.com/827338/230904093-f9de9564-9b73-4c63-9224-46ceb2c3ee07.mp4
https://user-images.githubusercontent.com/827338/230904132-55bcacfa-c3e8-4795-9e14-cfedc4b636d2.mp4
=> fix: break words in TOC titles for proper wrapping

.changeset/lucky-eels-glow.md, packages/nextra-theme-docs/src/components/file-tree.tsx, packages/nextra-theme-docs/src/components/sidebar.tsx
fix uncrawable links in sidebar, use button when link don't have href because it impacts on SEO
remove useless prop `children` frm <FileTree.File /> component
fixes https://github.com/shuding/nextra/issues/1635
=> fix uncrawable links in sidebar, use button when link don't have href because it impacts on SEO

.changeset/blue-games-pretend.md, packages/nextra-theme-docs/src/components/theme-switch.tsx
Here I'm using the themeSwitch `useOptions` custom hook to change the default language to portuguese (pt-BR) on my docs site but the selected option text does not replicate the options I'm returning.
```jsx
// ./theme.config.js
export default {
themeSwitch: {
useOptions() {
return {
light: 'Claro',
dark: 'Escuro',
system: 'Sistema',
}
}
}
}
```
To fix the issue I'm using the `useOptions().config` object and grabbing the text using the `theme` string from next-themes `useTheme()` hook
=> Use config.useOptions text as the Select `selected` name on Theme Switch

.changeset/blue-apricots-hammer.md, packages/nextra/src/loader.ts
fixes https://github.com/shuding/nextra/issues/1762
=> fix `Error: ENOENT: no such file or directory` in Nx-managed monorepos

.changeset/happy-pianos-fail.md, packages/nextra-theme-blog/src/basic-layout.tsx, packages/nextra-theme-blog/src/styles.css
I started using the blog theme and noticed that some styles were missing on smaller screens. Things like `blockquote`, headings and `a` elements weren't properly styled. After digging into it a bit I found that the `prose` class wasn't applied to all breakpoints, just `sm`. Adding the `nx-prose` class to the basic layout fixed things.
I walked through the blog example after the change and confirmed that the styles were applied and nothing else was affected. If necessary I can add some before and after screenshots.
=> fix(blog): Use tailwind prose for small screens

docs/pages/docs/docs-theme/theme-configuration.mdx
This PR changes the URL in a code snippet.
```diff
- https://github.com/shuding/nextra/blob/core/docs/pages
+ https://github.com/shuding/nextra/blob/main/docs/pages
```
=> fix: change sample URL path

packages/nextra/tsup.config.ts
On windows, `fast-glob` return path use '/' as separator, but esbuild use '\\', causing the esbuild plugin `add-mjs` can't identify client import, so the `nextra` package build output client script as `.mjs`:
=> fix: can't build package on windows

docs/pages/index.mdx
On Firefox, the spacing between two lines of headline is too large.
This PR fix it.
Env:
1. MacOS 13 + Firefox 111.0.1 => 113.0.1
2. Windows 11 + Firefox developer 114.0b7
=> fix: headline in firefox

docs/pages/docs/docs-theme/built-ins/tabs.mdx
I discovered a simple typing error in the library where "pnpm" was written as "pNPM" with the "npm" in uppercase.
I have corrected these issues in lines 10, 25, and 48.
=> fix: typo in word pnpm

.changeset/neat-kings-approve.md, packages/nextra/styles/code-block.css
Selecting and copying code/lines from code blocks with line numbers is currently broken.
Try it with the docs site here: https://nextra.site/docs/guide/syntax-highlighting
Result:
```
function
Counter
() {
const
[
count
,
setCount
] 
=
useState
(
0
)
return
<
button
onClick
=
{() 
=>
setCount
(count 
+
1
)}>{count}</
button
>
}
```
By removing `display: inline-flex`, I see no visual differences except that copying code works again:
Result:
```
function Counter() {
const [count, setCount] = useState(0)
return <button onClick={() => setCount(count + 1)}>{count}</button>
}
```
=> fix select+copy for code blocks with line numbers

.changeset/real-games-scream.md, packages/nextra/src/loader.ts
Fix to replace the last 'export default MDXContent;' instead of the first one.
If .mdx file contains a string that exactly matches 'export default MDXContent;', the certain export is not removed and it will result in an error.
=> fix: replace last 'export default MDXContent;'

docs/pages/docs/guide/organize-files.mdx
This page isn't exist.
Check this page https://nextra.site/docs/guide/organize-files
So I update href
=> fix: update href to docs page

docs/pages/docs/guide/advanced/latex.mdx
The link from the Latex page to the Markdown page references the same parent folder, but the markdown page is one folder above. This is fixed by adding the "../" to the front of the link path.
=> Fixed link from Latex page to Markdown page

.changeset/curvy-pigs-ring.md, packages/nextra/__test__/__snapshots__/compile.test.ts.snap, packages/nextra/__test__/compile.test.ts, packages/nextra/package.json, packages/nextra/src/mdx-plugins/rehype.ts, packages/nextra/src/mdx-plugins/remark-custom-heading-id.ts, packages/nextra/src/mdx-plugins/remark-headings.ts, pnpm-lock.yaml
As noticed by @uonr on his issue at [vercel/swr-site#530](https://github.com/vercel/swr-site/pull/530), same headings generate the same anchor ids. This PR adds checking of existent headings before pushing, and, if necessary, adds a prefix based on the closest lower depth heading.
Here's a comparision from the SWR's Mutation and Revalidation heading tree:
```
--- BEFORE ---
mutate #mutate
Global Mutate #global-mutate
Bound Mutate #bound-mutate
Revalidation #revalidation
API #api
Parameters #parameters
Return Values #return-values
useSWRMutation #useswrmutation
API #api <-- DUPLICATED ID
Parameters #parameters <-- DUPLICATED ID
Return Values #return-values <-- DUPLICATED ID
Basic Usage #basic-usage
Defer loading data until needed #defer-loading-data-until-needed
--- AFTER ---
mutate …
```
=> use github-slugger for custom heading ids to prevent duplicated headings

docs/pages/docs/docs-theme/theme-configuration.mdx
The documentation and my practice indicate that the `docsRepositoryBase` path in the example should omit the `pages`.
=> fix: docsRepositoryBase url in example

.changeset/poor-carrots-raise.md, docs/pages/docs/docs-theme.mdx, docs/pages/docs/docs-theme/built-ins.mdx, docs/pages/docs/docs-theme/start.mdx, docs/pages/docs/guide.mdx, docs/pages/docs/guide/advanced.mdx, docs/pages/docs/guide/built-ins.mdx, docs/pages/docs/guide/built-ins/cards.mdx, docs/pages/docs/guide/markdown.mdx, docs/pages/docs/guide/organize-files.mdx, package.json, packages/nextra-theme-docs/src/components/anchor.tsx, packages/nextra-theme-docs/src/constants.tsx, packages/nextra-theme-docs/src/index.tsx, pnpm-lock.yaml
- remove `Steps`, `Callout`, `Tabs`, `Tab`, `Cards`, `Card`, `FileTree` exports, export them now from `nextra/components`
- remove `useMDXComponents` export, export it now from `nextra/mdx`
- set by default `sidebar.toggleButton` to true
=> some major updates

docs/pages/docs/docs-theme/_meta.json, docs/pages/docs/docs-theme/api/_meta.json, docs/pages/docs/docs-theme/api/use-config.mdx
This PR closes #2241.
This PR adds `/docs/docs-theme/api/use-config`, which was missing in link references and states important information about the returned values of the `useConfig` hook.
fixes https://github.com/shuding/nextra/issues/1139
=> create new docs page about `useConfig`

.changeset/short-games-carry.md, docs/pages/docs/docs-theme/theme-configuration.mdx, docs/pages/docs/guide/i18n.mdx, docs/theme.config.tsx, examples/docs/src/theme.config.js, examples/swr-site/theme.config.tsx, packages/nextra-theme-docs/src/components/banner.tsx, packages/nextra-theme-docs/src/components/footer.tsx, packages/nextra-theme-docs/src/components/locale-switch.tsx, packages/nextra-theme-docs/src/components/toc.tsx, packages/nextra-theme-docs/src/constants.tsx
- rename theme config options
`i18n.text` → `i18n.name`
`banner.text` → `banner.content`
`editLink.text` → `editLink.content`
`footer.text` → `footer.content`
=> [v3/docs] rename theme config options

.changeset/chilled-kids-fetch.md, .changeset/fuzzy-meals-care.md, .changeset/wet-years-serve.md, docs/package.json, docs/pages/docs/custom-theme.mdx, docs/pages/docs/docs-theme/theme-configuration.mdx, examples/swr-site/package.json, examples/swr-site/theme.config.tsx, packages/nextra-theme-blog/__test__/__fixture__/pageMap.ts, packages/nextra-theme-docs/src/components/sidebar.tsx, packages/nextra-theme-docs/src/components/toc.tsx, packages/nextra-theme-docs/src/index.tsx, packages/nextra-theme-docs/src/schemas.ts, packages/nextra/__test__/__snapshots__/compile.test.ts.snap, packages/nextra/__test__/__snapshots__/page-map.test.ts.snap, packages/nextra/__test__/compile.test.ts, packages/nextra/__test__/page-map.test.ts, packages/nextra/src/client/setup-page.tsx, packages/nextra/src/server/compile.ts, packages/nextra/src/server/constants.ts, packages/nextra/src/server/loader.ts, packages/nextra/src/server/mdx-plugins/remark-headings.ts, packages/nextra/src/server/page-map.ts, packages/nextra/src/server/remote.ts, packages/nextra/src/types.ts
- remove `toc.headingComponent`
- should not add virtual `_meta` file if missing
- rename `pageOpts.headings` to `toc`
=> [V3] remove `toc.headingComponent`, rename `pageOpts.headings` to `toc`

.changeset/bright-pots-taste.md, packages/nextra-theme-docs/src/components/sidebar.tsx
Allow sidebar toggle button to be visible if `darkMode` is `false`
Add `margin-left: auto` if darkMode select is not visible in order to stick toggle to the right side
Fixes https://github.com/shuding/nextra/issues/2310
=> Fix showing sidebar when darkmode is turned off

docs/pages/docs/docs-theme/theme-configuration.mdx
Copy and pasting from the docs caused this example to error due to missing `useRouter` import. People new to Next might not know where to import `useRouter` from, so I've added it to the example.
=> Import useRouter in theme configuration example

packages/nextra/src/server/loader.ts
fix: https://github.com/shuding/nextra/issues/2424
This PR resolves a path separator inconsistency issue on different operating systems when creating the `route` constant. On Windows, `path.relative()` produces backslashes (`\`), while on Unix-based systems it produces forward slashes (`/`). This inconsistency can lead to unexpected behavior.
The solution is to use the `slash()` method to ensure all path separators are standardized to forward slashes (`/`). This change ensures consistent path formatting across all operating systems.
Changes proposed:
1. Use the `slash()` method when defining the `route` constant to convert any backslashes to forward slashes.
=> Uniform Path Separators using slash() Method

.changeset/mighty-days-clean.md, packages/nextra/src/client/components/cards.tsx
fixes: #1961
the `children` prop is only required when `image` is true
=> types: fix card typings

.github/workflows/nextjs-bundle-analysis.yml
The bundle analysis comment was failing on PR from fork. Changed the event to `pull_request_target`, this event will allow commenting on pr as it uses workflow file from the base branch so all the actions are safe to run
=> chore: use `pull_request_target` event to fix comment on pr

.github/workflows/nextjs-bundle-analysis.yml
It seems like `pull_request_target` not only uses the workflow from the target branch but the code too. So I changed the event back to pr with the `pull_request: write` permission so actions can add label/write comments on the pr. `content: read` is needed for checkout. I've also tried using replace syntax in the name, this might work, if it doesn't then please use the previous `bundle-${{ matrix.package == 'docs' && 'docs' || 'swr-site' }}` name
fixes: https://github.com/shuding/nextra/pull/2245#issuecomment-1947543568
the ci is failing due to fa83af93bd751fbd21455fcedbc28857cd55ee61 change
=> chore(bundle-analyzer): change event again

docs/pages/api/og.jsx
I noticed that `-webkit-background-clip` was being used in the JSX style prop in the OpenGraph image generation to the nextra site.
`-webkit-background-clip` is an invalid JSX style prop, and `WebkitBackgroundClip` should be used instead.
Although the webkit clip would not matter most of the time as `BackgroundClip` is present, I believe it is still best to use `WebkitBackgroundClip`.
Here is an example where I copied the image JSX and removed the `backgroundClip` style prop to compare the difference when `-webkit-background-clip` or `WebkitBackgroundClip` is used.
=> fix: Invalid webkit style

.changeset/brave-baboons-provide.md, packages/nextra-theme-docs/src/components/highlight-matches.tsx
This PR provides an additional fix for the memory leak issue in the `highlight-matches.tsx` component that was previously addressed in [#2152](https://github.com/shuding/nextra/pull/2152). While the initial fix resolved certain scenarios, it appears that a memory leak can still occur under specific conditions as I have recently discovered.
The memory leak issue was initially reported in issue [#2150](https://github.com/shuding/nextra/issues/2150) and a subsequent fix was proposed in PR [#2152](https://github.com/shuding/nextra/pull/2152). while this fix aimed to address this, but it seems the problem persists in certain edge cases.
Building on the efforts of PR [#2152](https://github.com/shuding/nextra/pull/2152), I have conducted further investigation and identified that the memory leak …
=> Comprehensive fix for memory leak in highlight-matches component

.changeset/tall-cobras-juggle.md, docs/pages/api/og.jsx, examples/swr-site/pages/en/_meta.ts, packages/nextra-theme-blog/CHANGELOG.md, packages/nextra-theme-docs/CHANGELOG.md, packages/nextra-theme-docs/src/components/highlight-matches.tsx, packages/nextra-theme-docs/src/components/navbar.tsx, packages/nextra/CHANGELOG.md, packages/nextra/__test__/__snapshots__/page-map.test.ts.snap
* fix: Invalid webkit style
"-webkit-background-clip" is an invalid style for JSX, this commit switches this to the "WebkitBackgroundClip" style.
* refactor: Remove webkit styling
=> [v3] allow `items: Map` for `type: 'menu'` since object can't guaranty the insertion order

.changeset/blue-suits-scream.md, packages/nextra-theme-docs/css/styles.css
=> [v3] enable `outline: 'none'` only for `:focus-visible` state, to fix double ring in Firefox

.changeset/rotten-spies-exist.md, packages/nextra/src/server/loader.ts, packages/nextra/src/server/webpack-plugins/nextra-search.ts
fixes https://github.com/shuding/nextra/issues/2763
=> [v3] fix `TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))` on dev environment when `frontMatter.searchable: false`

.changeset/loud-ties-swim.md, packages/nextra-theme-docs/src/index.tsx
fixes #2781 
Exports the use menu context so you can create a custom navbar component to open/close the sidebar in mobile.
=> export use menu

.changeset/warm-cameras-vanish.md, packages/nextra/styles/code-block.css
Fix the line highlighting background-color does not extend to the full width of the code block when a scrollbar appears with line numbers.
https://github.com/shuding/nextra/assets/26923823/c5a7d769-46fa-46b3-9b33-4a50e07cace3
adding `_inline-block` class and removing `_float-left` class
https://github.com/shuding/nextra/assets/26923823/7c175be9-2930-4b8e-916f-3bb635813def
=> [v3] Fix the line-numbers style in syntax highlighting

.changeset/small-ads-glow.md, .changeset/warm-mice-flash.md, packages/nextra-theme-docs/src/mdx-components.tsx, packages/nextra/src/client/components/file-tree.tsx
fixes https://github.com/the-guild-org/website/actions/runs/10024457855/job/27706559011?pr=1695
=> [v3] fix `RangeError: Maximum call stack size exceeded` in `findSummary` when `child.props.children` is `undefined`

docs/pages/docs/guide/advanced/table.mdx
Hello! I addressed typos, such as incorrect usage of "it's" and missing articles, throughout the "Rendering Tables" article located at `docs/pages/docs/guide/advanced/table.mdx`. 
I'm a new contributor, interested in the project and its documentation, and I hope that this is helpful.
=> docs: Addressed typos in `docs/pages/docs/guide/advanced/table.mdx`

docs/pages/docs/docs-theme/built-ins/bleed.mdx, docs/pages/docs/guide/built-ins/filetree.mdx, examples/docs/src/pages/themes/docs/bleed.mdx
https://github.com/shuding/nextra/issues/3124
* Previous demo image was external from Unsplash. It was removed from origin server and started returning `404`
* Replaced with internal image that doesn't depend on 3rd party.
=> [ISSUE-3124] fix: Bleed demo image

.changeset/poor-rings-shop.md, packages/nextra-theme-blog/src/index.tsx, packages/nextra/src/types.ts
I encountered a similar issue to #2971 when I attempted to implement a custom Nextra theme. My idea is to add a generic parameter in `NextraThemeLayoutProps` for `themeConfig`, which would provide better type support for the root layout. If this approach is not suitable, feel free to close it.
`type.ts`
```tsx
import type { NextraThemeLayoutProps } from 'nextra'
export type MyNextraThemeFrontmatter = {
// ...
}
export type MyNextraThemeConfig = {
titleSuffix?: string
// ...
}
export type MyNextraThemeLayoutProps = NextraThemeLayoutProps<
MyNextraThemeFrontmatter,
MyNextraThemeConfig
>
```
`theme.tsx`
```tsx
import Head from 'next/head'
import { DEFAULT_THEME_CONFIG } from './constants'
import type { MyNextraThemeLayoutProps } from './types'
export default function Layout({ children, …
```
=> [v3] add a generic for `themeConfig` to improve type inference

.changeset/long-islands-report.md, packages/nextra/src/server/index.ts
This change allows TypeScript to infer the `ZodError` type, so we don't need to import it for explicit assertion. Feel free to close this if the approach is not suitable.
=> [v3] remove explicit `ZodError` type assertion

.changeset/khaki-adults-mix.md, examples/swr-site/package.json, packages/nextra-theme-docs/package.json, packages/nextra-theme-docs/src/index.tsx, pnpm-lock.yaml
Following the [focus-visible](https://github.com/WICG/focus-visible) guidelines, I reviewed the codebase and couldn't find any related selectors such as `.js-focus-visible`, `.focus-visible`, or `[data-focus-visible-added]`. Since `:focus-visible` is now supported in all major browsers, the polyfill may no longer be necessary.
If anything is missed or if there are still cases where the polyfill is needed, please feel free to close this PR.
<details>
<summary>Chrome 127</summary>
https://github.com/user-attachments/assets/6aec13bf-d557-4312-bc0f-7dbf10a6627f
</details>
<details>
<summary>Firefox 117</summary>
https://github.com/user-attachments/assets/b54ff8eb-0d0f-43f0-9749-481a66899fe0
</details>
<details>
<summary>Safari 17.5</summary> …
=> [v3] remove focus-visible polyfill

.changeset/gorgeous-crabs-laugh.md, packages/nextra-theme-docs/src/components/search.tsx
Resolves #2833 
This pull request aims to provide better support for CJK language users while ensuring that the existing search behavior for non-Pinyin characters remains unaffected.
I referred to the [foxact](https://foxact.skk.moe/use-composition-input) implementation and changed the search input to be uncontrolled to ensure that the state in `<Flexsearch>` only updates the composition process is complete, allowing the input state in the browser to be reflected to the user.
To better understand the changes in this PR, here's an overview of the sequence of events when composing the character "你" using Pinyin:
Chrome
```
compositionstart
input (value: n, isComposing: true)
input (value: i, isComposing: true)
input (value: 1, isComposing: true)
input (value:你, isComposing: true) …
```
=> [v3] enhance search input to better support CJK language users

.changeset/short-icons-impress.md, examples/swr-site/pages/en/index.mdx, packages/nextra-theme-docs/src/components/collapse.tsx, packages/nextra-theme-docs/src/components/sidebar.tsx, packages/nextra-theme-docs/src/components/toc.tsx, packages/nextra-theme-docs/src/mdx-components.tsx, packages/nextra/src/client/components/tabs.tsx
fixes https://github.com/shuding/nextra/issues/1432
different approach to fix https://github.com/shuding/nextra/pull/3149 cc @87xie
https://github.com/user-attachments/assets/598ce6d8-0263-41a9-8bde-4c2531cd1edc
https://github.com/user-attachments/assets/eec147b4-fd12-4579-bf32-06c9bf996be8
=> [v3] avoid focus-visible style being cut off by overflow-hidden

.changeset/fair-hounds-watch.md, examples/swr-site/theme.config.tsx, packages/nextra-theme-docs/src/components/search.tsx, packages/nextra-theme-docs/src/components/sidebar.tsx
another approach to fix https://github.com/shuding/nextra/pull/3150 because I think adding `sidebarEl.addEventListener` / `sidebarEl.removeEventListener` makes things complex – we can ignore the case when the folder will not be closed when switching to the locale switch for example
cc @87xie wdyt
https://github.com/user-attachments/assets/71730838-90d8-4de7-aeff-78f654aa4b04
=> [v3] Avoid the sidebar collapse having unintended animations when `sidebar.autoCollapse` is set to `true`

.changeset/clever-dots-unite.md, examples/swr-site/components/video.tsx, examples/swr-site/package.json, packages/nextra-theme-docs/package.json, packages/nextra-theme-docs/src/contexts/active-anchor.tsx, pnpm-lock.yaml
Nextra v3 requires Next.js >= 13. Based on the [Supported Browsers](https://github.com/vercel/next.js/pull/41529/files#diff-7e079a6684a14ec2884b491ffdb0ae0f1a61e68e8127b4e00e71acf214f4a98d) for Next.js 13, it seems that most users don't need `intersection-observer` polyfill.
Is it a good opportunity to remove this dependency in v3? If users require support for older browsers, we can suggest they import it in `_app.tsx`.
=> [v3] remove intersection-observer polyfill

.changeset/forty-bats-design.md, docs/pages/docs/guide/advanced/playground.mdx, docs/pages/docs/guide/syntax-highlighting.mdx, packages/nextra-theme-docs/css/styles.css, packages/nextra-theme-docs/src/components/collapse.tsx, packages/nextra-theme-docs/src/components/navbar.tsx, packages/nextra-theme-docs/src/components/search.tsx, packages/nextra-theme-docs/src/components/select.tsx, packages/nextra-theme-docs/src/components/sidebar.tsx, packages/nextra-theme-docs/src/mdx-components.tsx
- fix overflow when clicking on `<details>` with open state
https://github.com/user-attachments/assets/2c8b3ab8-3ff5-49ec-82da-1d45b6818a77
- fix animation on mobile when clicking on `<details>` with open state
https://github.com/user-attachments/assets/a4d5cc1c-4aae-4c14-bd37-e0e622d8cd5d
https://github.com/user-attachments/assets/41a96dbf-631f-469a-b5c0-7236619587d9
=> fix `<details />` on mobile

.changeset/red-squids-enjoy.md, packages/nextra-theme-docs/src/components/head.tsx, packages/nextra-theme-docs/src/constants.tsx, packages/nextra-theme-docs/src/contexts/active-anchor.tsx, packages/nextra-theme-docs/src/mdx-components.tsx
This change aims to resolve the issue shown below the image:
1. When I click the `href=“#two”` link in the table of contents (TOC),
1. The URL updates, and the page scrolls to the corresponding anchor,
1. However, the active style in the TOC stays on the link before `href=“#two”`.
I think the intersection area should be restricted to below the navbar height, aligning it more closely with the user's visible area.
The current implementation in this PR uses `document.querySelector('.nextra-content')`, which may not be the best approach. If we could move the `<ActiveAnchorProvider>` into the `<NextraWrapper>` in the MDX components and obtain the corresponding DOM reference for `.nextra-content` through a ref, it might provide better consistency and more closely align with its actual scope of …
=> [v3] consider navbar height for the anchor intersection observer

.changeset/few-snails-occur.md, packages/nextra-theme-docs/src/components/back-to-top.tsx
A small fix to correctly use the `aria-hidden` attribute, as referenced by [this guideline](https://dequeuniversity.com/rules/axe/4.9/aria-hidden-focus): elements with `aria-hidden: true` must not be focusable.
=> [v3] remove aria-hidden attr when scroll-to-top button is visible

.changeset/tasty-worms-fry.md, packages/nextra-theme-blog/package.json, packages/nextra-theme-docs/package.json, packages/nextra/package.json, pnpm-lock.yaml
In v3, React 18 needs to be considered the minimal requirement because of the following:
- The steps component currently uses `useId`
- Headless UI v2
Also, remove `@popperjs/core` (currently unused)
=> [v3] make react 18 as minimal requirement

.changeset/slimy-vans-rush.md, .changeset/wild-windows-grow.md, docs/next-env.d.ts, docs/pages/docs/docs-theme/theme-configuration.mdx, examples/swr-site/next-env.d.ts, examples/swr-site/theme.config.tsx, packages/nextra-theme-docs/src/components/back-to-top.tsx, packages/nextra-theme-docs/src/components/toc.tsx, packages/nextra-theme-docs/src/constants.tsx, packages/nextra-theme-docs/src/schemas.ts
[#2308](https://github.com/shuding/nextra/issues/2308) seems to be planned for v3, but it hasn't been addressed yet (currently, there is  a PR #2895  for v2), so I would like to try to help.
I referenced the implementation of the `feedback` option and decided not to expose the `backToTop.component` option, as the `className` and `hidden` props might not be necessary for users.
Here's how the implementation allows users to control the text through `backToTop.text`, for example:
```ts
const themeConfig = {
backToTop: {
text: (locale: string) => {
switch (locale) {
case 'ru': return 'Перейти наверх'
case 'es': return 'Desplazarse hacia arriba'
default: return 'Scroll to top'
}
}
}
}
```
Feel free to close this if it is not suitable.
`locale: es`
`locale: en`
=> [v3] update the back-to-top option to support i18n

docs/components/index-page/index.tsx
The link to MDX 3 opens the [blog post for MDX 2](https://mdxjs.com/blog/v2).
Closes #3323
Correctly links `MDX 3` to the [MDX 3 blog post](https://mdxjs.com/blog/v3) instead of the [MDX 2 blog post](https://mdxjs.com/blog/v2).
- For content changes, you will also see an automatically generated comment
with links directly to pages you've modified. The comment won't appear if
your PR only edits files in the `data` directory.
[self-review checklist](https://docs.github.com/en/contributing/collaborating-on-github-docs/self-review-checklist).
=> Fix Docs: Link to MDX 3 Instead of MDX 2

.changeset/plenty-boxes-buy.md, examples/swr-site/pages/es/docs/getting-started.mdx, packages/nextra-theme-blog/postcss.config.js, packages/nextra-theme-docs/postcss.config.js, packages/nextra/src/client/components/steps.tsx, packages/nextra/styles/steps.css
Closes: N/A
To support RTL direction for the `<Steps>` component in v3, I referenced the approach from v4, utilizing logical properties to simplify RTL support. However, the current configuration of `postcss-lightningcss` with [`browsers: '>= .25%'`](https://browsersl.ist/#q=%3E%3D+.25%25) requires maintaining compatibility with deprecated browsers like IE11, which results in some unexpected transformations of logical properties.
To resolve this, I adjusted the browsers configuration to [`>= .25% and not dead`](https://browsersl.ist/#q=%3E%3D+.25%25+and+not+dead). Below is an example of the differences in Tailwind's generated styles
**browsers: '>= .25%'**
```css
._ps-6:not(:is(:lang(ae),:lang(ar),:lang(arc),:lang(bcc),:lang(bqi),:lang(ckb),:lang(dv),:lang(fa),:lang(glk),:lang(he),:lang(ku …
```
=> RTL support for the steps component

docs/pages/docs/guide/built-ins/cards.mdx
Closes: N/A
I noticed the [Card Components](https://nextra.site/docs/guide/built-ins/cards) documentation page is missing a title prefix, so I added `__nextra_dynamic_opts.title: 'Card Components'` to the static props to ensure the page has a proper title.
**Before**
**After**
- For content changes, you will also see an automatically generated comment
with links directly to pages you've modified. The comment won't appear if
your PR only edits files in the `data` directory.
[self-review checklist](https://docs.github.com/en/contributing/collaborating-on-github-docs/self-review-checklist).
=> fix missing title prefix on the cards component page

docs/pages/docs/guide/advanced/customize-the-cascade-layers.mdx, docs/pages/docs/guide/built-ins/steps.mdx
Closes: N/A
In v3, the steps component supports h2, h3, and h4, so I updated part of the documentation.
I also adjusted the heading level for the steps component in `customize-the-cascade-layers.mdx`, as it only supported h3 at the time.
- For content changes, you will also see an automatically generated comment
with links directly to pages you've modified. The comment won't appear if
your PR only edits files in the `data` directory.
[self-review checklist](https://docs.github.com/en/contributing/collaborating-on-github-docs/self-review-checklist).
=> update the documentation for the steps component

.changeset/quiet-carpets-sit.md, packages/nextra-theme-blog/src/mdx-theme.tsx, packages/nextra-theme-docs/src/components/anchor.tsx
Closes: N/A
In theme-docs, when using markdown to create a jump link like `[My content](#my-content)`, clicking the link to jump to specific content causes that content to be covered by the navbar, It can be reproduced by clicking on the `GFM syntax table:` [here](https://nextra.site/docs/guide/advanced/table#unexpected-result), and this behavior is inconsistent with clicking on TOC links and sub-heading anchors.
The jump link created via markdown syntax is converted into a next-link. When clicking it, the `activeElement` remains on the link, which causes the following CSS not to be applied:
```css
html:not(:has(*:focus)) {
@apply _scroll-pt-[--nextra-navbar-height];
}
```
To resolve this, I added a check on the MDX anchor component to see if the href starts with `#`. If true, it uses …
=> ensure jump link behavior is consistent in markdown

docs/pages/docs/guide/advanced/table.mdx
Closes: N/A
Due to the upgrade from v3 to MDX3, the content related to [`remark-mdx-disable-explicit-jsx`](https://github.com/iAdramelk/remark-mdx-disable-explicit-jsx) may no longer be applicable, so I have commented it out. Additionally, I have supplemented the documentation by creating a table component, using a similar approach as seen in [theme-configuration.mdx](https://github.com/shuding/nextra/blob/main/docs/pages/docs/docs-theme/theme-configuration.mdx?plain=1#L31-L46).
Feel free to close this if is unnecessary.
- For content changes, you will also see an automatically generated comment
with links directly to pages you've modified. The comment won't appear if
your PR only edits files in …
=> update the documentation for rendering tables in v3

.changeset/big-adults-remain.md, packages/nextra/src/server/constants.ts, packages/nextra/src/server/index.ts, packages/nextra/src/server/page-map.ts
```
pnpm --filter docs dev
> docs@ dev /Users/dmytro/Desktop/nextra/docs
> next
▲ Next.js 14.2.13
- Local:        http://localhost:3000
✓ Starting...
automatically enabled Fast Refresh for 3 custom loaders
✓ Ready in 1072ms
```
=> use 3 nextra's webpack loaders instead of 4 to improve performance

.changeset/light-shirts-warn.md, .eslintrc.cjs, packages/nextra-theme-docs/src/components/search.tsx
In previous major version, Nextra had a `nextra-search-results` class on the search results panel, that was pretty handy for styling: I have a green hero section on a landing page, so I was using `.nextra-search-results` to remove the backdrop-blur and transparency of the background, preserving legibility of the text.
Closes: (Sorry, I didn't create an issue 😓 )
I'm adding the class back to the place it fits the most.
=> Add `.nextra-search-results` class back to v3

docs/pages/docs/docs-theme/theme-configuration.mdx
Closes: N/A
Add `filename="theme.config.jsx"` to syntax highlight blocks on [theme-configuration](https://nextra.site/docs/docs-theme/theme-configuration) for consistent styling with other pages like [page-configuration](https://nextra.site/docs/docs-theme/page-configuration).
=> add a filename to theme-configuration syntax highlight blocks

.changeset/green-cheetahs-destroy.md, packages/nextra-theme-docs/src/components/toc.tsx
Closes: #3388
I'm not sure of the purpose of `ltr:-_mr-4 rtl:-_ml-4`. Can we remove these to eliminate extra horizontal margin spacing? It seems that after adding `_px-4` in [#3160](https://github.com/shuding/nextra/pull/3160/files#diff-e07f0bc6445c47b38f62eaeb0655948798c2bbb38e87db5123c5c891fcfa49caR60), we no longer need to consider the ltr or rtl direction.
**ltr**
**rtl**
=> remove extra horizontal margin spacing in toc

.changeset/quick-singers-whisper.md, packages/nextra/src/server/compile.ts
Closes: #2915
Now user provided `recmaPulgins` run first. Same as how `remarkPlugins` and `rehypePlugins` work.
This fixes the integration between Nextra 3 and [Code Hike](https://codehike.org/).
=> Apply user's recmaPlugins first

.changeset/nasty-experts-smile.md, packages/nextra-theme-docs/src/mdx-components.tsx
=> hide `<summary>` marker on Safari

docs/pages/docs/docs-theme/theme-configuration.mdx
The documentation is missing the parent key `notFound`.
Without it, users won't know how to edit the theme.config file correctly.
=> chore: add parent key for custom 404 page

.changeset/spotty-dingos-pretend.md, packages/nextra/package.json
fixes https://github.com/shuding/nextra/issues/2948 https://github.com/shuding/nextra/issues/2603
=> fix `Could not find a declaration file for module 'nextra'`

.changeset/fast-poets-hear.md, packages/nextra-theme-docs/src/components/sidebar.tsx, packages/nextra/src/client/components/collapse.tsx
Closes: N/A
This PR aims to simplify the class name of the sidebar file item. Since the file item only needs `_flex _flex-col _gap-1` when `active && props.anchors.length > 0`, I added `_mt-1` to the anchor list to achieve the same effect.
sidebar
mobile nav
=> [v4] simplify the class-name of the sidebar file item

.changeset/calm-dolphins-swim.md, examples/swr-site/next-env.d.ts, packages/nextra/src/client/components/search.tsx
fixes https://github.com/shuding/nextra/issues/3441 https://github.com/shuding/nextra/issues/2450 https://github.com/shuding/nextra/issues/3405
cc @87xie wdyt 😅
Postbuild script will be mentioned in docs, so no need to add here I guess
```json
"postbuild": "pagefind --site .next/server/app --output-path .next/static/chunks/pagefind",
```
=> add helpful error message about not available search on development mode

.changeset/four-fans-reply.md, packages/nextra-theme-docs/src/components/sidebar.tsx
Closes: N/A
This pull request introduces the following:
- Add `aria-expanded` and `aria-controls` attrs to the sidebar collapse button.
- Rename the `showSidebar` to `isExpanded` for better clarity, making it easier to distinguish between `useConfig().hideSidebar` and `!showSidebar`.
- Update the `aria-label` of the collapse button to  "Expand sidebar" or "Collapse sidebar".
- Colocate the sidebar anchors calculation.
expanded
collapsed
=> [v4] add aria attrs to the sidebar collapse button

.changeset/fifty-birds-invite.md, packages/nextra/styles/code-block.css
All code elements written as markdown in mdx files via backticks will automatically have the `nextra-code` class.
Any other code elements that could come from custom components, might not want the default nextra style applied to it.
In fact, if you have tailwind applied to your custom `<code>` elements, it will be overwritten by the global `code:not([class*='twoslash-'])` specifier since it has a higher specificity.
If someone prefers the global css for custom `<code>` elements, they can add the class `nextra-code` to get it applied still.
Closes:
https://github.com/shuding/nextra/issues/3476
css specifier
=> [ISSUE-3476] style: narrow css specificity for code elements

.changeset/six-parrots-dream.md, .eslintrc.cjs, examples/swr-site/app/[lang]/[[...mdxPath]]/page.tsx, packages/nextra/src/client/components/search.tsx
Closes: N/A
In v4 `<Search>`, when receiving multiple pagefind results, the user input update will also be delayed.
Here are the steps to reproduce:
1. Visit the [preview page](https://nextra-v2-git-v4-31-shud.vercel.app/).
1. Type "to" in the search bar.
1. Press the `Backspace` key to delete "o".
https://github.com/user-attachments/assets/cef0b0b3-d19f-46d2-a113-7ddc6722df4f
I separated the `search` and `deferredSearch` for:
- `search`: high-priority state for user input.
- `deferredSearch`: low-priority state for pagefind result calculation.
There might be a better way to solve this. Feel free to close this if it’s not suitable.
https://github.com/user-attachments/assets/357a57c9-dfd9-4b35-bb4c-6997f035fc17 …
=> [v4] defer pagefind results update for prioritizing user input state

.changeset/afraid-pens-teach.md, packages/nextra-theme-docs/src/components/navbar/index.tsx, packages/nextra-theme-docs/src/components/sidebar.tsx
Thank you for Nextra v4 prerelease!
This PR fixes an issue where the color of the upper part of the screen was incorrect when opening the mobile nav in Nextra 4.
When opening the mobile nav in Light mode, the overlay at the top header section feels transparent and seems off. Just like in Nextra 3, I've adjusted it so that the header color does not change when the mobile nav is opened.
Attached are the test results from the following example:
https://github.com/shuding/nextra/tree/v4-v2/examples/docs
|    | Without banner   |  With banner  |
|----|----|----|
| Before|  ![before](https://github.com/user-attachments/assets/f8f09165-ef4b-43fa-a7a5-901adb858747)  |  ![before-banner](https://github.com/user-attachments/assets/9f6ecaad-b775-4695-b945-45cdf187bfec) |
| After | …
=> [v4] fix mobile nav position

.changeset/thirty-seahorses-bathe.md, packages/nextra/src/server/loader.ts
Closes:
`mdxOptions.rehypePrettyCodeOptions.transformers`overrides pre-existing twoslash transformer. 
```js
const withNextra = nextra({
theme: 'nextra-theme-docs',
themeConfig: './theme.config.tsx',
mdxOptions: {
rehypePrettyCodeOptions: {
transformers: [...] // <---
}
}
})
```
=> fix(nextra/server): Prevent overwriting of transformer

.changeset/big-years-agree.md, docs/components/_slider.tsx, docs/pages/docs/docs-theme/theme-configuration.mdx, packages/nextra-theme-docs/src/components/head.tsx, packages/nextra-theme-docs/src/constants.tsx, packages/nextra-theme-docs/src/schemas.ts, packages/nextra-theme-docs/tailwind.config.ts
within theme config, we currently support tweaking color.hue and color.saturation 
this PR comples by adding color.lightness support 
for some hue/sat combos lightness needs to be tweaked independantly on light and dark mode for readability, ie. : 
| light | dark | 
| ---- | ---- | 
| ![CleanShot 2024-10-30 at 12  28 05@2x](https://github.com/user-attachments/assets/b209558a-e08d-4040-b501-f094737132eb) | ![CleanShot 2024-10-30 at 12  28 21@2x](https://github.com/user-attachments/assets/4c21e671-729b-4974-8668-8402a3db551d) |
| ![CleanShot 2024-10-30 at 12  29 26@2x](https://github.com/user-attachments/assets/854e8005-15d6-40fe-a4db-3b196883b507) | ![CleanShot 2024-10-30 at 12  29 59@2x](https://github.com/user-attachments/assets/5f1b8b2c-524a-4fec-9079-9d4bf0c629bc) |
| ![CleanShot …
=> feat(nextra-theme-docs): primary color.lightness theme config

.changeset/perfect-cats-hang.md, examples/docs/app/_ignored/_meta.js, examples/docs/app/_ignored/page.mdx, examples/docs/content/page.mdx, packages/nextra/__test__/generate-page-map.test.ts, packages/nextra/src/server/page-map/generate.ts
- do not treat `content/page.{mdx,md}` as index page
- skip visiting directories which starts with underscore for `app` directory
=> [v4] do not treat `content/page.{mdx,md}` as `index` page

.changeset/honest-falcons-brush.md, packages/nextra-theme-docs/src/components/404/index.client.tsx, packages/nextra-theme-docs/src/components/404/index.tsx
inspired from https://github.com/graphql/graphql.github.io/pull/1810
=> [v4] include `document.referrer` in link in `<NotFoundPage>` component

.github/workflows/lint.yml, .github/workflows/nextjs-bundle-analysis.yml, .github/workflows/release.yml, .github/workflows/test.yml, package.json
according https://turbo.build/repo/docs/guides/ci-vendors/github-actions#caching-with-github-actionscache
fixes https://github.com/shuding/nextra/issues/3614
=> [v4] caching turbo with with GitHub `actions/cache`

docs/pages/docs/docs-theme/_meta.ts, docs/pages/docs/guide/_meta.ts, docs/pages/docs/guide/advanced/table.mdx, docs/pages/docs/guide/built-ins.mdx, docs/pages/docs/guide/built-ins/_meta.ts, docs/pages/docs/guide/built-ins/table.mdx
Performs the suggested docs update proposed in https://github.com/shuding/nextra/issues/3530
The issue being that the latest changes to MDX no longer render literal `<table>` and its associated elements correctly. The documentation should be updated to point users to consume the existing built-in components: `<Table>`, `<Td>`, `<Th>`, and `<Tr>`.
The non-working example under Advanced → Rendering Tables has been removed, and instead point users to the new built-in component page created for `<Table>` components under Built-in components → Table.
The cards are ordered alphabetically + a new card for `<Table>` has been added:
Advanced table usage page now has a callout linking to built-in table component:
A new built-in component page for `<Table>` has been created, following a similar …
=> docs: literal table with built-in components

.changeset/sharp-knives-care.md, docs/app/globals.css, packages/nextra/src/client/mdx-components.tsx
=> [v4] fix external svg icon was added for span in `<Anchor>`

.changeset/loud-kids-attack.md, packages/nextra-theme-docs/tailwind.config.ts
Made a typo in https://github.com/shuding/nextra/pull/3592
Closes:
=> fix(nextra-theme-docs): incorrect makePrimaryColor relative value for tailwind primary-900

.changeset/slimy-shoes-poke.md, packages/nextra/src/client/components/tabs/tabs.tsx
I'm adding `tabClassName` prop to make styling HeadlessTab easier (without `> button` selector).
cc @dimaMachina
=> Accept `tabClassName`

.changeset/ninety-birds-teach.md, packages/nextra-theme-docs/package.json, packages/nextra-theme-docs/src/stores/config.tsx, pnpm-lock.yaml
Closes: N/A
Since v5 is the current major version of Zustand, I think it would be appropriate to upgrade to v5 in `nextra-theme-docs` as well.
I reviewed the current usage of `useConfig` and found that using a `selector` and `shallow` is unnecessary. I simplified the implementation so that each call to `useConfig` returns the current state directly and ensures reference consistency, so `useStoreWithEqualityFn` and `shallow` are no longer needed. With this change, migration to v5 is successful.
=> [v4] migrate to zustand v5

.changeset/plenty-rabbits-return.md, packages/nextra-theme-docs/src/stores/config.tsx
Closes: N/A
I noticed that the effect callback updating the store on the initial render in `<ConfigProvider>` is unnecessary, which causes the consumers of `useConfig` to re-render. So, I’d like to fix this.
I think Zustand might not be necessary in the current scenario, so I made the following adjustments:
- Memoize the `normalizedPages` and store it in the config context.
- Derive the `hideSidebar` state in the `useConfig` hook.
Feel free the close this if I missed something obvious.
=> [v4] avoid unnecessary updates to config store on initial render

.changeset/many-gifts-cough.md, packages/nextra/src/server/loader.ts, packages/nextra/tsconfig.json, packages/nextra/tsup.config.ts
fixes https://github.com/shuding/nextra/issues/3675
=> [v4] Cache the result of `repository.getFileLatestModifiedDateAsync` because it can slow down Fast Refresh for uncommitted files.

.changeset/fifty-apricots-report.md, packages/nextra/src/server/loader.ts
fixes https://github.com/shuding/nextra/issues/3675#issuecomment-2466490115
=> [v4] use `Date.now()` for last edit time on development and git last commit time on production

.changeset/loud-donkeys-itch.md, packages/nextra-theme-docs/src/components/sidebar.tsx
Code that previously targeted the sidebar is broken without it and there's no other elegant way to target it.
Added `.nextra-sidebar-container` class back.
=> [v4] nextra-mobile-nav

.changeset/afraid-foxes-deny.md, docs/app/page.css, packages/nextra-theme-docs/src/components/footer/index.tsx, packages/nextra-theme-docs/src/components/navbar/index.tsx, packages/nextra-theme-docs/src/mdx-components/index.tsx, packages/nextra/src/client/components/head.tsx
This moves the content width that was used throughout nextra `max-w-[90rem]` to a css variable. This way the changing the value in the future should be easier, but it also makes it possible to customize the max width of the content for people using nextra without needing to overload a tailwind class in a hacky way.
I have several screenshots in my docs that are a pretty consistent 1280x720, due to the max width of the content view being limited to `90rem` these images are always scaled down quite a bit. I was hoping to make the max width a bit wider for this reason but didn't see an easy way to do so without overloading the `_max-w-[90rem]` tailwind CSS class; which didn't seem like a good idea.
I've simply lifted the value passed to max width to a css variable similar to the other css …
=> [v4] feat(theme): Content width css variable for easier customization

.changeset/new-pumpkins-joke.md, packages/nextra/src/server/page-map/to-page-map.ts
can't be normalized for `(folder)/page.tsx`
=> [v4] adjust RegEx for folder groups in app router

.changeset/itchy-frogs-shop.md, packages/nextra/src/client/hocs/with-icons.tsx
noticed icons were not appears in https://github.com/dotansimha/graphql-yoga/pull/3570
=> [v4] add icons for ```javascript and ```typescript langs

.changeset/rotten-llamas-drum.md, packages/nextra/src/server/schemas.ts
`transformTitle` is changing the `MetaRecord` type to `unknown`. By adding that generic parameter `T`, we allow it to preserve the type.
I took liberty of moving `transformTitle` up, because there's only one union constituent accepting a string. This also makes the `MetaRecord` type more readable in error messages. @dimaMachina Let me know if that makes sense.
=> Fix the signature of transformTitle

.changeset/tasty-nails-cover.md, packages/nextra-theme-docs/src/components/sidebar.tsx, packages/nextra/src/client/components/banner/index.tsx
cc @hasparus this fixx bug with https://github.com/graphql-hive/console/blob/12f74af0a74d29534c50362b341cf8d9d659c014/packages/web/docs/src/app/layout.tsx#L38-L39
=> [v4] fix unclickable `type: menu` on mobile nav

.changeset/blue-sloths-play.md, packages/nextra/src/client/components/search.tsx
closes https://github.com/shuding/nextra/issues/3901
=> [v4] Don't focus search input on `⌘ + Shift + k` or `Ctrl + Shift + k`.

.changeset/big-nails-end.md, packages/nextra/styles/steps.css, packages/nextra/styles/subheading-anchor.css
In Tailwind CSS v4 beta, the `@apply` directive does not behave as expected when used with dark theme utility classes on pseudo-elements. 
While the root cause is unclear, this PR introduces a temporary workaround for release candidate users. If it is not suitable, feel free to close it.
Closes:
=> fix steps background on dark mode / fix headings anchor link color on dark mode

.changeset/hungry-planets-divide.md, packages/nextra/styles/steps.css
The top margin in `.nextra-steps` is redundant and makes the step unaligned with the text.
=> Remove margin-top from .nextra-steps so it's even

docs/app/docs/file-conventions/meta-file/page.mdx, docs/app/docs/file-conventions/page.mdx
Update Folders with Index Page to the new format
The Old format does not work anymore in v4.
=> Update Folders with Index Page to v4

.changeset/honest-parrots-rest.md, packages/nextra/src/client/components/head.tsx
closes https://github.com/shuding/nextra/issues/3998
=> fix `::selection` styles, use `hsla` instead of `hsl` because it can overlap text with `::selection` background when `background-clip: text` is set

.changeset/giant-garlics-kiss.md, docs/app/docs/page.mdx, packages/nextra/src/client/normalize-pages.ts, packages/nextra/src/server/__tests__/__snapshots__/normalize.test.ts.snap, packages/nextra/src/server/__tests__/normalize.test.ts
fix https://github.com/shuding/nextra/issues/4049
=> fix regression from Nextra 3 setting `theme.collapsed?: boolean` in `_meta` file for folders has no effect in sidebar

.changeset/nice-weeks-dream.md, packages/nextra/src/client/hocs/with-github-alert.tsx
css has capitalize support
no visual changes
=> Fix capitalization of alert name in GitHub alert HOC

.changeset/fresh-llamas-judge.md, examples/swr-site/app/[lang]/layout.tsx, packages/nextra-theme-docs/src/components/locale-switch.tsx, packages/nextra-theme-docs/src/components/sidebar.tsx, packages/nextra-theme-docs/src/components/theme-switch.tsx
lite mode on mobile doesn't work, now it behaves like locale switch
before
after
=> fix: theme toggle lite mode on mobile

.changeset/big-starfishes-punch.md, examples/docs/src/app/layout.jsx, packages/nextra-theme-docs/src/components/footer/index.tsx
Render the footer content only if it is defined in the theme configuration, improving the component's flexibility and responsiveness to theme changes.
Closes https://github.com/shuding/nextra/issues/4031
before
after
=> Conditionally render footer based on children presence to align with user expectation and remove empty space

.changeset/twelve-hotels-nail.md, docs/app/_meta.global.tsx, packages/nextra-theme-docs/src/mdx-components/wrapper.client.tsx
this pr gives the user more control and adheres to user expectation.
implicit, undocumented, and no workaround behavior like this should be avoided.
Closes: #4081
Closes: https://github.com/shuding/nextra/issues/4030
http://localhost:3000/about
before
after
docusaurus allows rendering toc on regular pages which is useful and i need this
I realize this changes previous behavior but this is needed and it's best to do it now while v4 is new and very few people are using it.
=> Ability to render TOC in type page

.changeset/mean-pears-drive.md, packages/nextra/src/client/mdx-components/details.tsx
fixes https://github.com/shuding/nextra/issues/4074
=> fix a sudden height jump on opening for `<detail>` element when his last children contain margins

.changeset/slimy-beans-grin.md, packages/nextra-theme-docs/src/components/back-to-top.tsx
Matches the styling of other `toc` links
Adds `x:cursor-pointer` to the `backToTop` component
=> Add `x:cursor-pointer` style to the `backToTop` component

packages/nextra/src/client/components/bleed.tsx
was broken after https://github.com/shuding/nextra/pull/4085 which isn't released yet
closes https://github.com/shuding/nextra/issues/4103
=> fix `<Bleed>` overflow 

examples/swr-site/app/[lang]/remote/graphql-eslint/[[...slug]]/page.tsx, examples/swr-site/app/[lang]/remote/graphql-yoga/[[...slug]]/page.tsx
Closes: #4116 
Update page routing to accommodate an optional slug parameter, ensuring proper handling when the slug is not provided.
=> fix remote docs example

.changeset/cold-cycles-fix.md, packages/nextra-theme-docs/src/mdx-components/wrapper.client.tsx
Closes: #4110 
Revise the rendering logic of the Table of Contents to consider theme configuration and the active type, ensuring proper display based on these conditions.
=> Update TOC to render correctly on type=page

.changeset/friendly-windows-count.md, docs/app/_components/i18n-demo.tsx, examples/docs/src/app/showcase/(overview)/page.jsx, packages/eslint-config/src/index.ts, packages/nextra/src/server/__tests__/to-page-map.test.ts, packages/nextra/src/server/page-map/to-page-map.ts
Closes: #4148
Use Next.js utility function `normalizeAppPath` to align path normalization behavior.
=> fix: normalize path with nextjs `normalizeAppPath` utility function

.changeset/flat-rabbits-accept.md, packages/nextra/src/server/compile-metadata.ts
fix https://github.com/shuding/nextra/issues/4164
=> fix `Could not parse expression with acorn` for inline math code in `development` mode without turbopack enabled

docs/app/docs/advanced/remote/page.mdx
The link to the remote content example changed.
=> fix(remote-content): use correct repo link

README.md
Revise the installation instructions to include enabling Corepack and provide guidance for installing it if the command fails. Clarify the steps for installing workspace dependencies with PNPM.
i had this idea because corepack failed to install the latest version of pnpm due to it being out of date
=> Update installation instructions for Corepack and PNPM

.changeset/swift-squids-rhyme.md, packages/nextra-theme-docs/src/components/sidebar.tsx
this adds hover bg color transition animation, had to remove `*:` because they were breaking the bg transition and it don't seem to be adding anything usefull
https://github.com/user-attachments/assets/57274e67-29d9-43d2-97ac-31e5e69def55
=> Improve sidebar item arrow animation

.changeset/tender-forks-type.md, packages/nextra/src/client/components/search.tsx, packages/nextra/src/server/page-map/index.ts
fixes https://github.com/shuding/nextra/issues/4367
=> fix `TypeError: page.generateMetadata is not a function` when using with `withSentryConfig` plugin

.changeset/open-trains-wait.md, docs/app/docs/file-conventions/mdx-components-file/page.mdx, docs/mdx-components.tsx, packages/eslint-config/src/index.ts, packages/nextra-theme-docs/src/components/sidebar.tsx, packages/nextra/src/client/mdx-components.ts, packages/nextra/src/client/mdx-components/anchor.tsx, packages/nextra/src/server/index.ts
fix https://github.com/shuding/nextra/issues/4419
=> Fix: Received `false` for a non-boolean attribute `prefetch`. Allow override `next-mdx-import-source-file` in `turbopack.resolveAlias` option

docs/app/docs/file-conventions/mdx-components-file/page.mdx
The current docs for `next-mdx-import-source-file` resolve error is not working for Next 15.
Update the docs about the `next-mdx-import-source-file` resolve error for Next 15.
=> Add Next 15 guide for `next-mdx-import-source-file` resolve error

docs/app/docs/file-conventions/meta-file/page.mdx
Closes: N/A
On the [meta-file page](https://nextra.site/docs/file-conventions/meta-file), two anchor elements have the same `typesetting` id, which causes the TOC links to jump to the wrong section.
I specified a custom id `#typesetting-section` for the heading to ensure the TOC link works as expected.
https://github.com/user-attachments/assets/234674d0-b88b-4f52-9254-1fda9b46b808
=> Specify custom id for toc link to the typesetting section

docs/app/docs/advanced/table/page.mdx
fixed link to built-ins/table
Broken link
Closes:
https://github.com/shuding/nextra/issues/4708
just removed `guide` from URL linking to the `built-ins/table`
=> Updated docs/advanced/table
