.nextra/config.js
.nextra/layout.js
components/arrow-right.js
nextra.config.js

Builds on #2
Adds Previous and Next links to the top part of the footer. Can be disabled in config:
```json
prevLinks: false,
nextLinks: false
```
Custom footer is also changed in config (example in code):
```js
footer: <span>Hello!</span>
```

Support custom footer, add Next/Previous links

---

.nextra/config.js
.nextra/layout.js
.nextra/styles.css
components/search.js
package.json
yarn.lock

Builds on #3 
Very basic implementation of a search. Right now, only searches through the titles of each page.
Todo:

Add basic version of Search

---

README.md
packages/nextra/package.json

This allows watching nextra and nextra-theme-docs paralelly

dev(nextra): Add watch command

---

README.md
packages/nextra-theme-docs/package.json
packages/nextra-theme-docs/postcss.config.js
packages/nextra/package.json
yarn.lock

You can now run `yarn dev` to develop the docs theme and it will watch changes in both JS and CSS.

Add postcss for Tailwind watch mode

---

examples/docs/pages/nextra/test.en.mdx
packages/nextra-theme-docs/bleed.js
packages/nextra-theme-docs/package.json
packages/nextra-theme-docs/src/bleed.js
packages/nextra-theme-docs/src/callout.js
packages/nextra-theme-docs/src/locale-switch.js
packages/nextra-theme-docs/src/styles.css
packages/nextra-theme-docs/src/theme-switch.js
packages/nextra-theme-docs/src/utils/use-mounted.js
packages/nextra-theme-docs/tailwind.config.js

- Add `nextra-theme-docs/bleed` component ([example](https://nextra-dev-git-bleed.shuding1.vercel.app/nextra/test#same-slug-1))
- Fix hydration mismatch
- Fix container alignment
- Fix other styles

Add Bleed component

---

packages/nextra-theme-blog/src/mdx-theme.js

Closes https://github.com/shuding/nextra/issues/110.

Make external links safe by default.

---

packages/nextra-theme-docs/src/index.js
packages/nextra-theme-docs/src/misc/default.config.js

Via `config.defaultMenuCollapsed`
Fix https://github.com/shuding/nextra/issues/109
Fix https://github.com/vercel/swr-site/issues/81

Allow menus collapsed by default

---

packages/nextra-theme-docs/src/index.js
packages/nextra-theme-docs/src/locale-switch.js

minor accessibility issues ul-li

---

packages/nextra-theme-docs/src/misc/default.config.js

get current year using javascript instead of outdated year.

feat: get current year dynamically

---

pages/docs/get-started.mdx

update docs to get current year instead of static.

chore: update docs based on #156

---

packages/nextra-theme-docs/package.json
packages/nextra-theme-docs/src/callout.js
packages/nextra-theme-docs/tailwind.config.js
yarn.lock

Added `type` prop to callouts; also upgraded TailwindCSS to use JIT mode.

Better Callouts

---

examples/docs/pages/meta.en.json
examples/docs/theme.config.js
packages/nextra-theme-docs/src/index.js
packages/nextra-theme-docs/src/navbar.js
packages/nextra-theme-docs/src/search.js
packages/nextra-theme-docs/src/sidebar.js
packages/nextra-theme-docs/src/stork-search.js
packages/nextra-theme-docs/src/styles.css
packages/nextra-theme-docs/src/utils/normalize-pages.js

Show logo and pages on the navbar and move search into the menu on mobile (<md).

Improvements to search and mobile layout

---

pages/index.mdx

Fixed in order to redirect to the correct page. (_right now the link is returning 404_)

MDX internal link was broken

---

package.json
packages/nextra-theme-blog/package.json
packages/nextra-theme-docs/package.json
packages/nextra-theme-docs/src/index.js
packages/nextra-theme-docs/src/toc.js
packages/nextra/package.json
packages/nextra/src/index.js

- fix MDXProvider 
- fix TOC 
- bump @mdx-js/react and @mdx-js/loader
ref: https://github.com/mdx-js/mdx/issues/1831

fix for MDXProvider/TOC, and bump mdx version to 2.0.0-rc2 

---

packages/nextra-theme-blog/src/index.js

feat: custom head according to meta or frontMatter of post

---

packages/nextra-theme-blog/src/nav.js

```
Warning: Each child in a list should have a unique "key" prop. 
Check the top-level render call using <div>. See https://reactjs.org/link/warning-keys for more information. at Nav (webpack-internal:///../../packages/nextra-theme-blog/dist/index.js:106:16) .....
```

fix: react key warning

---

packages/nextra-theme-blog/scripts/build.js
packages/nextra-theme-blog/scripts/dev.js
packages/nextra-theme-docs/scripts/build.js
packages/nextra-theme-docs/scripts/dev.js
packages/nextra/scripts/build.js
packages/nextra/scripts/dev.js

Set lower build target

---

pages/features/ssg.mdx

docs: fix typo/grammar

---

packages/nextra-theme-blog/src/meta.tsx
packages/nextra-theme-blog/src/utils/get-tags.ts

feat: [blog theme] support array typed tags; fix #302

---

packages/nextra-theme-blog/src/nav.tsx
packages/nextra-theme-blog/src/types.ts

feat: [blog theme] add pure nav links; fix #301

---

pages/themes/blog/index.mdx

fix #239 
add docs for #240  #305

docs: update config for nextra-theme-blog

---

packages/nextra-theme-docs/src/sidebar.tsx
packages/nextra-theme-docs/src/styles.css

fix: theme switch menu position

---

packages/nextra-theme-docs/src/locale-switch.tsx
packages/nextra-theme-docs/src/sidebar.tsx
packages/nextra-theme-docs/src/styles.css
packages/nextra/src/locales.ts

This PR reimplements the locale middleware which fixes several locale related issues.

fix: Locale issues

---

packages/nextra-theme-docs/src/flexsearch.js
packages/nextra-theme-docs/src/misc/default.config.tsx
packages/nextra-theme-docs/src/search.tsx
packages/nextra-theme-docs/src/styles.css
packages/nextra-theme-docs/src/types.ts
packages/nextra-theme-docs/src/utils/render-component.tsx
packages/nextra/src/mdx-plugins/structurize.js

Group search results by page and other improvements

---

examples/docs/src/pages/meta.json
examples/swr-site/next.config.js
examples/swr-site/pages/docs/meta.en-US.json
examples/swr-site/pages/meta.en-US.json
examples/swr-site/pages/meta.es-ES.json
examples/swr-site/pages/meta.ja.json
examples/swr-site/pages/meta.ko.json
examples/swr-site/pages/meta.ru.json
examples/swr-site/pages/meta.zh-CN.json
packages/nextra-theme-docs/src/index.tsx
packages/nextra-theme-docs/src/misc/theme-context.tsx
packages/nextra-theme-docs/src/styles.css
packages/nextra-theme-docs/src/utils/normalize-pages.tsx
packages/nextra/src/filter-route-locale.ts
packages/nextra/src/loader.ts

`"type": "nav"` is now `"type": "page"`.

breaking: Add theme context fields

---

package.json
packages/nextra-theme-docs/package.json
packages/nextra-theme-docs/src/env.d.ts
packages/nextra-theme-docs/src/flexsearch.js
packages/nextra-theme-docs/src/select.tsx
pnpm-lock.yaml

close #373
https://github.com/tailwindlabs/headlessui/pull/1055/files?file-filters%5B%5D=.json&show-deleted-files=true&show-viewed-files=true#diff-2a6e31e53b33defec6911c91bcf10a0c3c7a51dedb2af7a554f88e9f8b2abdfd

fix: upgrade @headlessui/react

---

examples/swr-site/theme.config.js
package.json
packages/nextra-theme-docs/src/flexsearch.js
packages/nextra-theme-docs/src/head.tsx
packages/nextra-theme-docs/src/misc/default.config.tsx
packages/nextra-theme-docs/src/navbar.tsx
packages/nextra-theme-docs/src/styles.css
packages/nextra-theme-docs/tailwind.config.js
pnpm-lock.yaml

Fix backdrop blur and divider styles, remove the `font` option and adjust the typography settings.

Styling improvements

---

examples/swr-site/next.config.js
packages/nextra/src/compile.ts
packages/nextra/src/mdx-plugins/structurize.js

Option to disable indexing codeblocks

---

examples/swr-site/theme.config.js
packages/nextra-theme-docs/src/index.tsx
packages/nextra-theme-docs/src/misc/default.config.tsx
packages/nextra-theme-docs/src/types.ts

So you can set the default theme or force the theme to be dark.

Support for a subset of next-themes options

---

packages/nextra-theme-docs/src/flexsearch.js

Improve search indexing

---

packages/nextra-theme-docs/package.json
packages/nextra-theme-docs/src/sidebar.tsx
packages/nextra/package.json
pnpm-lock.yaml

Style fixes, republish packages

---

packages/nextra/package.json
pnpm-lock.yaml

Update Shiki dependency to the latest `0.10.1` which include's RelationalAI's Rel language.

Update shiki to 0.10.1

---

examples/swr-site/pages/index.en-US.mdx
examples/swr-site/pages/meta.en-US.json
examples/swr-site/theme.config.js
packages/nextra-theme-blog/src/styles.css
packages/nextra-theme-docs/src/breadcrumb.tsx
packages/nextra-theme-docs/src/callout.tsx
packages/nextra-theme-docs/src/components/tabs.tsx
packages/nextra-theme-docs/src/footer.tsx
packages/nextra-theme-docs/src/index.tsx
packages/nextra-theme-docs/src/misc/theme-context.tsx
packages/nextra-theme-docs/src/misc/theme.tsx
packages/nextra-theme-docs/src/navbar.tsx
packages/nextra-theme-docs/src/select.tsx
packages/nextra-theme-docs/src/sidebar.tsx
packages/nextra-theme-docs/src/styles.css
packages/nextra-theme-docs/src/toc.tsx
packages/nextra-theme-docs/src/types.ts
packages/nextra-theme-docs/tailwind.config.js

- Better typesetting for articles via the `"typesetting": "article"` config in page theme.
- Banner support via `banner` and `bannerKey`, closes #391.
- Display extra content aside via `tocExtraContent`.
- Customizable theme primary color via `--nextra-primary-hue`.
- Better contrast in dark mode.
- Better scrollbar styles in the sidebar.
- A11y: high contrast mode.
- Improved initial sidebar focus.

Improvements

---

examples/docs/src/pages/nextra/test.mdx
packages/nextra-theme-docs/src/callout.tsx
packages/nextra-theme-docs/tailwind.config.js

Just a small styling addition to the callout component.

Add blue info colors to the callout component

---

packages/nextra-theme-docs/src/index.tsx
packages/nextra-theme-docs/src/navbar.tsx
packages/nextra-theme-docs/src/sidebar.tsx
packages/nextra-theme-docs/src/styles.css
packages/nextra-theme-docs/src/toc.tsx

Move ToC out of article from the layout

---

examples/swr-site/pages/meta.en-US.json
packages/nextra-theme-docs/src/index.tsx
packages/nextra-theme-docs/src/navbar.tsx

Layout improvements

---

packages/nextra-theme-blog/tailwind.config.js
packages/nextra-theme-docs/tailwind.config.js

https://tailwindcss.com/docs/content-configuration

fix(blog/docs): remove `css` from content field in `tailwind.config.js`

---

packages/nextra/package.json
pnpm-lock.yaml

fix(nextra): remove `p-limit` from dependencies

---

packages/nextra/src/plugin.ts

related https://github.com/shuding/nextra/pull/485

fix(nextra): specify type of `NextraPlugin.config`

---

.changeset/config.json
.changeset/pre.json
.changeset/selfish-avocados-report.md
.github/workflows/release.yml
examples/blog/package.json
examples/docs/package.json
examples/swr-site/package.json
package.json
pnpm-lock.yaml

More information can be found in [Changesets' docs](https://github.com/changesets/changesets).
Now this repository will have 3 special branches:
- `main`: The default branch which contains the documentation for Nextra.
- `core`: The branch with actual Nextra code in development, will be published as pre-releases by the CI.
- `stable`: The stable branch. When merging `core` into `stable`, CI will cut a stable release.

Add Changesets and setup pre-release and release CI

---

.changeset/olive-lions-help.md
.github/workflows/release.yml

Fix release workflow

---

.changeset/rude-colts-agree.md
packages/nextra-theme-blog/src/nav.tsx

Fixes a minor regression in #535 
cc @B2o5T

change(theme-blog): make nav items center aligned

---

.changeset/three-olives-admire.md
packages/nextra-theme-docs/src/sidebar.tsx

I have some problems due to this class in my app, we don’t need this as we specify transform here
https://github.com/shuding/nextra/blob/core/packages/nextra-theme-docs/src/styles.css#L267
and here for an open state
https://github.com/shuding/nextra/blob/core/packages/nextra-theme-docs/src/styles.css#L276

fix sidebar.tsx style

---

.changeset/lazy-hounds-tan.md
packages/nextra-theme-docs/src/flexsearch.js
packages/nextra/src/constants.ts
packages/nextra/src/index.ts
packages/nextra/src/loader.ts

related https://github.com/shuding/nextra/pull/520#issuecomment-1193168203

fix(nextra/docs): fallback search to `en-US` instead `default`

---

.changeset/flat-crabs-thank.md
packages/nextra/src/loader.ts

fixes https://github.com/shuding/nextra/issues/573

fix: print shallow warning only once

---

.changeset/tiny-rice-boil.md
examples/swr-site/pages/docs/advanced/code-highlighting.en-US.mdx
examples/swr-site/pages/docs/advanced/meta.en-US.json
packages/nextra-theme-docs/src/styles.css
packages/nextra/__test__/__snapshots__/page-map.test.ts.snap
packages/nextra/package.json
packages/nextra/src/compile.ts
pnpm-lock.yaml

related https://github.com/shuding/nextra/pull/501

feat(nextra-theme-docs): bump `rehype-pretty-code` version, support `showLineNumbers`

---

.github/workflows/ci.yml
.github/workflows/release.yml

ci: pnpm cache

---

.changeset/forty-snakes-share.md
examples/swr-site/pages/docs/suspense.en-US.mdx
examples/swr-site/pages/index.en-US.mdx
packages/nextra-theme-docs/tailwind.config.js

fixes https://github.com/shuding/nextra/issues/588

fix: broken flexsearch styles

---

.changeset/eight-baboons-march.md
.github/workflows/ci.yml
.github/workflows/release.yml
examples/blog/package.json
examples/docs/package.json
examples/docs/src/pages/themes/docs/configuration.mdx
examples/swr-site/package.json
package.json
packages/nextra-theme-blog/package.json
packages/nextra-theme-blog/src/index.tsx
packages/nextra-theme-blog/tailwind.config.js
packages/nextra-theme-docs/package.json
packages/nextra-theme-docs/src/bleed.tsx
packages/nextra-theme-docs/src/callout.tsx
packages/nextra-theme-docs/src/footer.tsx
packages/nextra-theme-docs/src/index.tsx
packages/nextra-theme-docs/src/misc/active-anchor.tsx
packages/nextra-theme-docs/src/misc/theme.tsx
packages/nextra-theme-docs/src/navbar.tsx
packages/nextra-theme-docs/src/search.tsx
packages/nextra-theme-docs/src/toc.tsx
packages/nextra-theme-docs/src/types.ts
packages/nextra/package.json
pnpm-lock.yaml
turbo.json

feat: react 18

---

.changeset/cool-houses-return.md
packages/nextra-theme-docs/src/select.tsx

feat: add cursor pointer to locale and theme switch

---

.changeset/mean-rules-beg.md
package.json
packages/nextra-theme-blog/postcss.config.js
packages/nextra-theme-blog/src/styles.css
packages/nextra-theme-docs/postcss.config.js
packages/nextra-theme-docs/src/styles.css
packages/nextra-theme-docs/src/variables.css
pnpm-lock.yaml

also, we can share `code-blocks` styles to avoid code duplications but in another PR

chore(blog/docs): use `postcss-import` to import css variables styles

---

.changeset/unlucky-impalas-clean.md
packages/nextra-theme-docs/src/flexsearch.jsx
packages/nextra-theme-docs/src/styles.css

Closes #625 and make the search input's font size 16px on mobile (otherwise iOS Safari will scale automatically).

UI bug fixes

---

pages/get-started.mdx

Tiny copy change to the getting started

Small copy change

---

.changeset/pretty-starfishes-check.md
packages/nextra-theme-blog/package.json
packages/nextra-theme-docs/package.json
packages/nextra-theme-docs/src/components/bleed.tsx
packages/nextra-theme-docs/src/components/breadcrumb.tsx
packages/nextra-theme-docs/src/components/flexsearch.jsx
packages/nextra-theme-docs/src/components/footer.tsx
packages/nextra-theme-docs/src/components/nav-links.tsx
packages/nextra-theme-docs/src/components/navbar.tsx
packages/nextra-theme-docs/src/components/search.tsx
packages/nextra-theme-docs/src/components/select.tsx
packages/nextra-theme-docs/src/components/sidebar.tsx
packages/nextra-theme-docs/src/components/tabs.tsx
packages/nextra-theme-docs/src/components/toc.tsx
packages/nextra-theme-docs/src/index.tsx
pnpm-lock.yaml

fixes https://github.com/shuding/nextra/issues/639

replace `classnames` package with `clsx` as he's faster

---

.changeset/stale-onions-study.md
packages/nextra-theme-blog/src/index.tsx
packages/nextra-theme-docs/src/index.tsx

fixes https://github.com/shuding/nextra/issues/630

export `useConfig` and `useTheme`

---

packages/nextra-theme-docs/package.json
pnpm-lock.yaml

deps: update title to 3.5.1

---

.changeset/angry-apples-shout.md
packages/nextra-theme-docs/src/components/navbar.tsx

works as before but without 3 unneeded divs

remove unneeded wrappers `<div />`s in `<Navbar />`

---

.changeset/brave-deers-swim.md
examples/swr-site/pages/meta.en-US.json
packages/nextra-theme-docs/src/components/flexsearch.jsx
packages/nextra-theme-docs/src/components/navbar.tsx

Make the search input responsive on narrow screens

---

.changeset/brown-lizards-collect.md
packages/nextra-theme-docs/src/index.tsx
packages/nextra-theme-docs/src/mdx-components.tsx
packages/nextra-theme-docs/src/types.ts

closes https://github.com/shuding/nextra/pull/230

allow override `MDXProvider.components`

---

.changeset/sharp-carpets-care.md
packages/nextra-theme-docs/package.json
packages/nextra-theme-docs/src/components/flexsearch.tsx
packages/nextra-theme-docs/src/components/highlight-matches.tsx
packages/nextra-theme-docs/src/components/input.tsx
packages/nextra-theme-docs/src/components/match-sorter-search.tsx
packages/nextra-theme-docs/src/components/search.tsx
packages/nextra-theme-docs/src/env.d.ts
packages/nextra-theme-docs/src/styles.css
packages/nextra-theme-docs/src/types.ts
pnpm-lock.yaml

`<MemoizedStringWithMatchHighlights />` was extracted in `components` directory as `<HighlightMatches />` to be reused in `<MatchSorterSearch />`.

match-sorter search should highlight every match like flexsearch, update `match-sorter`

---

.changeset/two-lizards-fry.md
packages/nextra-theme-docs/src/components/search.tsx

fixes https://github.com/shuding/nextra/issues/554

do not add `basePath` to the links

---

.changeset/quick-masks-rhyme.md
examples/swr-site/theme.config.tsx
packages/nextra-theme-docs/src/index.tsx
packages/nextra-theme-docs/src/types.ts

we need it to add Giscus comments in our websites

add `DocsThemeConfig.bodyExtraContent` option

---

packages/nextra-theme-docs/src/styles.css

fixes https://github.com/shuding/nextra/issues/710

bring back sidebar active link classes

---

.changeset/sweet-worms-visit.md
examples/docs/src/theme.config.js
examples/swr-site/theme.config.tsx
packages/nextra-theme-docs/src/components/head.tsx
packages/nextra-theme-docs/src/constants.tsx
packages/nextra-theme-docs/src/types.ts

fixes https://github.com/shuding/nextra/issues/704  https://github.com/shuding/nextra/issues/679

fix `useConfig`/`useRouter` inside `head()`

---

.changeset/witty-numbers-smash.md
examples/swr-site/pages/index.en-US.mdx
examples/swr-site/pages/index.es-ES.mdx
examples/swr-site/pages/index.ja.mdx
examples/swr-site/pages/index.ko.mdx
examples/swr-site/pages/index.ru.mdx
examples/swr-site/pages/index.zh-CN.mdx
examples/swr-site/theme.config.tsx
packages/nextra-theme-docs/src/components/breadcrumb.tsx
packages/nextra-theme-docs/src/components/highlight-matches.tsx
packages/nextra-theme-docs/src/components/nav-links.tsx
packages/nextra-theme-docs/src/components/navbar.tsx
packages/nextra-theme-docs/src/components/search.tsx
packages/nextra-theme-docs/src/components/sidebar.tsx
packages/nextra-theme-docs/src/components/toc.tsx
packages/nextra-theme-docs/src/mdx-components.tsx
packages/nextra-theme-docs/src/styles.css

otherwise my pagination's buttons with `layout: raw` have color and underscore

`"layout": "raw"` should have unstyled `<a />` and `<p />` elements as well

---

.changeset/polite-nails-mix.md
packages/nextra-theme-docs/src/components/flexsearch.tsx
packages/nextra-theme-docs/src/components/match-sorter-search.tsx
packages/nextra-theme-docs/src/components/search.tsx

@shuding I don't know why you added it [here](https://github.com/shuding/nextra/commit/41e7b915b79b1cfa5ddc8a8e4742009a2d00a730) but this provoke the following issue
https://user-images.githubusercontent.com/7361780/185764644-b113e309-4466-4744-be0c-a44d72ee7bcd.mov

fix extra space in flexsearch input after loading indexes

---

.changeset/pink-chicken-exist.md
examples/docs/src/theme.config.js
examples/swr-site/theme.config.tsx
packages/nextra-theme-docs/src/components/toc.tsx
packages/nextra-theme-docs/src/constants.tsx
packages/nextra-theme-docs/src/contexts/config.tsx
packages/nextra-theme-docs/src/types.ts
packages/nextra-theme-docs/src/utils/get-git-edit-url.ts
packages/nextra-theme-docs/src/utils/index.ts
packages/nextra-theme-docs/src/utils/render.tsx

fixes  https://github.com/shuding/nextra/issues/729
with latest refactoring it's so easy to customize elements on the page

add `editLink.component`

---

.changeset/happy-crabs-hope.md
examples/blog/next.config.mjs
examples/swr-site/next.config.js
packages/nextra-theme-blog/src/mdx-theme.tsx
packages/nextra-theme-blog/tailwind.config.js
packages/nextra-theme-docs/src/mdx-components.tsx
packages/nextra-theme-docs/tailwind.config.js
packages/nextra/package.json
packages/nextra/src/compile.ts
packages/nextra/src/components/code.tsx
packages/nextra/src/components/copy-to-clipboard.tsx
packages/nextra/src/components/index.ts
packages/nextra/src/components/pre.tsx
packages/nextra/src/icons.ts
packages/nextra/src/icons/check.tsx
packages/nextra/src/icons/copy.tsx
packages/nextra/src/icons/index.ts
packages/nextra/src/loader.ts
packages/nextra/src/mdx-plugins/rehype-handler.js
packages/nextra/src/types.ts
packages/nextra/styles/code-block.css
packages/nextra/tsup.config.ts
pnpm-lock.yaml

fixes https://github.com/shuding/nextra/issues/539
maybe rename `unstable_defaultShowCopyCode` to `unstable_defaultShowCopyButton` ?

[Blog/Docs] Add copy to clipboard button for code-blocks.

---

.changeset/tasty-moose-kick.md
packages/nextra/package.json

https://github.com/shuding/nextra/issues/736

fix react-dom peer dependency version

---

.changeset/orange-bugs-sell.md
packages/nextra-theme-docs/src/components/flexsearch.tsx
packages/nextra-theme-docs/src/components/match-sorter-search.tsx
packages/nextra-theme-docs/src/components/navbar.tsx
packages/nextra-theme-docs/src/constants.tsx
packages/nextra-theme-docs/src/types.ts

fix empty space in navbar when theme option `search.component: null`

---

.changeset/olive-brooms-behave.md
packages/nextra-theme-docs/src/components/flexsearch.tsx
packages/nextra-theme-docs/src/components/match-sorter-search.tsx
packages/nextra-theme-docs/src/components/search.tsx

PR that introduces this behaviour but fixes another issue https://github.com/shuding/nextra/pull/739

hide search input in navbar on mobile

---

.changeset/cuddly-insects-scream.md
packages/nextra/src/loader.ts

fix `ReferenceError` when trying to access `__nextra_pageOpts__` inside mdx file

---

.changeset/swift-drinks-relax.md
packages/nextra-theme-docs/src/components/callout.tsx

fix callout shrinking from children content

---

.changeset/strong-toes-decide.md
packages/nextra/src/components/pre.tsx
packages/nextra/styles/code-block.css

show copy code button only on hover of container

---

.changeset/purple-melons-begin.md
examples/blog/next.config.mjs
examples/blog/pages/posts/code-blocks.mdx
packages/nextra-theme-blog/src/article-layout.tsx
packages/nextra-theme-blog/src/mdx-theme.tsx
packages/nextra-theme-blog/src/meta.tsx
packages/nextra/package.json
packages/nextra/src/compile.ts
packages/nextra/src/loader.ts
packages/nextra/src/types.ts
pnpm-lock.yaml

fixes https://github.com/shuding/nextra/issues/683

add `nextraConfig.unstable_readingTime` option for blog theme

---

.changeset/giant-steaks-cry.md
packages/nextra-theme-docs/src/components/toc.tsx
packages/nextra-theme-docs/src/index.tsx

fixes https://github.com/shuding/nextra/issues/747

scrollbar in toc should be same as in sidebar

---

.changeset/famous-tables-knock.md
packages/nextra-theme-docs/src/components/flexsearch.tsx
packages/nextra-theme-docs/src/components/match-sorter-search.tsx
packages/nextra-theme-docs/src/components/search.tsx

fixes https://github.com/shuding/nextra/issues/747

fix ESC button when still stays after pressed ESC

---

.changeset/four-camels-jog.md
packages/nextra-theme-docs/src/components/locale-switch.tsx
packages/nextra-theme-docs/src/components/select.tsx
packages/nextra-theme-docs/src/components/theme-switch.tsx

fix covered theme switch popup when i18n is not setup

---

.changeset/fifty-rocks-shake.md
packages/nextra/styles/code-block.css

fixes https://github.com/shuding/nextra/issues/769

fix invisible copy button in code blocks

---

.changeset/lucky-plums-judge.md
packages/nextra-theme-docs/src/components/sidebar.tsx
packages/nextra-theme-docs/src/contexts/config.tsx

Fix theme switcher style

---

.changeset/twenty-apples-scream.md
packages/nextra-theme-docs/css/styles.css
packages/nextra-theme-docs/src/components/head.tsx
packages/nextra-theme-docs/src/constants.tsx
packages/nextra-theme-docs/src/contexts/config.tsx
packages/nextra-theme-docs/src/types.ts

fixes https://github.com/shuding/nextra/issues/788
https://user-images.githubusercontent.com/7361780/188018380-5681cdd2-2fcf-4639-994b-53e78ddb6adb.mov

support custom hue theme color via `primaryHue`, `primaryHue.dark` and `primaryHue.light` theme options

---

.changeset/wise-fireants-hunt.md
packages/nextra-theme-docs/css/scrollbar.css
packages/nextra-theme-docs/src/components/head.tsx
packages/nextra-theme-docs/src/components/navbar.tsx
packages/nextra-theme-docs/src/components/sidebar.tsx
packages/nextra-theme-docs/src/mdx-components.tsx

https://user-images.githubusercontent.com/7361780/188200353-bfeff78e-7d05-4ae5-9fa2-340b3f7b4dce.mov

reuse nextra's scrollbar-y styles for scrollbar-x, adjust sidebar's scrollbar-y

---

.changeset/angry-keys-matter.md
packages/nextra/src/content-dump.ts
packages/nextra/src/loader.ts

since the missing title will fallback to `frontMatter.title` here https://github.com/shuding/nextra/pull/755

`addPage` no longer need accept `frontMatter`

---

.changeset/light-shirts-judge.md
packages/nextra-theme-docs/css/scrollbar.css
packages/nextra-theme-docs/css/styles.css

fixes https://github.com/shuding/nextra/issues/800

fix disappearing toc issue in Firefox

---

.changeset/lemon-cycles-turn.md
packages/nextra-theme-docs/src/components/collapse.tsx
packages/nextra-theme-docs/src/components/sidebar.tsx

Make sure arrows are aligned with nested folders

---

.changeset/spotty-swans-explain.md
examples/swr-site/pages/docs/advanced/future-image.en-US.mdx
packages/nextra-theme-docs/src/constants.tsx
packages/nextra/src/compile.ts
packages/nextra/src/constants.ts
packages/nextra/src/content-dump.ts
packages/nextra/src/file-system.ts
packages/nextra/src/loader.ts
packages/nextra/src/mdx-plugins/static-image.ts
packages/nextra/src/page-map.ts
packages/nextra/src/plugin.ts
packages/nextra/src/utils.ts

fixes https://github.com/shuding/nextra/issues/810

replace images with `<NextImage />` even when url not relative but that starts from `/` (public directory)

---

.changeset/honest-guests-shout.md
.eslintrc.cjs
.github/workflows/ci.yml
examples/swr-site/theme.config.tsx
package.json
packages/nextra/__test__/compile.test.ts
packages/nextra/__test__/context.test.ts
packages/nextra/__test__/page-map.test.ts
packages/nextra/src/constants.ts
packages/nextra/src/loader.ts
packages/nextra/src/page-map.ts
packages/nextra/src/plugin.ts
packages/nextra/src/utils.ts

fixes https://github.com/shuding/nextra/issues/830

fix TypeError: Cannot read properties of undefined (reading 'data')

---

.changeset/twelve-spoons-kick.md
packages/nextra-theme-docs/src/components/highlight-matches.tsx

Quick attempt at fixing - https://github.com/vercel/turborepo/issues/1946

fix(search): handle case when value is empty

---

.changeset/giant-elephants-sit.md
docs/components/card/index.tsx
packages/nextra-theme-blog/src/mdx-theme.tsx
packages/nextra-theme-blog/src/meta.tsx

Just a small commit for now, however i have been looking into another issue on the console, which says,
> repeated forward or backslash are not allowed in routes

found some missing passHrefs to a tags,  reduce some warnings at DOM levels

---

.changeset/sharp-horses-happen.md
packages/nextra-theme-blog/src/theme-switch.tsx
packages/nextra-theme-docs/src/components/head.tsx
packages/nextra-theme-docs/src/components/theme-switch.tsx

just because resolvedTheme will be `dark`/`white`

use resolvedTheme instead renderedTheme + theme check

---

.changeset/thirty-buses-fold.md
packages/nextra-theme-docs/src/components/navbar.tsx
packages/nextra-theme-docs/src/index.tsx

1. Export ThemeSwitch to allow using this in custom docs footers
2. Support fully custom social links

chore(docs): export ThemeSwitch & custom social

---

.changeset/wet-trainers-sleep.md
packages/nextra/__test__/__snapshots__/page-map.test.ts.snap
packages/nextra/__test__/sort-pages.test.ts
packages/nextra/src/plugin.ts
packages/nextra/src/utils.ts

fixes https://github.com/shuding/nextra/issues/835

capitalize sidebar's folders names if item is missing in `_meta.json`

---

.changeset/shy-horses-help.md
examples/swr-site/pages/docs/_meta.en-US.json
packages/nextra-theme-docs/__test__/__snapshots__/normalize-page.spec.ts.snap
packages/nextra-theme-docs/src/components/sidebar.tsx
packages/nextra-theme-docs/src/constants.tsx
packages/nextra-theme-docs/src/types.ts
packages/nextra-theme-docs/src/utils/normalize-pages.ts
packages/nextra/__test__/__snapshots__/context.test.ts.snap
packages/nextra/__test__/__snapshots__/page-map.test.ts.snap

fixes https://github.com/shuding/nextra/issues/821

add `_meta.json#theme.collapsed` option for control state sidebar's folders

---

.changeset/smart-maps-greet.md
packages/nextra-theme-docs/src/components/banner.tsx
packages/nextra-theme-docs/src/constants.tsx
packages/nextra-theme-docs/src/types.ts

fixes https://github.com/shuding/nextra/issues/827

add new theme option `banner.dismissible`

---

README.md

Signed-off-by: Jie Peng <im@jiepeng.me>

chore: change yarn to pnpm made command consistent

---

.changeset/lazy-timers-teach.md
packages/nextra-theme-docs/src/components/search.tsx

fixes https://github.com/shuding/nextra/issues/949

add missing border for search container

---

.changeset/moody-mails-complain.md
packages/nextra-theme-docs/src/components/search.tsx
packages/nextra-theme-docs/src/constants.tsx
packages/nextra-theme-docs/src/types.ts

fixes https://github.com/shuding/nextra/issues/933

add new option `search.loading` for control loading text

---

pages/themes/docs/configuration.mdx

| before | after  |
|---|---|
|<img width="798" alt="截圖 2022-10-31 21 12 43" src="https://user-images.githubusercontent.com/10325111/199016537-c3484069-ce1b-4f82-9a60-e360ebc62611.png">|<img width="810" alt="截圖 2022-10-31 21 12 36" src="https://user-images.githubusercontent.com/10325111/199016532-d075451d-a9ad-4b05-ac17-87c578bbc72b.png">|
Signed-off-by: Jie Peng <im@jiepeng.me>

docs: remove redundant slash

---

CODE_OF_CONDUCT.md

noticed this project does not have a CODE OF CONDUCT. It seems large enough to warrant one, though @shuding shoulders the decision and the moderation responsibility

feat(app): add CODE_OF_CONDUCT

---

docs/pages/docs/guide/image.mdx

Congrats on v2!
Ugh, this project keeps making exaclty what I've been slowly slowly building for my own lil git-based blogging engine!

Fix lil typo in Nextjs image

---

packages/nextra/__test__/locale.test.ts

fixed in: https://github.com/vercel/next.js/pull/39381

use named export from next

---

.changeset/shy-walls-beam.md
docs/pages/docs/get-started.mdx.backup
docs/pages/docs/guide/image.mdx
docs/pages/docs/guide/syntax-highlighting.mdx
examples/blog/next.config.mjs
examples/docs/next.config.js
examples/docs/src/pages/features/image.mdx
examples/docs/src/pages/get-started.mdx
examples/docs/src/pages/themes/blog/index.mdx
examples/docs/src/pages/themes/docs/configuration.mdx
examples/docs/src/pages/themes/docs/index.mdx
examples/docs/src/theme.config.js
examples/swr-site/next.config.js
packages/nextra/src/components/pre.tsx

also, I removed all `unstable_` suffixes in repo
related https://github.com/shuding/nextra/issues/1010

make code-blocks buttons focusable if they are visible on page

---

.changeset/violet-elephants-hope.md
packages/nextra-theme-blog/src/mdx-theme.tsx
packages/nextra-theme-docs/src/components/anchor.tsx

small improvement saw in https://github.com/shuding/nextra/issues/1010

inform screen readers of externals links that open in a new tabs

---

docs/pages/docs/docs-theme/page-configuration.mdx
docs/pages/docs/docs-theme/theme-configuration.mdx
docs/pages/index.mdx

Address some issues reported in #1010.

Improve docs

---

docs/pages/docs/guide/i18n.mdx

Improve docs for i18n

---

.changeset/config.json
.changeset/forty-dolls-dress.md
docs/components/file-tree/index.tsx
docs/pages/docs/index.mdx
docs/pages/index.mdx
examples/swr-site/theme.config.tsx
packages/nextra-theme-blog/src/mdx-theme.tsx
packages/nextra-theme-docs/css/styles.css
packages/nextra-theme-docs/src/components/breadcrumb.tsx
packages/nextra-theme-docs/src/components/highlight-matches.tsx
packages/nextra-theme-docs/src/components/input.tsx
packages/nextra-theme-docs/src/components/nav-links.tsx
packages/nextra-theme-docs/src/components/navbar.tsx
packages/nextra-theme-docs/src/components/not-found.tsx
packages/nextra-theme-docs/src/components/search.tsx
packages/nextra-theme-docs/src/components/select.tsx
packages/nextra-theme-docs/src/components/server-side-error.tsx
packages/nextra-theme-docs/src/components/sidebar.tsx
packages/nextra-theme-docs/src/components/tabs.tsx
packages/nextra-theme-docs/src/components/toc.tsx
packages/nextra-theme-docs/src/index.tsx
packages/nextra-theme-docs/src/mdx-components.tsx
packages/nextra/src/components/copy-to-clipboard.tsx
packages/nextra/src/components/pre.tsx
packages/nextra/styles/subheading-anchor.css

Some are related to #1010. I adjusted the default primary color from 500 to 600, also made it more keyboard friendly.
https://user-images.githubusercontent.com/3676859/205468386-b7179be8-7356-4969-a7ea-f1fc4145b329.mp4

Improve a11y

---

.changeset/config.json
.changeset/giant-steaks-scream.md
examples/blog/pages/tags/[tag].mdx
packages/nextra-theme-blog/__test__/tag.spec.ts
packages/nextra-theme-blog/package.json
packages/nextra-theme-blog/src/index.tsx
packages/nextra-theme-blog/src/tags.tsx
packages/nextra-theme-blog/src/utils/get-tags.ts
packages/nextra-theme-blog/tsup.config.ts

statically generate tags for blog theme
close https://github.com/shuding/nextra/issues/641

feat: static tag title 

---

docs/pages/docs/docs-theme/theme-configuration.mdx

Add '_' to Twitter Link

---

packages/nextra/src/components/copy-to-clipboard.tsx
packages/nextra/src/components/pre.tsx

fixes https://github.com/shuding/nextra/issues/956

fix(#956): fixed copy into clipboard to have the correct indentation

---

.changeset/brown-rice-attend.md
packages/nextra/src/components/pre.tsx

refacor https://github.com/shuding/nextra/pull/1059

copy button refactor and changeset

---

.changeset/new-boxes-enjoy.md
packages/nextra-theme-docs/src/components/navbar.tsx

fixes https://github.com/shuding/nextra/issues/1028

fix `Navbar />` elements `key` prop

---

.changeset/thin-bulldogs-enjoy.md
examples/swr-site/next.config.js
packages/nextra/src/constants.ts
packages/nextra/src/content-dump.ts
packages/nextra/src/file-system.ts
packages/nextra/src/index.js
packages/nextra/src/loader.ts
packages/nextra/src/plugin.ts
packages/nextra/src/types.ts

fixes https://github.com/shuding/nextra/issues/1085

[nextra] support `nextConfig.distDir`

---

docs/package.json
docs/pnpm-lock.yaml

Fixes the warning:
```
Error: No Next.js version could be detected in your project. Make sure `"next"` is installed in "dependencies" or "devDependencies"
```

docs: Fix build warning

---

.changeset/kind-tigers-promise.md
packages/nextra-theme-docs/src/components/banner.tsx

- Add aria label for banner dismiss button

fix(nextra-theme-docs): add aria label for banner dismiss button

---

.changeset/rare-flies-check.md
examples/blog/theme.config.jsx
examples/swr-site/theme.config.tsx
packages/nextra-theme-docs/src/constants.tsx
packages/nextra-theme-docs/src/index.tsx

fixes https://github.com/shuding/nextra/issues/1118

fix hydration for default `gitTimestamp` component

---

.changeset/plenty-experts-push.md
docs/pages/docs/guide/syntax-highlighting.mdx
packages/nextra/package.json
packages/nextra/src/theme.json
packages/nextra/styles/variables.css
pnpm-lock.yaml

fixes https://github.com/shuding/nextra/issues/934

update shiki to v0.12.1

---

.changeset/thirty-papayas-do.md
examples/swr-site/next.config.js
packages/nextra/__test__/locale-with-base-path.test.ts
packages/nextra/__test__/locale.test.ts
packages/nextra/src/locales.ts

fixes https://github.com/shuding/nextra/issues/1111

support `nextConfig.basePath` with i18n + tests

---

.changeset/fast-games-grow.md
packages/nextra-theme-docs/src/components/locale-switch.tsx

feat: support basePath with locale switch

---

docs/pages/about.mdx

It helped me a lot while fixing mistakes in CSS classes https://github.com/shuding/nextra/pull/944

mention `eslint-plugin-tailwindcss` in about.mdx

---

.changeset/twenty-mirrors-fold.md
packages/nextra-theme-docs/src/components/navbar.tsx
packages/nextra-theme-docs/src/components/not-found.tsx
packages/nextra-theme-docs/src/components/server-side-error.tsx
packages/nextra-theme-docs/src/mdx-components.tsx
packages/nextra/src/components/copy-to-clipboard.tsx
packages/nextra/styles/code-block.css

A few style improvements for the navbar links, `h2` and `a` elements.

Style improvements

---

.changeset/real-pumpkins-deny.md
examples/swr-site/package.json
examples/swr-site/pages/docs/remote/foo.en-US.mdx
packages/nextra/__test__/__snapshots__/context.test.ts.snap
packages/nextra/__test__/__snapshots__/page-map.test.ts.snap
packages/nextra/src/compile.ts
pnpm-lock.yaml

Ref: https://github.com/hashicorp/next-mdx-remote/issues/307#issuecomment-1363415249

Fix remote MDX error with Next.js 13

---

.changeset/weak-pigs-fail.md
docs/pages/docs/docs-theme/theme-configuration.mdx
examples/swr-site/theme.config.tsx
packages/nextra-theme-docs/src/components/toc.tsx
packages/nextra-theme-docs/src/constants.tsx
packages/nextra-theme-docs/src/types.ts

fixes https://github.com/shuding/nextra/issues/1029

add new option `feedback.useLink`

---

.changeset/new-ladybugs-relax.md
packages/nextra-theme-blog/src/styles.css

fixes https://github.com/shuding/nextra/issues/1163

[blog] fix inline code blocks style regression

---

.changeset/hot-carrots-sit.md
docs/pages/docs/guide/latex.mdx
examples/docs/src/pages/features/latex.mdx
packages/nextra-theme-docs/src/contexts/config.tsx
packages/nextra/src/loader.ts

fix `undefined: undefined` property in `useConfig()`

---

.changeset/beige-seals-sniff.md
examples/blog/theme.config.jsx
package.json
packages/nextra-theme-docs/src/components/sidebar.tsx
pnpm-lock.yaml

fixes https://github.com/shuding/nextra/issues/1169

Always close mobile nav when route was changed (e.g. logo click)

---

.changeset/late-years-relax.md
packages/nextra/src/mdx-plugins/static-image.ts

fixes https://github.com/shuding/nextra/issues/1146

fix static images on windows

---

docs/pages/docs/blog-theme/start.mdx
docs/theme.config.tsx
packages/nextra-theme-docs/src/components/skip-nav.tsx

Update the time of copyright. Happy new year.

fix(docs): update the copyright time info

---

.changeset/yellow-insects-mix.md
docs/pages/docs/guide/syntax-highlighting.mdx
packages/nextra/src/components/copy-to-clipboard.tsx
packages/nextra/src/components/pre.tsx

Allow copying dynamic code

---

.changeset/late-bears-explode.md
.changeset/modern-laws-cough.md
docs/package.json
docs/pnpm-lock.yaml
examples/swr-site/next.config.mjs
examples/swr-site/pages/docs/advanced/more/tree/one.en-US.mdx
examples/swr-site/pages/docs/advanced/more/tree/two.en-US.mdx
examples/swr-site/pages/test.en-US.md
examples/swr-site/theme.config.tsx
package.json
packages/nextra-theme-docs/src/index.tsx
packages/nextra/__test__/__snapshots__/context.test.ts.snap
packages/nextra/__test__/__snapshots__/page-map.test.ts.snap
packages/nextra/src/compile.ts
packages/nextra/src/layout.ts
packages/nextra/src/loader.ts
packages/nextra/src/types.ts
pnpm-lock.yaml

`getStaticProps` from the MDX page take priority over `getStaticProps` from the theme config
fixes https://github.com/shuding/nextra/issues/1227

support `getStaticProps` from theme config

---

.changeset/hip-starfishes-try.md
docs/pages/docs/docs-theme/theme-configuration.mdx
packages/nextra-theme-docs/src/components/sidebar.tsx
packages/nextra-theme-docs/src/constants.tsx

This can be a nice addition to current API so you can customize titles under a specific folder easily.

Pass route to titleComponent

---

.changeset/gold-weeks-give.md
packages/nextra/__test__/compile.test.ts
packages/nextra/src/compile.ts
packages/nextra/src/constants.ts
packages/nextra/src/mdx-plugins/rehype.js

fixes https://github.com/shuding/nextra/issues/1280

fix missing filename, add filename / copy code with `codeHighlight: false`, add various tests

---

.changeset/tender-suns-fold.md
packages/nextra/src/loader.ts
packages/nextra/src/setup-page.ts
packages/nextra/src/utils.ts
turbo.json

See detailed explanation here: https://github.com/shuding/nextra/pull/1268/files#r1080669178

fix: Warning of dynamic imports

---

.changeset/healthy-chicken-shave.md
packages/nextra-theme-docs/src/components/collapse.tsx

fixes https://github.com/shuding/nextra/issues/1302

fix `<Collapse />` initial animation

---

.changeset/rare-penguins-hide.md
packages/nextra/__test__/__snapshots__/page-map.test.ts.snap
packages/nextra/__test__/page-map.test.ts
packages/nextra/src/constants.ts
packages/nextra/src/context.ts
packages/nextra/src/loader.ts
packages/nextra/src/plugin.ts

fixes https://github.com/shuding/nextra/issues/1315

fix when sidebar show non-md folders

---

.changeset/gold-tools-deliver.md
docs/pages/docs/docs-theme/theme-configuration.mdx
packages/nextra-theme-docs/src/components/flexsearch.tsx
packages/nextra-theme-docs/src/components/search.tsx
packages/nextra-theme-docs/src/constants.tsx
packages/nextra/src/search/plugin.ts

Closes #1309. This PR also adds an `error` state and option.

Fix search index output location

---

.changeset/little-phones-rush.md
packages/nextra/src/loader.ts

CC @B2o5T this should address the `fs` related problem!

Fix bug in loader

---

.changeset/ten-houses-grow.md
packages/nextra-theme-docs/src/constants.tsx
packages/nextra-theme-docs/src/contexts/config.tsx
packages/nextra-theme-docs/src/index.tsx
packages/nextra-theme-docs/src/types.ts
packages/nextra-theme-docs/src/utils/normalize-pages.ts

add zod validation for _meta.json "theme" property

---

.changeset/ten-houses-grow.md
.changeset/thin-coats-guess.md
.eslintrc.cjs
examples/swr-site/components/remote-utils.js
packages/nextra-theme-docs/src/constants.tsx
packages/nextra-theme-docs/src/contexts/config.tsx
packages/nextra-theme-docs/src/index.tsx
packages/nextra-theme-docs/src/types.ts
packages/nextra-theme-docs/src/utils/normalize-pages.ts

fixes https://github.com/shuding/nextra/issues/1335

use `z.strictObject` instead `z.object` in zod theme validation, improve zod error messages

---

.changeset/serious-baboons-collect.md
packages/nextra-theme-docs/src/contexts/config.tsx

fix treeshake of zod validation on prod build

---

.changeset/light-parents-perform.md
packages/nextra/src/loader.ts

fixes https://github.com/shuding/nextra/issues/1345

compile mdx with `format: 'detect'` in loader

---

.changeset/three-dots-heal.md
packages/nextra/src/mdx-plugins/static-image.ts

fixes https://github.com/shuding/nextra/issues/1344

use `decodeURI` in static-image.ts

---

.changeset/thin-kiwis-study.md
packages/nextra/src/locales.ts

fixes https://github.com/shuding/nextra/issues/1354

ignore `.xml` files in locales middleware

---

.changeset/plenty-radios-sparkle.md
packages/nextra-theme-blog/package.json
packages/nextra-theme-docs/package.json
pnpm-lock.yaml

I'm seeing some issues in certain package mangers caused by this.

Add `nextra` to themes' peer deps

---

.changeset/fluffy-zebras-taste.md
packages/nextra-theme-docs/css/styles.css
packages/nextra-theme-docs/src/components/collapse.tsx
packages/nextra-theme-docs/src/components/navbar.tsx
packages/nextra-theme-docs/src/components/select.tsx
packages/nextra-theme-docs/src/components/sidebar.tsx

Some style improvements of padding, border, animation, etc. For example these places:

Style tweaks

---

.changeset/good-flowers-allow.md
examples/swr-site/theme.config.tsx
packages/nextra-theme-blog/src/types.ts
packages/nextra-theme-blog/src/utils/get-tags.ts
packages/nextra-theme-docs/src/contexts/config.tsx
packages/nextra/src/compile.ts
packages/nextra/src/types.ts

fixes https://github.com/shuding/nextra/issues/1222

typed frontmatter -> `useConfig<YOUR_FRONTMATTER_TYPE>`

---

.changeset/kind-pandas-change.md
examples/swr-site/pages/docs/getting-started.en-US.mdx
packages/nextra-theme-docs/src/components/head.tsx
packages/nextra-theme-docs/src/index.tsx

fixes https://github.com/shuding/nextra/issues/1284

fix overflow for main content on desktop and mobile

---

.changeset/pretty-wombats-kick.md
.eslintrc.cjs
examples/swr-site/pages/docs/getting-started.en-US.mdx
package.json
packages/nextra-theme-blog/src/utils/parent.ts
packages/nextra-theme-docs/src/components/navbar.tsx
packages/nextra-theme-docs/src/utils/normalize-pages.ts
packages/nextra/src/compile.ts
pnpm-lock.yaml

fixes https://github.com/shuding/nextra/issues/1032

fix raw `__esModule` string ☠️

---

.changeset/tough-hotels-remember.md
packages/nextra-theme-docs/src/index.tsx

fixes https://github.com/shuding/nextra/issues/1379

fix for `theme: { footer: false }` still showed the footer

---

.changeset/sour-cobras-check.md
packages/nextra/src/index.js

fixes https://github.com/shuding/nextra/issues/1395

fix rewrites

---

docs/pages/docs/docs-theme/theme-configuration.mdx
docs/pages/docs/guide/syntax-highlighting.mdx

fixes https://github.com/shuding/nextra/issues/1400

chore: add code highlighting option to docs

---

.changeset/spotty-poets-count.md
packages/nextra/src/components/td.tsx
packages/nextra/src/components/th.tsx
packages/nextra/src/components/tr.tsx

Just some low hanging fruit.
Fixes #1398

fix custom class names fully overriding default component styles

---

.changeset/giant-apes-breathe.md
packages/nextra/src/locales.ts

fixes https://github.com/shuding/nextra/issues/1402

do not redirect `.txt` files in nextra's locales middleware

---

.changeset/thin-countries-agree.md
docs/pages/docs/guide/organize-files.mdx
docs/pages/showcase.mdx
packages/nextra-theme-docs/src/components/sidebar.tsx

fixes  https://github.com/shuding/nextra/issues/1412

fix squeezed sidebar when he was hidden -> navigated to page without sidebar -> comeback to page with sidebar

---

.changeset/clean-dogs-brake.md
packages/nextra-theme-docs/src/components/sidebar.tsx

fixes https://github.com/shuding/nextra/issues/1412

fix white appearing of white square while sidebar was toggled

---

.changeset/rude-rocks-judge.md
packages/nextra-theme-blog/src/index.tsx
packages/nextra-theme-docs/src/contexts/config.tsx

fixes https://github.com/shuding/nextra/issues/1389 https://github.com/shuding/nextra/issues/478

force theme to `light` if `darkMode: false` was set

---

packages/nextra-theme-docs/__test__/use-fs-route.spec.ts
packages/nextra-theme-docs/src/utils/use-fs-route.ts

fix: remove trailing slash

---

.changeset/sweet-candles-visit.md
examples/swr-site/next.config.mjs
examples/swr-site/pages/remote/graphql-yoga/[[...slug]].mdx
packages/nextra-theme-docs/package.json
pnpm-lock.yaml

fixes https://github.com/shuding/nextra/issues/1451 https://github.com/dotansimha/graphql-code-generator/pull/8965 https://github.com/dotansimha/graphql-yoga/pull/2403

bump @headlessui/react to ^1.7.10

---

.changeset/six-drinks-lick.md
packages/nextra-theme-docs/css/styles.css

Fix the capital letter M is displayed incorrectly on Xiaomi phones

---

.changeset/shy-rockets-run.md
packages/nextra-theme-docs/src/components/callout.tsx

As mentioned here: https://github.com/shuding/nextra/issues/1516

Fix overflow of latex in Callouts

---

.changeset/wild-singers-fix.md
packages/nextra-theme-blog/src/meta.tsx
packages/nextra-theme-docs/css/styles.css
packages/nextra-theme-docs/src/components/banner.tsx
packages/nextra-theme-docs/src/components/footer.tsx
packages/nextra-theme-docs/src/components/nav-links.tsx
packages/nextra-theme-docs/src/components/navbar.tsx
packages/nextra-theme-docs/src/components/sidebar.tsx
packages/nextra-theme-docs/src/index.tsx

Hide some unnecessary parts of the page, like navbar, sidebar, when being printed. fixes #1502

Optimize Printing Experience

---

docs/pages/docs/docs-theme/theme-configuration.mdx

should consider i18n locale when composing url just to be accurate

update: theme-configuration.mdx

---

.changeset/long-starfishes-peel.md
packages/nextra-theme-blog/src/index.tsx
packages/nextra-theme-docs/src/contexts/config.tsx

Revert "force theme to `light` if `darkMode: false` was set"

---

.changeset/ten-glasses-brake.md
packages/nextra/src/loader.ts

fixes https://github.com/shuding/nextra/issues/1602

do not auto create `_app.mdx` if missing

---

.changeset/witty-needles-tap.md
examples/swr-site/pages/docs/getting-started.en-US.mdx
packages/nextra-theme-docs/src/components/file-tree.tsx

fix filetree for 2 folders

---

.changeset/wild-weeks-remember.md
examples/swr-site/pages/docs/getting-started.en-US.mdx
packages/nextra-theme-docs/src/mdx-components.tsx

fixes https://github.com/shuding/nextra/issues/1579

fix `<summary />` when children contains `<p />`

---

nervous-tigers-camp.md

I only remove an unnecessary changeset file.

chore: Remove an unnecessary changeset file

---

.changeset/popular-lizards-provide.md
examples/blog/theme.config.jsx
packages/nextra-theme-blog/src/meta.tsx
packages/nextra-theme-blog/src/posts-layout.tsx
packages/nextra-theme-blog/src/types.ts

add date formatter to the configuration 
related to https://github.com/shuding/nextra/issues/1648

feat: add date formatter

---

.changeset/brown-moose-sparkle.md
packages/nextra-theme-docs/src/components/locale-switch.tsx

fixes https://github.com/shuding/nextra/issues/1742

use `<span />` instead `<div />` inside `<button />` for local switch button

---

.changeset/tall-weeks-tap.md
.gitignore
examples/swr-site/pages/docs/change-log.en-US.mdx
examples/swr-site/pages/docs/change-log.es-ES.mdx
examples/swr-site/pages/docs/change-log.ru.mdx
package.json
packages/nextra/src/index.js
pnpm-lock.yaml

fixes https://github.com/shuding/nextra/issues/1694

do not throw error when `output: 'export'` is specified in `next.config.js`

---

.changeset/strong-rings-begin.md
.eslintrc.cjs
docs/package.json
docs/pages/docs/docs-theme/theme-configuration.mdx
examples/blog/package.json
examples/docs/package.json
examples/swr-site/package.json
examples/swr-site/theme.config.tsx
package.json
packages/nextra-theme-blog/package.json
packages/nextra-theme-docs/__test__/normalize-page.spec.ts
packages/nextra-theme-docs/package.json
packages/nextra-theme-docs/src/components/toc.tsx
packages/nextra-theme-docs/src/constants.tsx
pnpm-lock.yaml

Allow for the editing of TOC values in addition to the entire TOC.

Add valueComponent to TOC

---

.changeset/silver-squids-repair.md
examples/swr-site/pages/docs/getting-started.en-US.mdx
packages/nextra-theme-docs/src/components/anchor.tsx
packages/nextra-theme-docs/src/index.tsx
packages/nextra-theme-docs/src/mdx-components.tsx

fixes https://github.com/shuding/nextra/issues/1693

export `<Link />` from theme docs

---

.changeset/calm-doors-search.md
packages/nextra-theme-docs/src/components/sidebar.tsx
packages/nextra/src/loader.ts

fixes https://github.com/shuding/nextra/issues/1758

fix regression of sidebar style for folder

---

.changeset/breezy-cameras-cry.md
docs/package.json
examples/swr-site/pages/remote/[slug].mdx
examples/swr-site/pages/remote/_meta.js
package.json
packages/nextra-theme-blog/package.json
packages/nextra-theme-docs/package.json
packages/nextra/package.json
packages/nextra/src/file-system.ts
packages/nextra/src/hooks/use-fs-route.ts
packages/nextra/src/use-internals.ts
packages/nextra/src/utils.ts
packages/nextra/tsup.config.ts
pnpm-lock.yaml

fix(nextra): avoid named imports from find-pages-dir

---

.changeset/violet-penguins-compare.md
.github/workflows/ci.yml
.github/workflows/nextjs-bundle-analysis.yml
packages/nextra-theme-docs/src/index.tsx

Replace nx-overflow-x-hidden by nx-overflow-clip

---

.changeset/famous-ears-switch.md
packages/nextra/src/compile.ts
packages/nextra/src/ssg.tsx

fixes https://github.com/shuding/nextra/issues/1842

fix Module not found: Can't resolve '.../node_modules/nextra/dist/mdx.mjs'

---

.changeset/gorgeous-walls-brush.md
packages/nextra/src/search/plugin.ts

fix: Search index not generating in certain Next.js versions

---

.changeset/hungry-glasses-try.md
docs/pages/docs/guide/_meta.json
docs/pages/docs/guide/mermaid.mdx
packages/nextra/package.json
packages/nextra/src/compile.ts
pnpm-lock.yaml

fixes https://github.com/shuding/nextra/issues/1373

support mermaid diagrams

---

docs/pages/docs/docs-theme/theme-configuration.mdx
docs/pages/docs/guide/advanced/table.mdx
docs/pages/docs/guide/i18n.mdx
docs/pages/docs/guide/syntax-highlighting.mdx
package.json

just a few language tweaks as I read through the docs

content tweaks

---

.changeset/blue-apes-swim.md
docs/pages/docs/docs-theme/page-configuration.mdx
docs/pages/docs/docs-theme/theme-configuration.mdx
packages/nextra-theme-blog/src/mdx-theme.tsx
packages/nextra-theme-docs/src/components/anchor.tsx

fix https://github.com/shuding/nextra/issues/2025

`opens in new tab` span element should have `user-select: none`

---

.changeset/great-trains-drop.md
.changeset/lemon-chefs-occur.md
examples/swr-site/pages/_meta.en-US.json
examples/swr-site/pages/_meta.ru.json
examples/swr-site/pages/blog.en-US.mdx
examples/swr-site/pages/blog.ru.mdx
examples/swr-site/pages/blog/_meta.es-ES.json
examples/swr-site/pages/blog/_meta.ru.json
examples/swr-site/theme.config.tsx
packages/nextra-theme-docs/src/components/footer.tsx
packages/nextra-theme-docs/src/components/locale-switch.tsx
packages/nextra-theme-docs/src/components/navbar.tsx
packages/nextra-theme-docs/src/components/sidebar.tsx
packages/nextra-theme-docs/src/index.tsx
packages/nextra/__test__/__snapshots__/context.test.ts.snap
packages/nextra/__test__/__snapshots__/page-map.test.ts.snap
packages/nextra/__test__/normalize-page.spec.ts
packages/nextra/src/normalize-pages.ts
pnpm-lock.yaml

fixes https://github.com/shuding/nextra/issues/1760
fixes https://github.com/shuding/nextra/issues/2131

fix i18n `Warning: Prop `href` did not match. Server: "/blog.en-US#" Client: "/blog#"`

---

.changeset/curvy-pigs-ring.md
.changeset/flat-cougars-enjoy.md
.changeset/great-trains-drop.md
.changeset/lemon-chefs-occur.md
.changeset/mean-geckos-study.md
.changeset/odd-baboons-swim.md
.changeset/rude-timers-beam.md
.changeset/ten-pans-shake.md
.changeset/tough-flowers-press.md
.changeset/warm-pens-travel.md
packages/nextra-theme-blog/CHANGELOG.md
packages/nextra-theme-blog/package.json
packages/nextra-theme-docs/CHANGELOG.md
packages/nextra-theme-docs/package.json
packages/nextra/CHANGELOG.md
packages/nextra/package.json

Revert "Version Packages"

---

.changeset/weak-tigers-double.md
packages/nextra-theme-docs/src/utils/get-git-issue-url.ts

fixes https://github.com/shuding/nextra/issues/2169

fix feedback.labels for gitlab

---

.changeset/sour-cups-care.md
packages/nextra/package.json

fixes https://github.com/shuding/nextra/issues/2089

fix ts error `Cannot find module 'nextra/filter-route-locale'`

---

.changeset/weak-poems-explode.md
packages/nextra/src/components/pre.tsx

fixes https://github.com/shuding/nextra/issues/2172

remove `font-weight: 500;` from styles of code blocks since it gives no effect

---

.changeset/tiny-melons-cough.md
examples/swr-site/pages/foo.en-US.md
packages/nextra/__test__/__snapshots__/context.test.ts.snap
packages/nextra/__test__/__snapshots__/page-map.test.ts.snap
packages/nextra/package.json
packages/nextra/src/compile.ts
packages/nextra/src/mdx-plugins/static-image.ts
packages/nextra/src/mdx.ts
packages/nextra/src/mdx.tsx
packages/nextra/tsup.config.ts
pnpm-lock.yaml

fixes https://github.com/shuding/nextra/issues/1936
fixes https://github.com/shuding/nextra/issues/1821

allow override static image component, support `<details />`/`<summary />` for `.md` files

---

.changeset/neat-lemons-repair.md
docs/pages/docs/docs-theme/theme-configuration.mdx
docs/theme.config.tsx
examples/swr-site/theme.config.tsx
packages/nextra-theme-docs/src/components/back-to-top.tsx
packages/nextra-theme-docs/src/components/toc.tsx
packages/nextra-theme-docs/src/constants.tsx

fixes https://github.com/shuding/nextra/issues/2061

add toc.backToTop option

---

.changeset/red-mayflies-shake.md
.eslintrc.cjs
packages/nextra-theme-docs/src/components/sidebar.tsx
packages/nextra/src/mdx-plugins/remark-headings.ts

related https://github.com/shuding/nextra/issues/1796#issuecomment-1690590418

do not render mobile sidebar on desktop

---

.changeset/tame-cooks-sneeze.md
packages/nextra-theme-docs/src/components/flexsearch.tsx
packages/nextra/src/compile.ts
packages/nextra/src/mdx-plugins/index.ts
packages/nextra/src/mdx-plugins/remark-headings.ts
packages/nextra/src/mdx-plugins/remark-mdx-disable-explicit-jsx.ts
packages/nextra/src/mdx-plugins/remark-structurize.ts

fixes https://github.com/shuding/nextra/issues/2077

fix `Out of Memory` in search while indexing large words

---

packages/nextra/package.json
pnpm-lock.yaml

Revert "fix(deps): update dependency rehype-raw to v7"

---

.changeset/fluffy-rings-play.md
examples/blog/theme.config.jsx
packages/nextra-theme-blog/src/cusdis.tsx
packages/nextra-theme-blog/src/mdx-theme.tsx
packages/nextra-theme-blog/src/meta.tsx
packages/nextra-theme-blog/src/nav.tsx
packages/nextra-theme-blog/src/posts-layout.tsx
packages/nextra-theme-blog/src/types.ts

- remove `legacyBehavior` from `NextLink`
- remove `config.cusdis`. Instead, now you need to pass cusdis options as props in `Cusdis` component

[v3] blog changes

---

.changeset/fair-balloons-talk.md
packages/nextra-theme-docs/src/constants.tsx
packages/nextra/__test__/loader.test.ts
packages/nextra/src/context.ts
packages/nextra/src/index.ts
packages/nextra/src/loader.ts
packages/nextra/src/normalize-pages.ts
packages/nextra/src/plugin.ts
packages/nextra/src/server/utils.ts
packages/nextra/src/setup-page.tsx
packages/nextra/src/utils.ts

set default `head` option as `null` in nextra-theme-docs and improve bundle little but

[v3] set default `head` option as `null` in `nextra-theme-docs` and improve bundle size

---

.github/workflows/lint.yml
.github/workflows/nextjs-bundle-analysis.yml
.github/workflows/release.yml
.github/workflows/test.yml
docs/next.config.mjs
docs/package.json
examples/blog/package.json
examples/docs/package.json
examples/swr-site/package.json
package.json
packages/nextra-theme-blog/package.json
packages/nextra-theme-docs/package.json
packages/nextra/package.json
packages/nextra/src/file-system.ts
pnpm-lock.yaml
renovate.json5

fixes https://github.com/shuding/nextra/issues/2322

bump next.js to 13.5.2

---

.changeset/blue-worms-guess.md
.changeset/nine-papayas-end.md
packages/nextra-theme-docs/src/components/search.tsx
packages/nextra/package.json
pnpm-lock.yaml

fixes https://github.com/shuding/nextra/issues/2219

update `npm2yarn`, add bun tab

---

.changeset/sour-boxes-breathe.md
.gitignore
docs/package.json
examples/blog/package.json
examples/docs/package.json
examples/swr-site/package.json
package.json
packages/nextra-theme-blog/package.json
packages/nextra-theme-docs/package.json
packages/nextra/package.json
packages/nextra/src/file-system.ts
pnpm-lock.yaml

fixes https://github.com/shuding/nextra/discussions/2342

fix `Property 'existsSync' does not exist on type`

---

docs/pages/docs/guide/i18n.mdx

I was not able to get i18n working as documented, the default language page worked, but once I tried a Chinese page I started getting errors about too many redirects.  I tried the config used in the Vercel SWR docs and was successful.
I am not sure if the Arabic code you used was for Saudi Arabia or another, I just picked one randomly.
Thanks for Nextra, I like what I have seen.

update i18n docs

---

.changeset/two-scissors-prove.md
packages/nextra-theme-blog/src/mdx-theme.tsx
packages/nextra-theme-docs/src/components/anchor.tsx
packages/nextra-theme-docs/src/components/toc.tsx

fixes https://github.com/shuding/nextra/issues/2426

[v3] remove possible links in toc elements

---

docs/pages/docs/docs-theme/start.mdx

fixes https://github.com/shuding/nextra/issues/2476

docs: add hint about adding scripts in package.json

---

docs/pages/docs/index.mdx

based on comments here : https://github.com/shuding/nextra/discussions/1142#discussioncomment-4552759
I put this entry first in FAQ list because it seems quite important.

docs: add FAQ item about support of next.js app router

---

.changeset/hungry-planets-repeat.md
.eslintrc.cjs
examples/swr-site/pages/en/docs/advanced/images.mdx
packages/nextra/src/server/remark-plugins/__tests__/remark-static-images.test.ts
packages/nextra/src/server/remark-plugins/remark-static-image.ts

fixes https://github.com/shuding/nextra/issues/2605

[v3] support importing images by markdown image definitions

---

examples/swr-site/next-env.d.ts
packages/nextra/__test__/__snapshots__/page-map.test.ts.snap
packages/nextra/__test__/page-map.test.ts

snapshot wasnt updated after https://github.com/shuding/nextra/commit/1a364694d3433a59f555cb73c0cf3802c633d65c so test in my #2658 pr was failing

test: update snapshot

---

.github/workflows/nextjs-bundle-analysis2.yml

same as #2662 but for new workflow file

chore: use `pull_request_target` event to fix comment on pr

---

.github/workflows/nextjs-bundle-analysis.yml

this change is needed in `main` branch so #2245 ci can pass, after that u can rebase it with `v3`

chore: update path of downloaded artifact

---

.github/workflows/nextjs-bundle-analysis.yml
docs/pages/docs/guide/test.mdx

Sorry for the mess up, hopefully this one will be the last pr to fix the workflow

chore: fix workflow

---

.changeset/seven-pens-scream.md
examples/swr-site/pages/en/docs/getting-started.mdx
packages/nextra-theme-blog/package.json
packages/nextra-theme-docs/package.json
packages/nextra/src/client/components/steps.tsx
packages/nextra/styles/steps.css
pnpm-lock.yaml

fixes https://github.com/shuding/nextra/issues/2788

[v3] fix wrong numbering for nested `<Steps />`

---

.changeset/long-years-occur.md
.changeset/three-pandas-joke.md
packages/nextra-theme-docs/src/components/toc.tsx
packages/nextra-theme-docs/src/index.tsx
packages/nextra/src/client/components/table.tsx

fixes https://github.com/shuding/nextra/issues/2826
fixes https://github.com/shuding/nextra/issues/2824

[v3] use `overflow-x-auto` instead `overflow-x-scroll` for `<Table />`

---

.changeset/pretty-tips-refuse.md
packages/nextra-theme-docs/src/components/bleed.tsx
packages/nextra-theme-docs/src/components/toc.tsx
packages/nextra/src/server/compile.ts
packages/nextra/src/server/schemas.ts

fixes https://github.com/shuding/nextra/issues/2855 https://github.com/shuding/nextra/issues/2859

fix unclickable links in TOC / allow passing `recmaPlugins` in `mdxOptions`

---

.changeset/giant-gifts-care.md
.github/workflows/lint.yml
.github/workflows/nextjs-bundle-analysis.yml
.github/workflows/release.yml
.github/workflows/test.yml
examples/blog/pages/posts/lists.mdx
examples/swr-site/pages/en/docs/getting-started.mdx
packages/nextra-theme-docs/src/components/flexsearch.tsx
packages/nextra-theme-docs/src/components/sidebar.tsx
packages/nextra-theme-docs/src/mdx-components.tsx
packages/nextra/src/client/components/pre.tsx

fixes https://github.com/shuding/nextra/issues/1217
fixes https://github.com/shuding/nextra/issues/2753

[v3] fix vertical margin for nested ordered `<ol />` and unordered `<ul />` lists

---

.changeset/brave-hats-flow.md
packages/nextra-theme-docs/src/components/back-to-top.tsx

fixes https://github.com/shuding/nextra/issues/2917

[v3] fixes case when setting `disabled: true` on the scroll to top button prevents scrolling to most top

---

.changeset/hot-readers-sell.md
.eslintrc.cjs
packages/nextra-theme-docs/src/components/flexsearch.tsx
packages/nextra-theme-docs/src/components/search.tsx
packages/nextra/src/server/compile.ts

fixes https://github.com/shuding/nextra/issues/2840

[v3] fix page scroll jump while entering characters in the search input

---

.changeset/red-lions-greet.md
examples/swr-site/pages/en/docs/getting-started.mdx
examples/swr-site/pages/es/docs/getting-started.mdx
packages/nextra-theme-docs/src/mdx-components.tsx

fixes https://github.com/shuding/nextra/issues/2941

[v3] fixed `<summary />` lost whitespaces when there is some HTML element inside

---

pnpm-lock.yaml

Revert "fix(deps): update dependency yaml to v2.5.0"

---

docs/pages/docs/guide/built-ins/filetree.mdx

Wrote introduction sentence, explained example and usage sections.

Add descriptive text to filetree.mdx

---

docs/pages/docs/guide/link.mdx

Defined SPA and linked to wikipedia page, and added link to Next.js links to Next.js docs.

Update link.mdx with links and context

---

docs/pages/docs/guide/built-ins/cards.mdx

Add introduction text and usage explanation to cards.mdx

---

docs/pages/docs/guide/advanced/tailwind-css.mdx

Add guidance to integrate with TailwindCSS.
Related shuding/nextra-docs-template#45

docs(tailwind): Update tailwind-css.mdx

---

.changeset/little-camels-scream.md
.changeset/spotty-cobras-flash.md
docs/app/docs/guide/organize-files/page.mdx
docs/app/docs/page.mdx
docs/app/showcase/page.mdx
examples/blog/app/posts/(with-comments)/nextra-components/page.mdx
examples/swr-site/app/[lang]/layout.tsx
packages/nextra-theme-docs/src/components/head.tsx
packages/nextra/src/client/components/callout.tsx
packages/nextra/src/client/components/cards.tsx

fixes https://github.com/shuding/nextra/issues/2772#issuecomment-1985977827

[v4] support `<Head>`'s `backgroundColor.dark/light` props colors in `rgb(...,...,...)` and `#RRGGBB` formats

---

.changeset/chilled-kiwis-relate.md
docs/pages/docs/docs-theme/theme-configuration.mdx
docs/theme.config.tsx
packages/nextra-theme-docs/src/components/sidebar.tsx

fixes https://github.com/shuding/nextra/issues/3313

[v3] fix unclickable links on mobile

---

docs/pages/about.mdx

I updated the About page and mentioned Oscar Xie @87xie  as well :) Thank you!

update About page

---

docs/next.config.mjs

I saw it reduce bundle size in v4

add `optimizePackageImports: ['@components/icons']` for nextra.site

---

.changeset/gold-bikes-check.md
packages/nextra-theme-docs/src/components/sidebar.tsx
packages/nextra-theme-docs/src/contexts/config.tsx

reported by @hasparus 
https://github.com/user-attachments/assets/93eec64c-4561-420b-bf09-edca3a76b8ee

add `max-md:_overflow-hidden` instead of `_overflow-hidden` when hamburger is clicked

---

.changeset/thirty-geckos-repair.md
packages/nextra-theme-docs/src/components/navbar.tsx

fixes https://github.com/shuding/nextra/issues/3403

add ring-inset for navbar links

---

.changeset/ninety-news-behave.md
.changeset/silver-poems-turn.md
docs/pages/docs/_meta.ts
docs/pages/docs/docs-theme/page-configuration.mdx
docs/pages/docs/index.mdx
packages/nextra/package.json
packages/nextra/src/server/page-map.ts
pnpm-lock.yaml

fixes https://github.com/shuding/nextra/issues/3475#issuecomment-2419404008 and https://github.com/shuding/nextra/pull/3297#issuecomment-2414864868

Fix `frontMatter.sidebarTitle` didn't affect without `frontMatter.title` set

---

.changeset/gentle-eyes-bathe.md
docs/components/ready-to-go.mdx
docs/pages/docs/guide/advanced/remote.mdx
examples/blog/pages/_app.jsx
examples/docs/src/pages/_app.jsx
package.json
packages/nextra/src/server/index.ts
packages/nextra/src/server/rehype-plugins/rehype.ts
pnpm-lock.yaml

fixes https://github.com/shuding/nextra/issues/3473

bump next 15 rc1

---

docs/pages/docs/docs-theme/theme-configuration.mdx

Documentation for sidebarTitle per https://github.com/shuding/nextra/issues/3475

chore: document sidebarTitle frontmatter

---

docs/pages/docs/docs-theme/theme-configuration.mdx

* replace text with content property in code-block example

fix: banner and footer codeblock example

---

docs/pages/docs/guide/advanced/mermaid.mdx
docs/pages/docs/guide/advanced/table.mdx
docs/pages/docs/guide/built-ins/steps.mdx
docs/pages/docs/guide/syntax-highlighting.mdx
packages/nextra/vitest.config.ts

remove no longer working way to have styled table https://github.com/shuding/nextra/issues/3530

update table docs

---

.changeset/purple-doors-float.md
examples/docs/app/layout.jsx
packages/nextra-theme-docs/src/components/navbar/index.tsx

fixes https://github.com/shuding/nextra/issues/3532

[v4] remove default value of `Navbar.logo`, now this prop is required

---

.changeset/clean-items-tan.md
packages/nextra-theme-docs/src/components/sidebar.tsx
packages/nextra-theme-docs/src/mdx-components/heading.tsx
packages/nextra-theme-docs/src/style.css
packages/nextra/styles/subheading-anchor.css

https://github.com/user-attachments/assets/edbd7732-2672-4240-959b-5c7651065abe
inspired by
https://github.com/user-attachments/assets/57209265-99fa-4c9b-b629-c3a0a76213f9

[v4] add opacity animation for `:target` state for headings h2-h6

---

.changeset/moody-foxes-carry.md
packages/nextra/src/server/index.ts
packages/nextra/src/server/loader.ts

to help users with https://github.com/shuding/nextra/issues/3357 issues

[v3] requires to have a custom App component (`pages/_app.jsx`)

---

.changeset/thick-dingos-cry.md
examples/docs/src/pages/advanced/code-highlighting.mdx
packages/nextra/__test__/fixture/page-maps/folder-index-page-and-folder-should-be-merged/_meta.ts
packages/nextra/__test__/fixture/page-maps/folder-index-page-and-folder-should-be-merged/generated-page-map.ts
packages/nextra/__test__/normalize-page.spec.ts
packages/nextra/src/client/normalize-pages.ts
packages/nextra/vitest.config.ts

fixes https://github.com/shuding/nextra/issues/3581

[v3] fix folder's index page was not merged with folder itself for some edge case

---

.changeset/silver-news-scream.md
docs/app/docs/built-ins/head/_slider.tsx
docs/app/docs/built-ins/head/page.mdx
packages/nextra/__test__/generate-page-map.test.ts
packages/nextra/src/server/generate-page-map.ts
packages/nextra/src/server/index.ts
packages/nextra/src/server/schemas.ts

this fn needs to be simplified, all snapshots pass

[v4] simplify `generatePageMapFromFilepaths`

---

.changeset/curvy-beds-smile.md
packages/nextra-theme-docs/src/components/navbar/index.client.tsx
packages/nextra-theme-docs/tailwind.config.ts
packages/nextra/src/client/components/head.tsx

fixes https://github.com/shuding/nextra/issues/3645

fix unable to select text and `::selection` style

---

.changeset/orange-camels-sip.md
.eslintrc.cjs
docs/app/layout.tsx
packages/nextra-theme-docs/src/components/sidebar.tsx
packages/nextra-theme-docs/src/components/toc.tsx
packages/nextra-theme-docs/src/stores/config.tsx
packages/nextra-theme-docs/src/style.css
packages/nextra/src/client/mdx-components.tsx
packages/nextra/src/server/loader.ts

fixes https://github.com/shuding/nextra/issues/3659

remove `transition` for `transform` property when opening mobile nav

---

docs/app/docs/advanced/customize-the-cascade-layers/page.mdx

Closes: N/A
Update the cascade layers documentation for v4.
The changes are available [here](https://nextra-v2-git-fork-87xie-update-cascade-layers-docs-for-v4-shud.vercel.app/docs/advanced/customize-the-cascade-layers).

[v4] update the cascade layers docs

---

.changeset/cold-rings-double.md
docs/app/docs/custom-theme/page.mdx
docs/app/docs/docs-theme/page-configuration/page.mdx
docs/app/docs/guide/i18n/page.mdx
docs/app/docs/guide/search/page.mdx
docs/app/docs/guide/static-exports/page.mdx
docs/app/docs/guide/syntax-highlighting/page.mdx
examples/blog/app/_meta.global.js
examples/blog/app/layout.jsx
examples/blog/app/posts/(with-comments)/draft/page.mdx
examples/blog/app/posts/get-posts.js
packages/nextra-theme-blog/src/components/go-back.tsx
packages/nextra-theme-blog/src/components/navbar.tsx
packages/nextra-theme-blog/src/types.ts
packages/nextra/CHANGELOG.md
packages/nextra/src/server/__tests__/to-page-map.test.ts
packages/nextra/src/server/rehype-plugins/rehype-extract-toc-content.ts

fixes https://github.com/shuding/nextra/issues/1801

[v4] remove `BlogMetadata.draft`, support `_meta` files for `nextra-theme-blog`

---

.changeset/real-fishes-double.md
packages/nextra/src/client/mdx.ts

fixes https://github.com/shuding/nextra/issues/2897

fix unable override injected `img` component

---

.changeset/lucky-queens-burn.md
packages/nextra/src/client/components/cards.tsx
packages/nextra/styles/cards.css

I think adding `ellipsis` props to Card is a reasonable request.
Closes:https://github.com/shuding/nextra/issues/3855

Adding `ellipsis` props to Card component

---

.changeset/moody-jars-film.md
.changeset/sharp-foxes-carry.md
.changeset/short-bulldogs-matter.md
packages/nextra-theme-blog/src/components/layout.tsx
packages/nextra-theme-docs/src/mdx-components/index.tsx
packages/nextra-theme-docs/src/mdx-components/wrapper.client.tsx
packages/nextra/src/client/components/head.tsx
packages/nextra/src/types.ts

fixes while doing GraphQL Yoga migration https://github.com/dotansimha/graphql-yoga/pull/3570

[v4] fix `colorSchema` for HEX format, add `bottomContent` prop for `<Wrapper>` component

---

docs/app/docs/built-ins/cards/page.mdx

fix https://github.com/shuding/nextra/issues/3898

fix broken links on `/docs/built-ins/cards`

---

docs/app/_meta.global.ts
docs/next.config.ts

closes https://github.com/shuding/nextra/issues/3903

Update next.config.ts. redirect /docs/docs-theme/theme-configuration

---

.changeset/cuddly-colts-heal.md
.prettierignore
docs/app/_meta.global.ts
docs/app/about/page.mdx
docs/app/blog/page.mdx
docs/app/docs/blog-theme/start/page.mdx
docs/app/docs/docs-theme/built-ins/layout/page.mdx
docs/app/docs/docs-theme/start/page.mdx
docs/app/docs/guide/content-directory/page.mdx
docs/app/docs/guide/github-alert-syntax/page.mdx
docs/app/docs/guide/mdx-components-file/page.mdx
docs/app/docs/guide/meta-file/page.mdx
docs/app/docs/guide/page-file/page.mdx
docs/app/docs/guide/page.mdx
docs/app/docs/guide/src-directory/page.mdx
docs/app/layout.tsx
docs/components/ready-to-go.mdx
examples/docs/src/app/docs/[[...mdxPath]]/page.jsx
examples/swr-site/app/[lang]/[[...mdxPath]]/page.tsx
examples/swr-site/app/[lang]/remote/graphql-eslint/[[...slug]]/page.tsx
examples/swr-site/app/[lang]/remote/graphql-yoga/[[...slug]]/page.tsx
packages/nextra/src/client/components/file-tree/file.tsx
packages/nextra/src/server/__tests__/to-page-map.test.ts
packages/nextra/src/server/rehype-plugins/rehype.ts

closes https://github.com/shuding/nextra/issues/3938

fix highlighting for ```mdx lang and improve docs for `/docs/docs-theme/start`

---

.changeset/strange-horses-vanish.md
docs/app/docs/built-ins/banner/page.mdx
docs/app/docs/built-ins/head/page.mdx
docs/app/docs/built-ins/search/page.mdx
docs/app/docs/docs-theme/built-ins/footer/page.mdx
docs/app/docs/docs-theme/built-ins/layout/page.mdx
docs/app/docs/docs-theme/built-ins/navbar/page.mdx
docs/app/docs/docs-theme/built-ins/not-found/page.mdx
docs/app/docs/file-conventions/meta-file/page.mdx
docs/app/docs/file-conventions/page.mdx
docs/components/content-and-app-file-tree.tsx
packages/nextra/src/client/components/file-tree/file.tsx
packages/nextra/src/client/components/file-tree/tree.tsx
packages/nextra/src/server/loader.ts

closes https://github.com/shuding/nextra/issues/3988

fix build crash after renaming mdx pages

---

.changeset/quick-goats-work.md
examples/docs/src/content/get-started.mdx
packages/nextra/src/client/__tests__/remove-links.test.tsx
packages/nextra/src/client/remove-links.ts
packages/nextra/src/server/__tests__/__snapshots__/compile.test.ts.snap
packages/nextra/src/server/__tests__/compile.test.ts
packages/nextra/src/server/__tests__/latex.test.ts
packages/nextra/src/server/__tests__/recma-rewrite.test.ts
packages/nextra/src/server/__tests__/rehype-extract-toc-content.test.ts
packages/nextra/src/server/__tests__/remark-mdx-frontmatter.test.ts
packages/nextra/src/server/__tests__/remark-remove-imports.test.ts
packages/nextra/src/server/__tests__/remark-static-images.test.ts
packages/nextra/src/server/rehype-plugins/rehype-extract-toc-content.ts

closes https://github.com/shuding/nextra/issues/3979

fix crash of Nextra when `props` are used within headings, e.g. `## Hello {props.something}`

---

.changeset/twelve-fishes-tan.md
packages/nextra/src/server/loader.ts

closes https://github.com/shuding/nextra/issues/4016 https://github.com/shuding/nextra/discussions/3986

do not log a bunch of `Failed to get the last modified timestamp from Git for the file` messages if init git repository failed

---

docs/app/_meta.global.tsx

closes https://github.com/shuding/nextra/issues/3933

add Deploying link in sidebar to point in next.js docs

---

.changeset/rude-trees-warn.md
packages/nextra/src/server/__tests__/remark-mdx-frontmatter.test.ts
packages/nextra/src/server/__tests__/to-page-map.test.ts
packages/nextra/src/server/remark-plugins/remark-mdx-frontmatter.ts

closes https://github.com/shuding/nextra/issues/4021

fix parsing empty front matter

---

.changeset/cuddly-cups-promise.md
docs/app/docs/built-ins/tabs/page.mdx
packages/nextra/src/client/components/search.tsx
packages/nextra/src/client/components/tabs/index.client.tsx
packages/nextra/src/env.d.ts
packages/nextra/src/server/__tests__/compile.test.ts
packages/nextra/src/server/remark-plugins/remark-headings.ts

fixes https://github.com/shuding/nextra/issues/2927

select right tab and scroll into view when html element with `location.hash` id is inside `<Tabs.Tab>`

---

.changeset/sweet-bikes-shave.md
packages/nextra-theme-docs/src/components/sidebar.tsx

fix https://github.com/shuding/nextra/issues/4052

fix cropped sidebar footer on desktop, when nextra's `<Banner>` is used

---

.changeset/tidy-apples-beam.md
docs/app/layout.tsx
packages/nextra-theme-docs/src/components/navbar/index.client.tsx
packages/nextra-theme-docs/src/components/navbar/index.tsx
packages/nextra-theme-docs/src/components/toc.tsx
packages/nextra/src/client/components/search.tsx

missing transitions on link elements and missing out transition on the logo
Introduce transition effects to enhance interactions within the navbar and table of contents components.

Add transition effects to navbar and TOC components

---

.changeset/hot-jobs-accept.md
packages/nextra-theme-blog/src/style.css
packages/nextra-theme-docs/src/style.css
packages/nextra/src/client/components/banner/close-banner-button.tsx
packages/nextra/src/client/components/banner/index.client.tsx
packages/nextra/src/client/components/banner/index.tsx

fixes https://github.com/shuding/nextra/issues/4079 cc @hichemfantar

calculate `--nextra-banner-height` after mounting banner, so banner text can be wrapped on multiple lines

---

.changeset/new-years-sit.md
packages/nextra-theme-docs/src/components/back-to-top.tsx
packages/nextra-theme-docs/src/components/toc.tsx

back to top pops in and out suddenly
Enhance the link styling by adjusting the transition effects for a smoother fade in and out experience.

Implement back to top fade in and out transitions

---

.changeset/angry-ladybugs-doubt.md
packages/nextra-theme-docs/src/components/back-to-top.tsx
packages/nextra-theme-docs/src/components/navbar/index.client.tsx
packages/nextra-theme-docs/src/components/toc.tsx

no animation
Enhance the NavbarMenu component by refining its animation effects, resulting in a smoother user experience.
https://headlessui.com/react/menu#adding-transitions
https://github.com/user-attachments/assets/0d849d10-28bc-407c-98e0-31841208e2bd
docusaurus
https://github.com/user-attachments/assets/5c3ff8de-a168-44b2-a064-b8210304e579

enable animations for NavbarMenu

---

.changeset/fluffy-mails-laugh.md
docs/app/about/page.mdx
docs/app/docs/docs-theme/built-ins/layout/page.mdx
docs/app/showcase/page.mdx
docs/app/sponsors/page.mdx
packages/nextra-theme-blog/src/components/go-back.tsx
packages/nextra-theme-blog/src/components/theme-switch.tsx
packages/nextra-theme-docs/src/components/back-to-top.tsx
packages/nextra-theme-docs/src/components/locale-switch.tsx
packages/nextra-theme-docs/src/components/navbar/index.client.tsx
packages/nextra-theme-docs/src/components/sidebar.tsx
packages/nextra-theme-docs/src/components/theme-switch.tsx
packages/nextra-theme-docs/src/mdx-components/wrapper.client.tsx
packages/nextra/src/client/components/banner/index.client.tsx
packages/nextra/src/client/components/banner/index.tsx
packages/nextra/src/client/components/button.tsx
packages/nextra/src/client/components/select.tsx
packages/nextra/src/client/mdx-components/pre/copy-to-clipboard.tsx
packages/nextra/src/client/mdx-components/pre/index.tsx
packages/nextra/src/client/remove-links.ts

reimplement https://github.com/shuding/nextra/pull/4095
closes https://github.com/shuding/nextra/issues/4036

allow configuring `theme.toc` with `layout: 'default'` in `_meta` files

---

.changeset/yellow-hounds-provide.md
packages/nextra-theme-docs/src/components/toc.tsx
packages/nextra-theme-docs/src/mdx-components/wrapper.client.tsx

closes https://github.com/shuding/nextra/issues/2711

fix: show `Scroll to top` link `toc.backToTop` when `toc.float: false` is set

---

docs/app/layout.tsx

disable transitions for users who prefer reduced motion
Introduce a class to the navbar logo that disables transitions for users who prefer reduced motion, enhancing accessibility.

Add motion-reduce class to navbar logo for improved transition handling

---

.changeset/rotten-candles-hide.md
docs/app/docs/file-conventions/page.mdx
packages/nextra/src/server/page-map/index-page.ts
packages/nextra/src/server/page-map/index.ts
packages/nextra/src/server/schemas.ts
packages/nextra/styles/cards.css

fixes https://github.com/shuding/nextra/issues/4181#issuecomment-2645985731

add `display: 'normal' | 'hidden'` for `_meta` item `type: 'menu'`

---

.changeset/hungry-beds-brush.md
packages/nextra/src/client/pages.ts

fix: importPage URl decoding should use decodeURIComponent

---

.changeset/friendly-suns-dream.md
packages/nextra/src/client/components/search.tsx

fix: make search results appear above the navbar

---

.changeset/great-moments-wave.md
README.md
packages/nextra-theme-docs/src/layout.tsx

fixes https://github.com/shuding/nextra/issues/4301

fix: better error message for `Layout#lastUpdated` prop. Ensure `lastUpdated` is React component and not React fragment.

---

.changeset/light-walls-end.md
packages/nextra/src/server/loader.ts
packages/nextra/src/server/schemas.ts

closes https://github.com/shuding/nextra/issues/1446

fix: allow override `NextraConfig.mdxOptions.format` option in `next.config` file

---

.changeset/icy-turkeys-search.md
packages/nextra-theme-docs/src/components/sidebar.tsx

fixes https://github.com/shuding/nextra/issues/4280

Fix collapse behaviour of sidebar

---

.changeset/major-bananas-film.md
packages/nextra-theme-docs/src/components/sidebar.tsx
packages/nextra-theme-docs/src/style.css

fixes https://github.com/shuding/nextra/issues/4447

fix phantom scroll when footer is disabled

---

.changeset/silent-brooms-swim.md
.prettierignore
docs/app/_meta.global.tsx
docs/app/docs/advanced/latex/page.mdx
docs/app/docs/advanced/mermaid/page.mdx
docs/app/docs/advanced/npm2yarn/page.mdx

closes https://github.com/shuding/nextra/issues/4341 https://github.com/shuding/nextra/issues/4191

improve LaTeX docs, mention that you need apply styles for KaTeX https://nextra.site/docs/advanced/latex#apply-styles

---

.changeset/polite-queens-sell.md
docs/app/docs/advanced/tailwind-css/page.mdx
docs/app/globals.css

fixes https://github.com/shuding/nextra/issues/4490

update Tailwind CSS guide to match v4 version https://nextra.site/docs/advanced/tailwind-css

---

docs/app/docs/docs-theme/start/page.mdx

In v3, the following sections were "Page Configuration" and "Theme Configuration". Starting from v4, the subsequent sections have changed, so I updated the guide in the "Get Started" doc to reflect this change.
Closes: N/A

Update the next sections guide for docs theme v4

---

.changeset/cyan-towns-refuse.md
packages/nextra/src/client/components/search.tsx
packages/tsdoc/src/__tests__/snapshots/search.json
pnpm-lock.yaml

The `Search` component currently does not have custom callbacks. In practice, it is often important to collect data about what users are searching for.
Closes: #3103.
This PR adds an `onSearch` callback to the `SearchProps` in `client/components/search.tsx`. This callback, when specified, is called upon every search input change.

Add callback in search component

---

.changeset/floppy-webs-notice.md
packages/nextra/src/server/tsdoc/base.ts
packages/nextra/src/server/tsdoc/tsdoc.tsx
packages/tsdoc/src/__tests__/base.test.ts

fixes https://github.com/shuding/nextra/issues/4517

feat(tsdoc): support `@inline` tag and fix mobile overflow in `<TSDoc />` table

---

docs/app/docs/advanced/latex/page.mdx
docs/app/docs/advanced/npm2yarn/page.mdx
docs/app/docs/guide/custom-css/page.mdx
docs/app/docs/guide/image/page.mdx
docs/app/page.tsx
examples/docs/src/content/features/image.mdx
examples/docs/src/content/get-started.mdx
examples/docs/src/content/themes/blog/index.mdx
examples/docs/src/content/themes/docs/index.mdx

to fix broken links
Closes:
https://github.com/shuding/nextra/issues/4726
https://github.com/shuding/nextra/issues/4724
https://github.com/shuding/nextra/issues/4589
Just broken links, nothing else

Fix broken links
